### ISSUE TITLE
Add ledger-diff command

### ISSUE THREAD

**Issue by MarkusTeufelberger** [XRPLF/rippled#1343]
The "ledger-diff" command would take 2 ledger identifiers (source and target) as well as the other switches from the "ledger" command and instead of returning all data, it would only return the nodes that differ between these 2 ledgers. A typical way to use this command would be to query for one full ledger, store it locally and then issue ledger-diff commands for a couple interesting ledgers nearby.

A potential use case would be for services that query a lot of historic ledgers (Ripple data API...) but don't always want to transfer ~100 MB of (mostly stale) data every new ledger close to get the current ledger.
Another use case would be to make it possible to use some kind of "checkpoint" ledger for distributing data.
It would also allow alternative implementations of rippled to use RPC/Websockets for acquiring historical data more easily instead of having to rely on the (still undocumented) protobuf based peer protocol.

**Comment by MarkusTeufelberger** [comment]
Sooo... it's close to 9 months now, any ideas here if this is a good or bad thing to have?

The ability to compare 2 SHAmaps (or meanwhile also 2 SHAmap2s) to get a diff between them is something that I think has to happen at rippled level, as the amount of data + the time for transferring it alone means that it is nearly impossible to do this externally at scale.

Loading a handful of full binary ledgers sequentially at ~21.5million from a (GBit-LAN) local rippled with warm cache, SSD + NuDB datastore via RPC takes around 7 seconds each time.

Even though these 5 ledgers at that height create ~1.1GB in traffic (each one about 220 MB) and have about 761900 nodes (including inner nodes) each, they contain only 762900 unique nodes (again: including inner nodes) in total! Currently the only way to get to this data, which is important to actually verify the 2 hashes in ledger headers, is to ask for the full binary ledgers each time. The only time saved is after the first (longer) query that hits the node store, when the cache gets warm. Using ledger_diff, it would be possible to only transfer the initial 220MB and then transfer only the little data (even just the leafs, just like rippled already does) that changed between each ledger close.

There might be complexity attacks though (diffing very old against very new ledgers and the like), so I'd suggest exposing it unlimited as admin only and publicly only within a (configurable) maximum distance between 2 ledgers.
However, as written, this technique would maybe also help in historic data acquisition... currently my node stands at about 7.5 TB in traffic (mostly inbound) and has by FAR not managed to receive the ~3 TB or so of nodes that Ripple currently consists of in total. This wastes lots of time and resources of the other servers and the internet as a whole. If other nodes would send leaf diffs instead of inner nodes down to a certain depth starting from the root nodes, traffic would go down quite a bit while still offering a trustless(!) way to transfer historic data (since inner nodes can be generated from leafs and the root hashes for verification are in the headers anyways). Fetch packs of inner nodes can still be a fallback mechanism and/or be used for getting new data reaching forward. Going backwards, leaf diffs seem to me like a less wasteful way to obtain data.

**Comment by sublimator** [comment]
Pull request ?

**Comment by MarkusTeufelberger** [comment]
Not from me until I have feedback if it even has a chance of being merged.

Also shamap code is being worked on all the time and  critical to the program, so asking for feedback and then writing a more formal implementation plan imho is the way to go. Feel free to immediately post your pull request though and see how this works out...

**Comment by yxxyun** [comment]
bitcoin have a proposal, similar but not same, BIP152  
https://github.com/bitcoin/bips/blob/master/bip-0152.mediawiki

@JoelKatz @nbougalis I want to hear your opinions.

**Comment by vinniefalco** [comment]
Low priority...

**Comment by MarkusTeufelberger** [comment]
Closed with which resolution? Not possible? Not on Ripple roadmap, but community PRs that implement this are welcome? Even a community PR would not get merged?

After 3 years and 4 words in total from Ripple on asking for feedback on a design question, this is getting a bit frustrating. :-(

**Comment by nbougalis** [comment]
Considering the age of this issue, I didn't really think keeping the issue open made sense. 

I'd be happy to consider an external PR. You suggested you aren't interested in the absence of knowing that such a PR has a chance of being merged. We've always been willing to merge any PR that meaningfully improves the code or adds new features. Can I guarantee that a PR implementing this it will be merged? No. But we will review it carefully and thoroughly and work with any the submitted to make it happen. 

This isn't something that we have the resources to implement right now, and I believe that with sharding there are not better and more efficient mechanisms for retrieving data.

I'm going to reopen this issue because you're still interested.

**Comment by nbougalis** [comment]
I'd like to understand your end-goal a litle better. Do you want to be able to ask the server to produce a JSON object that shows the differences between two ledgers? Do you want to limit this to account roots, order books, or everything? Would you include "bookkeeping" entries (e.g. directory pages and the like?)

**Comment by MarkusTeufelberger** [comment]
One use case scenario:

I wrote a script to process individual full ledgers (https://developers.ripple.com/ledger.html with `"full": true`) to get metrics, similar to the DataAPI. This is fine to run, as long as I can process ledgers faster than they get produced (say every 3 seconds). Unfortunately since a few years now it takes longer to fetch a full ledger from the node_db than the next ledger close. Even if the entire node_db were stored in RAM and the command would send a reply instantly, already the network connection to transmit the data from the rippled server to the analytics program would need to be quite a bit beyond 1 Gb/s. The difference between 2 ledgers that follow each other is extremely small in comparison (a couple of leaf nodes in the account_state trie, the header and all transactions). It would be much nicer to get a full "checkpoint ledger" every now and then and only get a diff for everything in between.

Another use case:

To synchronize a server with the network that has been down for a bit (e.g. for maintenance), it could be cheaper to load the last known good ledger, ask your peers for a diff to the current ledger and apply that instead of syncing the whole state from scratch.

BIP 152 (linked above) also maps out a similar use case for synchronizing large parts of history with smaller impact on network resources.

Another use case would be to have a checkpointed mode of operations (could be combined with sharding), where every n-th ledger is stored in full in the node store and ledgers that get requested in between are being communicated as diffs between servers.

My personal use case is number 1 however - it is currently not possible to analyze the ledger in close to real-time because the data volumes involved are either too large in the case of full ledgers (rippled takes more than 3 seconds to come up with the data and it is too large to transfer) or not guaranteed to be complete or even available (in the case of subscribing to e.g. the `transactions` feed). I'd personally need everything that contributes to the hash of a ledger, so even inner nodes (but these are probably cheaper to be computed than to transmit them over the network - they are also not available in any API). For some other use cases, a filter similar to the one available in `ledger_entry` might be useful I guess.

I think I remember @WietseWind also had a few use cases for a command like this, I guess for his https://ledger.exposed/ site, so maybe he can also explain why it would be nice to have this.

**Comment by carlhua** [comment]
Revisited this - and we feel this would be better implemented outside rippled vs as part of rippled impl. Closing the issue now

**Comment by MarkusTeufelberger** [comment]
How could this efficiently be implemented outside `rippled`? This needs direct access to the node store which is only available to a single `rippled` instance. Could you give an outline how something outside `rippled` can do this operation better than `rippled` itself?

**Comment by cjcobb23** [comment]
A version of this command will be implemented as part of the reporting mode project

**Comment by cjcobb23** [comment]
@MarkusTeufelberger you can actually implement this outside of `rippled` by parsing transaction metadata. The transaction metadata describes all of the changes between a ledger and the previous one. This method would probably become inefficient when trying to get a diff between two non-consecutive ledgers, but for consecutive ledgers, parsing transaction metadata would describe all ledger changes except the skiplist update.

**Comment by cjcobb23** [comment]
Reopening this issue as a version of this command is incoming as part of the reporting mode project

**Comment by cjcobb23** [comment]
@MarkusTeufelberger the ledger_diff command has been implemented as part of the reporting mode PR:
https://github.com/ripple/rippled/pull/3609/files#diff-58fbed39e1be96771899476986dd4e7a
https://github.com/ripple/rippled/pull/3609/files#diff-56c53607eaf52d33be627c11cb0fab01

What do you think? Is this what you were looking for? Can you use gRPC or do you need the output in JSON? gRPC is going to be more efficient.

**Comment by intelliot** [comment]
@MarkusTeufelberger could you take a look at this?

**Comment by cjcobb23** [comment]
FYI clio supports something like this: https://xrpl.org/ledger-clio.html

**Comment by MarkusTeufelberger** [comment]
Clio seems to only report diffs between the previous and the specified ledger, so if I request ledger 1.000.000 with "diff=true", I'll get the difference from 999.999 to 1.000.000. What I'd like to have is a "diff=true, diff_ledger=900000" like functionality, to get the difference to a ledger of my choice potentially further back than a single hop. It is already better than before (you could request every single diff from start to finish and then merge these before requesting individual objects by hash).

Regarding reporting mode, there seems to be some undocumented RPC calls? I didn't look deeply into this, I can't find anything documented and assumed that you're planning to remove gRPC from this code base anyways.

**Comment by intelliot** [comment]
Thanks. For this use case:

"To synchronize a server with the network that has been down for a bit (e.g. for maintenance), it could be cheaper to load the last known good ledger, ask your peers for a diff to the current ledger and apply that instead of syncing the whole state from scratch."

I wonder if @thejohnfreeman 's work on Forward Ledger Replay might be relevant?

In any case, we're seeing little interest in this feature (i.e. no one beyond @MarkusTeufelberger ) and we have a ton on our plate already (both for rippled and Clio). In Clio's case, the team is working on getting the RPC testable and covered with unit tests before they add more APIs. RPCs are also being refactored (aiming to finish migration in Q1). However, **we would welcome a PR**. It probably makes the most sense in [Clio](https://github.com/XRPLF/clio).

We will, of course, consider all PRs - whether in Clio or rippled.
