### ISSUE TITLE
Quality out ineffective on Rippled payment

### ISSUE THREAD

**Issue by dchapes** [XRPLF/rippled#147]
This could just be a misunderstanding of how the quality settings are supposed to work.
To experiment with these settings I set quality_out=1.01 (actual value=1,010,000,000; I'm using ratios to 1e9 as a notational convience) on my BTC/Bitstamp and BTC/DividendRippler trust lines (leaving quality_in alone).

Transaction D01DE4419C689DC59AEF114B5A6B6B15ED664CE0A1F0DEB422178072FF65F48E was a payment from someone to DividendRippler for 1 BTC/DividendRippler using ~1.002 BTC/Bitstamp. Ripple chose three paths: Bitstamp -> {me, B, C} -> DividendRippler and sent the maximum through me and the remainder through B. Given my "fee" it should have used me only as a last resort.

My understanding was that such a transaction would consider my DR:quality_out / BS:quality_in = 1.01/1 = 1.01 and "charge" 1% (this was just an experiment, I don't really need/want to charge for this).

However, my balance was changed +0.8763125702226825 BTC/Bitstamp and -0.876312570222683 BTC/Dividend Rippler for a net of -0.0000000000000005 BTC; no 1.01 multiplier applied.

Originally reported as https://github.com/ripple/ripple-client/issues/958

[I normally wouldn't copy another issue but Bob Way specifically asked me to do so with this one; presumably so that when working on fixing/testing path finding bugs in rippled this wouldn't get overlooked as it's not a client bug (possibly at the time I didn't have access to this repository)]

**Comment by lazaridiscom** [comment]
@seelabs , what is the status of this one?

**Comment by carlhua** [comment]
@seelabs can you take a look at this and recommend a path forward?
