### ISSUE TITLE
Rippled partial payment can leave a negative balance outside of trust limits

### ISSUE THREAD

**Issue by dchapes** [XRPLF/rippled#161]
In transaction `A8C32D1B8AF07941ACCBB9E574BD83415217F940ECE3446A61773F7DDD35CD7E` a self payment (with the partial flag set) was made that rippled through several accounts.

An account who's trade offer was taken was left with a -0.00007819374138658 BTC/RippleIsrael balance on a trust line with zero limits.

The change in balance "overshot" by almost exactly 0.2%. So it looks like perhaps the 0.2% transfer fee that RippleIsrael has was charged to account that made the trade offer but not accounted for when determining the path liquidity of the payment.

The relevant part of the transaction that shows the balance being adjusted out-of-bounds is:

``` json
{
  "ModifiedNode": {
    "FinalFields": {
      "Balance": {
        "currency": "BTC",
        "issuer": "rrrrrrrrrrrrrrrrrrrrBZbvji",
        "value": "0.00007819374138658"
      },
      "Flags": 0,
      "HighLimit": {
        "currency": "BTC",
        "issuer": "r4TnS99Vcb8US2STJ4Khe939QN3wh4BjHT",
        "value": "0"
      },
      "HighNode": "0000000000000000",
      "LowLimit": {
        "currency": "BTC",
        "issuer": "rNPRNzBB92BVpAhhZr4iXDTveCgV5Pofm9",
        "value": "0"
      },
      "LowNode": "0000000000000000"
    },
    "LedgerEntryType": "RippleState",
    "LedgerIndex": "3BFDCB17A1721987864B1F0A6A5D65E1A4FDC11E31C1749CC5EF6B9EB573851C",
    "PreviousFields": {
      "Balance": {
        "currency": "BTC",
        "issuer": "rrrrrrrrrrrrrrrrrrrrBZbvji",
        "value": "-0.0390968706932923"
      },
      "Flags": 131072
    },
    "PreviousTxnID": "AD1F27B90A5D01E11EF2CCCAE746D2711550175336619ADC5886872803703B87",
    "PreviousTxnLgrSeq": 2136610
  }
}
```

A few of the trust lines had quality in/out settings but they appear to not be relevant. (Other than this appears to be another example of #147; account rnziP… had QualityIn set to 996,000,000 on their RippleIsrael line and the payment was `… -> BTC/RippleIsrael -> BTC/rnziP -> BTC/Bitstamp -> …` so the quality setting should have been applied but wasn't.)

An annotated copy of the full JSON transaction details is available at: http://pastebin.com/xaCvJQad

**Comment by lazaridiscom** [comment]
@seelabs , is the fix from @rec valid?

**Comment by carlhua** [comment]
@seelabs can you take a look at this and recommend a path forward?

**Comment by intelliot** [comment]
If this still needs to be fixed, please open a new issue with steps to reproduce the problem. Thanks!
