### ISSUE TITLE
ledger_request RPC call should request all nodes in a ledger

### ISSUE THREAD

**Issue by MarkusTeufelberger** [XRPLF/rippled#1873]
As far as I understand the code in https://github.com/ripple/rippled/blob/develop/src/ripple/rpc/handlers/LedgerRequest.cpp a ledger_request call to a ledger where only the header  is available in the nodestore/database would return the header but not fetch the missing nodes.

The expected behaviour would be closer to ledger_cleaner called with a single ledger: Checking the root hash of AS and TX and fetching all missing nodes in the tree(s) if necessary.

**Comment by JoelKatz** [comment]
I guess it's a judgment call whether we should do the additional work of verifying whether every node is present in the ledger or not. Currently, there is no way (other than invoking the ledger cleaner) to confirm that every node is in the ledger. I'm not sure it's sensible to do this by default.

**Comment by MarkusTeufelberger** [comment]
I expected to be able to have all nodes of a certain ledger available to me after sending this request. According to https://ripple.com/build/rippled-apis/#ledger-request "3. When the ledger is fully available, the response is a representation of the ledger header."

You'd get this response already after only the header was fetched but some tree nodes were still missing (which was the case on my server when I filed this bug). Since it is an admin-only call (and there are far more expensive ones out there, ressource wise), I would argue that internally invoking ledger_cleaner for confirming a ledger_request might be worth it, maaaaybe with an extra switch ("confirm=True" or whatever).

**Comment by JoelKatz** [comment]
It's as simple as constructing an `InboundLedger` object. That will confirm that the entire ledger is present (and only do any acquisition if it isn't). The tricky bit is that the only way to tell if the operation has completed is to issue another `ledger_request`, which would start another acquire/check if the ledger is present but the acquire information has purged from the cache.

**Comment by mDuo13** [comment]
I'm still supportive of making `ledger_request` work more intuitively. Maybe we could fix the problem of checking to see if the fetch has completed could be handled by using a different API method such as `fetch_info` and/or `ledger`.

**Comment by intelliot** [comment]
Let's combine this with https://github.com/XRPLF/rippled/issues/3514 - please add any comments there.
