### ISSUE TITLE
ASAN build fails unit tests on Ubuntu 16.04

### ISSUE THREAD

**Issue by MarkusTeufelberger** [XRPLF/rippled#2046]
https://github.com/ripple/rippled/issues/1668 is already closed, but the issue still persists - when running the build_all.sh script on Ubuntu 16.04, the very first build (which in my case is --static --assert --sanitize=address gcc.debug) already fails.

To reproduce, create the following Dockerfile:

    FROM ubuntu:16.04
    RUN  apt-get update \
      && apt-get -y upgrade \
      && apt-get -y install \
                  git \
                  scons \
                  ninja \
                  clang \
                  pkg-config \
                  protobuf-compiler \
                  libprotobuf-dev \
                  libssl-dev \
                  libboost-all-dev \
      && git clone --depth=1 https://github.com/ripple/rippled.git /rippled
    WORKDIR /rippled/Builds
    CMD ["/bin/bash", "/rippled/Builds/build_all.sh"]

Then run "docker build -t buildtest" and "docker run --rm --it buildtest". I am not 100% sure if the issue is with ASAN, boost-coroutine or rippled's use of these - maybe it is even already fixed upstream, but Ubuntu 16.04 still ships with Clang 3.8 by default.

**Comment by MarkusTeufelberger** [comment]
Issue still persists in 17.04, the currently latest Ubuntu release (well, soon to be release).

Dockerfile (ninja package is renamed to ninja-build):

    FROM ubuntu:17.04
    RUN  apt-get update \
      && apt-get -y upgrade \
      && apt-get -y install \
                  git \
                  scons \
                  ninja-build \
                  clang \
                  pkg-config \
                  protobuf-compiler \
                  libprotobuf-dev \
                  libssl-dev \
                  libboost-all-dev \
      && git clone --depth=1 https://github.com/ripple/rippled.git /rippled
    WORKDIR /rippled/Builds
    CMD ["/bin/bash", "/rippled/Builds/build_all.sh"]

**Comment by MarkusTeufelberger** [comment]
See https://github.com/ripple/rippled/pull/2082 fo an example of this happening.

**Comment by mellery451** [comment]
current travis builds using clang-8 are passing ASAN:  https://travis-ci.com/ripple/rippled/jobs/227886460. I'm inclined to close this, unless you are concerned about the clang versions that ship by default with the distro (we install compilers from apt.llvm.org). TSAN is still a problem and I'm not sure we can fix those easily. UBSAN is TBD, but seems like we should be able to make it pass.

**Comment by MarkusTeufelberger** [comment]
...the build you linked shows a warning from ASAN on line 1161. I'm not sure if it is actually working as expected.

**Comment by mellery451** [comment]
that warning talks about false positives, of which there are none currently. That said, it would be best to eliminate the warning (I'm thinking boost related possibly), so it warrants more investigation.

**Comment by carlhua** [comment]
@ximinez can you check if this is still an issue?

**Comment by ximinez** [comment]
This appears to still be an issue in rippled 1.6.0 with Pop OS / Ubuntu 20.04.

**Comment by intelliot** [comment]
Given the obsolete title of this issue, let's continue tracking in #4661
