### ISSUE TITLE
TSAN builds fail unit tests

### ISSUE THREAD

**Issue by MarkusTeufelberger** [XRPLF/rippled#2081]
In some cases they hang, in other cases they fail with

    ERROR:FATAL: ThreadSanitizer: unexpected memory mapping 0x7d0800000000-0x7d0800010000

I have yet to see a successful build + test run of a tsan enabled rippled binary. Is this regularly tested on your internal CI machine? It isn't on Travis at least.

**Comment by MarkusTeufelberger** [comment]
Quick PR in https://github.com/ripple/rippled/pull/2082 shows that TSAN blows up quite spectacularly.

**Comment by carlhua** [comment]
@ximinez can you check if this is still an issue?

**Comment by ximinez** [comment]
This appears to still be an issue in rippled 1.6.0 with Pop OS / Ubuntu 20.04.

**Comment by intelliot** [comment]
notes:
- low priority
- @MarkusTeufelberger or others - please feel free to re-open (or open a new issue) if you can provide more context on the benefits of this
