### ISSUE TITLE
Availability of full transaction history and ledger headers for testing

### ISSUE THREAD

**Issue by donovanhide** [XRPLF/rippled#244]
Hi,

it would be great if all the raw transaction and ledger headers from ledger 32570 onwards could be made publicly available for other implementers to test against. The rippled node takes many weeks to get the full history, even with recent patches.

The following commands executed on a running node with full history would produce the necessary files and it would be great if they could be shared somewhere:

```
sqlite3 -csv -noheader db/transaction.db  'select hex(RawTxn) from Transactions' | sed '/^$/d' | gzip -c9 >transactions.gz
sqlite3 -csv -noheader db/ledger.db  'select hex(RawData) from Validations' | sed '/^$/d' | gzip -c9 >ledger.gz
```

**Comment by lazaridiscom** [comment]
A 5 years old issue, totally unprocessed (e.g. no label) ?

**Comment by sublimator** [comment]
No label = not a priority

i suppose :)

**Comment by lazaridiscom** [comment]
Still, there are issue-categories. I assume its the usual thing: team uses internal tracker, the public one is a bit unmaintained.

**Comment by sublimator** [comment]
They used to use JIRA, not sure these days.

**Comment by MarkusTeufelberger** [comment]
They still do, but since about 1 year they plan to move to GitHub as issue tracker...

**Comment by lazaridiscom** [comment]
They have a nicely low issue count, so it should be doable. I usually am mainly interested to filter out the categories (bug, feature-request/enhancement, question).

**Comment by lazaridiscom** [comment]
To bored, and actually it affects this issue here. Looks like a feature-request, but would like to know if its still actual.

**Comment by MarkusTeufelberger** [comment]
Yes, this (public availability of "full" ledger history) is still an unsolved issue, related to #2985. Otherwise it would have been closed, I guess.

**Comment by lazaridiscom** [comment]
Ok, end of boredome, filing the obvious: https://github.com/ripple/rippled/issues/2989

**Comment by carlhua** [comment]
We should formulate a plan for this - how to orchestrate this and where to store the files etc.

**Comment by MarkusTeufelberger** [comment]
Once deterministic shards make it in (they seem to be planned to be reverted in 1.60.0-RC2?) this can be done by the community in a decentralized way (BitTorrent, IPFS...). I just don't want to start sharing a full history node database that might contain errors, that's not really verified and that is very hard to replicate - all things that will be solved eventually by deterministic shards.

**Comment by intelliot** [comment]
Going forward, [Clio](https://github.com/XRPLF/clio) is the project to implement a server that efficiently stores full transaction history and ledger headers. Creating and sharing archives / checkpoints would be a great feature for Clio; if the project doesn't already do what you'd like, feel free to open an issue there.
