### ISSUE TITLE
Disable much (most?) functionality when validation is enabled

### ISSUE THREAD

**Issue by MarkusTeufelberger** [XRPLF/rippled#2610]
While in theory it would be possible to run a node that kinda does everything (serve lots of historic data to users and the network, act as an API endpoint, validate...), it might be beneficial to disable a lot of features (node/shard store, most RPC/WS API calls, unclustered operation, the `/crawl` endpoint...) if a rippled instance is used for validation.

This might help to enforce some good practices (validators should not run alone and have `peer_private` set) and decrease the attack surface on validation servers while also making switching on validation a more concious choice.

**Comment by mDuo13** [comment]
Not a bad idea as long as you can turn it off. I like the idea of enforcing best practices by default with an opt-out switch for people who want to run an all-in-one instance.

**Comment by MarkusTeufelberger** [comment]
Yes, of course it should be possible to run using bad practices, but it should be externally visible ideally and definitely not the default.

**Comment by nbougalis** [comment]
I'm very supportive of this and there is work planned in this area.

**Comment by carlhua** [comment]
We should consider a validation only mode going that builds on top of the reporting mode.

**Comment by intelliot** [comment]
@mtrippled and others - any potential perf benefits from this idea?

Downsides?

**Comment by mtrippled** [comment]
> @mtrippled and others - any potential perf benefits from this idea?
> 
> Downsides?

This might be beneficial for the same reasons the requester suggested. The downside would be the effort involved in going through and disabling everything not necessary for a validator, and also how to factor in people who don't want other features. Ideally, trusted UNL operators would be running the same config to optimize performance and safety, so this is probably worth doing at some level.

An easier approach would be to provide tuning suggestions for validator operators, though that wouldn't disable RPC calls.

**Comment by mtrippled** [comment]
Also I don't think there there would be any intrinsic performance gains from this that couldn't be gained by implementing whatever config changes get applied.

**Comment by intelliot** [comment]
Replaced by https://github.com/XRPLF/rippled/issues/4872
