### ISSUE TITLE
Shared cluster history

### ISSUE THREAD

**Issue by nbougalis** [XRPLF/rippled#2808]
It should be possible to cluster several servers to a full history server and then allow those servers to respond to queries for ledgers that they do not have by acting as a caching proxy by quickly retrieving the relevant data from the full history server.

This can help reduce load on full history servers and improve performance for users.

**Comment by miguelportilla** [comment]
It is an interesting idea. What are your thoughts on the `quick retrieval` part?

One possibility is to create a message type that allows direct transfers of ledgers (possibly compressed) between cluster members. Ledgers transferred to members could also satisfy history or shards being acquired.

Another idea is to extend the existing shard download client to serve and additionally provide ledger archives.

Do cluster members currently announce their combined cluster history? If not that would need to be implemented.

**Comment by miguelportilla** [comment]
If we allowed nodes to store specific parts of history and cluster members are regularly updated on the history other members have, each member could be configured to accept or deny requests for `quick transfers` from other members. That would allow great flexibility in setups. For instance, you could have any number of full history and front-facing members in a cluster or distribute history in any weight amongst the members. That would likely provide better performance and reliability. With enough history overlap across members, single point failures could be eliminated. 

This design would require that each cluster member is:
  Configurable storage of specific history
  Updated about the history every other member has.
  Configurable to accept `quick transfers` requests from other members.

**Comment by nbougalis** [comment]
>It is an interesting idea. What are your thoughts on the quick retrieval part?
>
>One possibility is to create a message type that allows direct transfers of ledgers (possibly compressed) between cluster members. Ledgers transferred to members could also satisfy history or shards being acquired.

I was thinking a new request with a corresponding response available only to immediately connected cluster peers and afforded priority service with low command "cost".

>Another idea is to extend the existing shard download client to serve and additionally provide ledger archives.
>
>Do cluster members currently know what history other members have? If not that would need to be implemented.

No. We could add this into the `TMCluster` message, I guess. But, ultimately, maybe that isn't needed either. Simply send the message to all your cluster peers, and anyone that can help responds. Something like:

    auto rq = std::make_shared<Message>(cluster, protocol::mtCLUSTER_HISTORY_REQUEST);
    /* fill in the request */
    send_if (rq, peer_in_cluster ()));

Knowing who had what would allow us to reduce the load, I guess and, longer term, allow a cluster to coordinate so that it can be configured to hold full history in aggregate which is something we discussed last week as a "would be neat" thing. Which gets to the "ambitious design" message above.

**Comment by mDuo13** [comment]
I think it could also be very useful if clustered servers could avoid storing the same shards as one another, but could relay data from each other when doing most API queries. That way, a cluster of servers could act as one full-history server without one individual piece of hardware needing everything. Even if they don't reach full history, it could still ensure that a cluster uses sharding to efficiently provide as much history as it can.

**Comment by intelliot** [comment]
@WietseWind @jscottbranson thoughts on this?

**Comment by WietseWind** [comment]
@intelliot If it's just to put non FHs in front and then offload to FHs I don't really see the point: FH queries would still be limited to the amount of FHs behind the non FHs, resulting in the same bottlenecks? And offloading to FH happens fairly often, as non FH doesn't know if what it doesn't know exists elsewhere, so it'd have to relay lots of things it can't find locally.

You'd still end up requiring the equal amount of FH as right now, there's just someone else in front?

**Comment by intelliot** [comment]
Thanks!
