### ISSUE TITLE
Add ledger info to all webservice subscriptions

### ISSUE THREAD

**Issue by Aquatrader** [XRPLF/rippled#2819]
At the moment it is not possible to detect a broken subscription in an easy way, so adding simple last ledger info as a heartbeat to the available subscriptions would make life a lot easier.

**Comment by levinem** [comment]
It looks like the last valid ledger info is accessible through the function [context.ledgerMaster.getValidLedgerIndex () ](https://github.com/ripple/rippled/blob/e83d367f49cceb4b5f28830fb1965a5978744450/src/ripple/app/ledger/impl/LedgerMaster.cpp) and is already being used in the [RPCHandler](https://github.com/ripple/rippled/blob/5214b3c1b09749420ed0682a2e49fbbd759741e5/src/ripple/rpc/impl/RPCHandler.cpp#L179).

**Comment by levinem** [comment]
Also, the [isValidatedOld function](https://github.com/ripple/rippled/blob/efa926676c1b63fddb88f7686fb3e6edc26b169c/src/ripple/rpc/impl/RPCHelpers.cpp#L166) could perhaps be used to provide a bool indicator of the subscription sending stale ledger info.

**Comment by levinem** [comment]
@Aquatrader, are you listening to the server through ripple-lib and are hoping to have this information exposed via the api?  This may be more of an api feature if the info is already exposed through the rippled server.

**Comment by MarkusTeufelberger** [comment]
How would you detect a broken subscription by making calls to a different API? That would only detect that the server is still running, not that it is still handling your subscription...

**Comment by levinem** [comment]
@MarkusTeufelberger , I was thinking that @Aquatrader could use the [ledger stream message's](https://xrpl.org/subscribe.html) ledger_hash and ledger_time fields to perhaps get a sense of how old the ledger info is on the subscriber stream.

However, I think there could be two different use cases/implementation possibilities:

1. The change could be implemented on the rippled/server layer and be configured through the cfg file as to whether the behavior should be automated or not.  Some of the referenced functions above could be used to automatically drop the subscriber, log the change, and subscribe to a more up to date stream.

2. The behavior could be a bool setting on a subscriber stream to provide metadata about the health of the subscription.  In this case the behavior of updating subscriptions would be left to the specific implementation needs of the consumer software.

**Comment by Aquatrader** [comment]
I dont know if i understand all the questions, but this is my issue:
I subscribe to the ripple stream with the accounts command. In this case, i get a message whenever a transaction is made with the specified account. The problem is, i do not know when a transaction will happen. So if I do not recieve a message, this could be: a. no transactions OR b. there are transactions but the subscription is broken. I do not know a proper way to determine if the subscription is broken, so i suggest this subscription sends some basic ledger info too, then i am sure if I receive nothing after a while, the subscription is broken. If there is a better way to determine a broken subscription, please let me know :)

**Comment by intelliot** [comment]
You can get ledger info using [the `ledger` stream](https://xrpl.org/subscribe.html#ledger-stream).

**Comment by Aquatrader** [comment]
I know i can that the ledger info that way, but the issue is if I subscribe to only the account stream, my python setup cannot determine the difference between "no transactions on your account for x hours" or "the subscription has been lost for x hours" in both situations, so stream info would be handy...

**Comment by ximinez** [comment]
You can specify multiple streams in your `subscribe` command. (Or send multiple `subscribe`s on the same socket.) You can subscribe to the account and the ledger.
