### ISSUE TITLE
Add info about Websocket/RPC port(s) to the /crawl endpoint

### ISSUE THREAD

**Issue by MarkusTeufelberger** [XRPLF/rippled#2837]
As suggested in #2823, this could help in finding additional servers to use as a fallback for transaction submission for example. See also https://www.xrpchat.com/topic/30058-list-of-rippled-servers-with-wss-andor-json-rpc-servives/ for a need for this.

Currently there is no standard way to advertise these services, so the only other way to get this information would be to port-scan all reachable nodes. This is not a very friendly thing to do, having them advertise this in their /crawl endpoint is probably a better way forward.

**Comment by nbougalis** [comment]
This would be nice to have. Anyone wanting to claim this issue, either assign yourself or raise your hand and I'll assign it to you :)

**Comment by intelliot** [comment]
will be fixed by #4427 - expected in 1.12
