### ISSUE TITLE
account_tx wss only orders transactions w/ oldest first

### ISSUE THREAD

**Issue by carterbrett** [XRPLF/rippled#2918]
***This issue seems to apply to rippled v1.2.2, but not 1.2.4.***
I'm leaving this here for posterity and because I didn't see mention of this bug in the release notes for patches 1.2.3 or 1.2.4. 

### Issue
WebSocket `account_tx` commands only index transactions with the oldest transaction first in `rippled 1.2.2`. This is true when the`"forward": false` parameter is omitted or explicitly declared. 

### Example
```bash
> wscat -c wss://s.altnet.rippletest.net:51233 # currently running rippled 1.2.2

# this:
> {"id":2,"command":"account_tx","account":"r9cZA1mLK5R5Am25ArfXFmqgNwjZgnfk59","ledger_index_min":-1,"ledger_index_max":-1,"binary":false,"count":false,"limit":2,"forward":true}

# returns the same transactions, in the same order, as this:
> {"id":2,"command":"account_tx","account":"r9cZA1mLK5R5Am25ArfXFmqgNwjZgnfk59","ledger_index_min":-1,"ledger_index_max":-1,"binary":false,"count":false,"limit":2,"forward":false}

# and this:
> {"id":2,"command":"account_tx","account":"r9cZA1mLK5R5Am25ArfXFmqgNwjZgnfk59","ledger_index_min":-1,"ledger_index_max":-1,"binary":false,"count":false,"limit":2}
```

### Notes
- This can be easily observed by toggling the `forward` param between true and false with the [Ripple WebSocket Dev Tool](https://developers.ripple.com/websocket-api-tool.html#account_tx).
- The equivalent HTTP requests do not seem to exhibit the same behavior. 

#### P.S. 
I'm new here. :wave: If my issue/explanation can be improved in any way, your feedback is welcome!

### EDIT
The Ripple WebSocket Tool seems to be connected to wss://s2.ripple.com:443 which is running v1.2.4, so I'm not sure why its exhibiting this same issue. When I connect to s2 using the same `wscat` commands included above, everything seems to work fine.

**Comment by mDuo13** [comment]
The `account_tx` command has a legacy version that's triggered if you provide certain fields including `count`. The WebSocket Tool hasn't been updated in a while (it's on my to-do list) and the default example includes `count`, sending it to the legacy version of the command. (See the note following the parameter table [in the docs](https://developers.ripple.com/account_tx.html) for the full list.)

So, I'm not certain this is the case, but it seems likely that it's not the rippled version or WebSockets vs. JSON-RPC that's causing the difference, but the presence or absence of the `count` parameter that's causing it.

Thanks for dropping in and reporting this, and let me know if you can confirm my hypothesis about the reason why this is happening.

**Comment by carterbrett** [comment]
@mDuo13 Sounds good. Just a heads up though, excluding `count` and for that matter, all of the parameters outlined in the note you mentioned, doesn't seem to change the behavior. At least that seems to be the case in a quick test using the WebSocket tool.

**Comment by intelliot** [comment]
Closing because this is unlikely to apply to the current version. If the issue persists, please open a new one (and link back to this one).
