### ISSUE TITLE
Remove default constructor for PublicKey

### ISSUE THREAD

**Issue by thejohnfreeman** [XRPLF/rippled#2942]
The root of the problem is `PublicKey` is default constructable, and I don't think it should be. Anything using a default constructed public key should be changed to use a `boost::optional<PublicKey>` and any constructed `PublicKey` should be valid. This removes the `empty_` junk from public key and makes explicit the assumptions about how the key is used at the site.

_Originally posted by @seelabs in https://github.com/ripple/rippled/pull/2774_

https://github.com/XRPLF/rippled/pull/2774#discussion_r235359664

**Comment by scottschurr** [comment]
If we do this we should also remove the default constructor for `SecretKey`.  And, yeah, I think this is a really good idea.
