### ISSUE TITLE
minLedgerVersion transaction parameter (like Bitcoin "LockTime")

### ISSUE THREAD

**Issue by tim-dorcey** [XRPLF/rippled#2945]
It would be useful if a transaction could specify the earliest ledger version after which the transaction may appear. This could be used to recover funds if a private key is lost.

When transaction N is created, the account would also sign and save transaction N+1 that transfers the remaining balance to a recovery account, but only in some future ledger, say 30 days away.

The private key for the recovery account could be kept in cold storage, since it is never needed unless a recovery transaction is executed. Furthermore, it is of no value unless the parent account submits no new transactions for 30 days, since each new transaction N+1 automatically cancels the previous recovery transaction by consuming its sequence number.

**Comment by MarkusTeufelberger** [comment]
How would that be different from the existing Escrow feature?

**Comment by tim-dorcey** [comment]
The existing Escrow cannot be canceled before the time lock expires.  This is automatically canceled by any subsequent transaction.

**Comment by JoelKatz** [comment]
Great example use case! I like this idea a lot.

**Comment by smlu** [comment]
Just for consideration, it'd be interesting to have on chain delayed/deferred transactions in combination with authorization.
In such system, you could define a transaction wait time as one of the multi-signing weight. Such configuration could then recover an account if some of minimum threshold keys are lost, depending on the weight of wait condition.
This could also be useful in case of "single key - multi sig" configuration where you'd set one key and a wait time to define the min authorization threshold. User could then monitor his/her account and if deferred transaction is published to the network which was not approved by the user, he/she can cancel it thus preventing losing funds. User also get an information that his/her keys are compromised and should change them.

For reference see the sophisticated [permissions system](https://medium.com/@eoscafeblock/how-permissions-work-in-eos-82e55eb1d896) in [EOS](https://github.com/EOSIO/eos) blockchain.

**Comment by mDuo13** [comment]
This has also [been suggested](https://github.com/ripple/rippled/issues/2456#issuecomment-375849740) under the name `FirstLedgerSequence`.

**Comment by intelliot** [comment]
This is a nice idea, but I haven't recently heard from anyone that this is something they would actually use. Setting `Low Priority` as this issue hasn't seen activity in over a year. @tim-dorcey if this is a feature you'd like to see, please confirm that you would use it (and if possible, point to others who would use it too!)

**Comment by timethernom** [comment]
Thanks for inquiring.  As it happened, I had some other special requirements so ended up creating a private cluster with several new behaviors.  Given that freedom, I found a more direct solution by adding a few fields to the account object.   So, no, I wouldn't need to see it on the main ledger.  My main requirement was to allow only 1 copy of the private key, in a secure enclave, with no export or backup.  So, I needed a mechanism to transfer control to a new key if that became inaccessible.

**Comment by intelliot** [comment]
Glad to hear that you found a more direct solution. Your private cluster could be a good candidate for a [sidechain](https://xrpl.org/federated-sidechains.html). If anyone else is interested in this feature (or a related one), please start a new [discussion in XRPL-Standards](https://github.com/XRPLF/XRPL-Standards/discussions).
