### ISSUE TITLE
SSLHTTPDownloader Improvements

### ISSUE THREAD

**Issue by mellery451** [XRPLF/rippled#3033]
This class is used to fetch shard archives from other nodes. We should add

1. sensible timeouts (beast helps with this)
2. the ability to resume a partial download that was interrupted by failure/shutdown.

**Comment by carlhua** [comment]
@miguelportilla do we want to work this?

**Comment by scottschurr** [comment]
I'm not seeing evidence of an `SSLHTTPDownloader` class in develop as of 1.7.0.  I think it was replaced by the `HTTPDownloader.h` class.

I'm guessing these issues can be marked as closed as a result of the of going Shards work.  Do you agree @miguelportilla and/or @undertome?

**Comment by undertome** [comment]
> I'm not seeing evidence of an `SSLHTTPDownloader` class in develop as of 1.7.0. I think it was replaced by the `HTTPDownloader.h` class.
> 
> I'm guessing these issues can be marked as closed as a result of the of going Shards work. Do you agree @miguelportilla and/or @undertome?

Correct

**Comment by intelliot** [comment]
I believe Shards is deprecated and will likely be removed
