### ISSUE TITLE
Fix serialization of FeeSettings object

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/rippled#3165]
The [`FeeSettings` ledger object type](https://xrpl.org/feesettings.html) has some weird behavior when it's serialized to JSON (In `ledger_entry` or `ledger_data` responses, or in the metadata of [a SetFee transaction](https://xrpl.org/websocket-api-tool.html?server=wss%3A%2F%2Fs2.ripple.com%2F&req=%7B%22id%22%3A%22setfee_nonunique_hash_1%22%2C%22command%22%3A%22transaction_entry%22%2C%22tx_hash%22%3A%221C15FEA3E1D50F96B6598607FC773FF1F6E0125F30160144BE0C5CBC52F5151B%22%2C%22ledger_index%22%3A3715073%7D)):

- `BaseFee` is serialized as hex despite being an XRP amount (UInt64)
- `ReferenceFeeUnits`, `ReserveBase`, and `ReserveIncrement` are serialized as JSON numbers, not strings as XRP usually is. (This is because they are actually UInt32 types instead of the usual UInt64.)

It would be nice to change the binary format of the `FeeSettings` object to make it use the proper data type for XRP amounts in all its XRP fields, but that's harder to fix because it would require an amendment.

**Comment by mDuo13** [comment]
Note that with the given data structures the [maximum theoretical values for fee settings](https://xrpl.org/fee-voting.html#maximum-fee-values) are, shall we say, strange. The reserve settings, which would make sense to be much larger than the costs of sending a transaction, are more limited.

**Comment by intelliot** [comment]
Related: https://github.com/XRPLF/rippled/issues/4425

**Comment by intelliot** [comment]
@mDuo13 can you confirm this issue has been fixed as of what's in `develop` now?

**Comment by intelliot** [comment]
**mDuo13** noted that this is probably fine. If anyone sees any potential issues, please comment here or create a new issue.
