### ISSUE TITLE
Historic data not accessible if current ledger not available

### ISSUE THREAD

**Issue by MarkusTeufelberger** [XRPLF/rippled#322]
If rippled is not synced to the network it is not possible to access already existing and verified data.

e.g.:
server_info: {"build_version":"0.23.0","complete_ledgers":"5500000-5930000" ...etc}

If the network cable is pulled the server stays in that state, it will however only reply with error 13 "Network not available" if you query for data in ledger 5900000 for example, even though this data is already immutable and fully available to rippled.

**Comment by intelliot** [comment]
This is a reasonable idea but not a priority at this time. If anyone is interested in this, please create a new issue - including a spec / description of exactly what you'd like (and why).
