### ISSUE TITLE
Enhance getInfoRippled.sh to streamline Github issue creation

### ISSUE THREAD

**Issue by carlhua** [XRPLF/rippled#3248]
As part of the Github issues template that will be used during issue creation, the config file is recommended to be uploaded as part of the issue creation process. The config files contain private information that should be removed/sanitized. This issue is to enhance the existing getInfoRippled.sh script to:

1. @nbougalis tagged the ips and ips_fixed stanzas for removal. We need to either remove those, or white-list stanzas for the script.
2. Improve the output of the script after execution to be more user-friendly.
3. Add it to packages
4. Consider adding hardware spec per @MarkusTeufelberger

**Comment by thejohnfreeman** [comment]
Might want to implement it in Python to be cross-platform. Yes, it will assume people have Python installed, but it's easier for Linux and Mac users to install and run Python (and most of them probably already have it) than it is for Windows users to install and run Bash.

**Comment by seelabs** [comment]
@mellery451 The current output is something like:
```
/tmp/ripple_info.MZgr
database_path: /home/swd/.rippled/db

Use the following command on your local machine to download from your rippled instance: scp <remote_rippled_username>@<remote_host>:/tmp/ripple_info.MZgr/info-package.tar.gz <path/to/local_machine/directory>
```

That starts with a piece of data with no context: `/tmp/ripple_info.MZgr`. It also assumes rippled is running on a remote server and uses `scp` to copy it. Anyone running linux is going to know `cp`. `scp` is a little more obscure.

That output is OK, but I'd like to do better if we recommend that run this script to report a bug. @mDuo13 is good at things like this, we might want his input.

**Comment by mellery451** [comment]
the current script creates several small txt files and then zips them into an archive. How about we instead generate a single .md file and provide basic instructions for uploading as a gist? I'm not sure the archive is useful if we don't provide a standard place to upload them...

**Comment by mellery451** [comment]
Here's a stab at what I'm proposing. The script will generate a single markdown file locally - example:  https://gist.github.com/mellery451/a7b17830a70d025fc09d8a84e586c3a2

and then the only output to stdout would be something like:

```
####################################################
  rippled info has been gathered. Please copy the
  contents of /tmp/ripple_info.0rzK7/rippled_info.md
  to a github gist at https://gist.github.com/

  PLEASE REVIEW THIS FILE FOR ANY SENSITIVE DATA
  BEFORE POSTING! We have tried our best to omit
  any sensitive information from this file, but you 
  should verify before posting.
####################################################
```

**Comment by thejohnfreeman** [comment]
I've asked around, and it seems like no one is using this script any more. If anyone reading this has used it in the past year, please leave a comment. Until then, I suggest we close this issue and consider removing the script. If we want to keep it, we need to put some serious effort into (a) identifying the problem it solves, (b) fixing it up, and (c) promoting it. @intelliot

**Comment by intelliot** [comment]
If we're not aware of anyone using it, go ahead and remove the script.
