### ISSUE TITLE
Allowing out of order transactions

### ISSUE THREAD

**Issue by timethernom** [XRPLF/rippled#3301]
I am working on a new transaction flag which indicates that a transaction can be added to the ledger even if it creates a gap in the sequence number space.  An optional STBlob bitfield is added to the AccountRoot ledger entry to track any leading transactions.

This is for a private ledger supporting an off-network payment system.  However, I expect it might also be useful for the public ledger.  Whenever transactions arrive in a different order than they were created, and there is no particular reason they must execute in order, it should be more efficient and secure to commit them to the ledger as soon as possible.

If there is any interest, I can share this code.  I guess I just create a Pull Request?

**Comment by mDuo13** [comment]
You're not the only one who wants a feature like this. At Ripple, we've been (kind of stealthily) working on a similar, more robust functionality called Tickets to handle this and similar use cases. And, finally, we've published our spec for how Tickets should work: https://github.com/xrp-community/standards-drafts/issues/9

**Comment by intelliot** [comment]
[XLS-13](https://github.com/XRPLF/XRPL-Standards/discussions/18) Tickets has been implemented and activated on Mainnet. Details: https://xrpl.org/known-amendments.html#ticketbatch
