### ISSUE TITLE
Drop non-strict account parsing

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/rippled#3330]
## Summary
Relating to #3329, I think non-strict account parsing should be removed.

## Motivation
Accepting secret values in the API just encourages poor operational security and makes the API definition more ambiguous.

## Solution
**This is a breaking change requiring an API version bump.**

All API fields that accept account addresses in base58 should _not_ accept passphrases, secret keys, public keys, RFC-1751 phrases, or other variant forms. (X-Address support would be fine though.)

This applies to all fields named `account`, as well as some other cases like `peer`, `taker`, `issuer`, members of `hotwallets`, etc. I haven't extensively tested which of these fields accept secrets/etc. but the answer should be "none of them."

After doing this, the `strict` parameter can be removed from all API methods that have it.

**Comment by intelliot** [comment]
@drlongle could you add a comment here re: your thoughts / questions?

**Comment by drlongle** [comment]
I would like to know why public keys should not be accepted. Is it because we want to simplify the API and argument parsing (i.e. guessing whether a provided argument is an address or a public key).

@mDuo13 Can you clarify? Thanks.

**Comment by intelliot** [comment]
**drlongle:** What is the rationale for not accepting public key to look up account? Do we have a consensus about that?

**mDuo13:** There is no security issue with using public keys, but for simplicity and consistency, it makes the most sense to accept only one data type per field. I still think the ticket is relevant and worth doing

**Comment by intelliot** [comment]
Resolved by https://github.com/XRPLF/rippled/pull/4404, expected to be released in v1.11, target release date ~June 2023.
