### ISSUE TITLE
Refactor Stoppable interface

### ISSUE THREAD

**Issue by carlhua** [XRPLF/rippled#3442]
## Summary

Currently, the Stoppable interface requires inheritance and constructor parameters, which makes messy declarations of abstract base classes that implement Stoppable. We need to change the way the Stoppable hierarchy is formed to eliminate the need for constructor arguments.

Exported from RIPD-118

**Comment by scottschurr** [comment]
@thejohnfreeman, since https://github.com/ripple/rippled/commit/78245a072c0e58b30ff482e41c375494505d9b32 was merged in 1.7.0-b10, can this issue be closed?

**Comment by thejohnfreeman** [comment]
That was a minor cleanup commit. The real refactor is #3741, which is presently awaiting resolution of merge conflicts. I don't mind closing this issue now, or waiting until that PR is merged.

**Comment by scottschurr** [comment]
Seems good to wait until https://github.com/ripple/rippled/pull/3741 is merged, just in case something unexpected happens.

**Comment by scottschurr** [comment]
@thejohnfreeman, I no longer see #3741 as an open pull request.  It looks like it was merged in 1.8.0-b3.  Are we good to close this issue?

**Comment by thejohnfreeman** [comment]
Indeed!
