### ISSUE TITLE
Refactor TrustSet transactor

### ISSUE THREAD

**Issue by carlhua** [XRPLF/rippled#3466]
## Summary

Refactor the TrustSet transactor:
1) If the line doesn't exist, create it in the default state (unless the account can't pay the reserve, in which case tec).
2) Set the line as requested.
3) See whether the line should be charged to the account that sent this transaction.
4) If no and we created the line, tec.
5) If no and we didn't create the line, make sure it's not charged, and tes.
6) If yes, and it's not charged, charge the account for the line. tes.

Also, please add unit test to make sure TrustSet fails if insufficient reserve to add a trustline is detected.

Exported from RIPD-14 and RIPD-1016

**Comment by scottschurr** [comment]
The description, the way I'm reading it, is not just a refactor.  It would require an amendment.  Changing the order in which transactors handle operations changes which result is returned for various error circumstances.  Such changes could lead to problems with the validators picking a preferred ledger. 

I don't think the refactor described here justifies adding an amendment.

Regarding the note at the end, there is currently a unit test that verifies the reserve behavior for trust line creation.  So I think that last request has been fulfilled.

**Comment by intelliot** [comment]
@scottschurr , thank you! Given that, let's close this issue for now. If someone still wants it (or something similar), please feel free to open a new issue (and if you like, link back to this one).
