### ISSUE TITLE
Inter-round generic consensus updates

### ISSUE THREAD

**Issue by carlhua** [XRPLF/rippled#3476]
RCLConsensus, LedgerMaster and NetworkOps still have some rules for managing inter-round changes in the closed and fully validated ledgers. I've tried to repeat them in csf::Peer but it would be better to have them explicitly in the generic consensus code. Particularly, switching to the most supported ledger when starting the next round of consensus. This doesn't favor our current ledger, and has checks to avoid switching to the parent ledger, incompatible ledgers.

Exported from RIPD-1520

**Comment by intelliot** [comment]
@thejohnfreeman any thoughts on this? Can we just close this issue?

**Comment by thejohnfreeman** [comment]
I don't know what it's talking about. I'm fine closing it.
