### ISSUE TITLE
add a beast::Insight::Counter for number of fetch pack requests

### ISSUE THREAD

**Issue by carlhua** [XRPLF/rippled#3481]
Per the title - add a beast::Insight::Counter for number of fetch pack requests in StatsD.

Exported from RIPD-232

**Comment by intelliot** [comment]
note: originally requested by @mtrippled in April 2014

If this is no longer relevant or helpful, go ahead and close this issue.

**Comment by mtrippled** [comment]
I don't see this as relevant or helpful. I don't even know if beast insight is even used anywhere.
