### ISSUE TITLE
Allow Validator operators to designate proxy for amendment votes

### ISSUE THREAD

**Issue by carlhua** [XRPLF/rippled#3482]
A validator operator would add a validation public key to an [amendment_proxy] config field to mimic the amendment votes of the proxy validator.

Exported from RIPD-1228

**Comment by MarkusTeufelberger** [comment]
If that proxy validator is down, how would the votes look like?

**Comment by intelliot** [comment]
Sounds cool but we haven't seen any actual demand for this; there is also a strong argument to be made that every validator should be actively engaged and make its own amendment voting decision - this is best for the governance and decentralization of protocol change decisions. Closing.
