### ISSUE TITLE
Change mulDiv() return from pair<bool, std::uint64_t> to optional<std::uint64_t>

### ISSUE THREAD

**Issue by carlhua** [XRPLF/rippled#3495]
The current mulDiv interface is error prone, and it’s easy to ignore when overflow occurs. The suggestion is that we change this interface to use optional in place of pair<boool, value>.

This suggestion should decrease the likelihood of people ignoring overflow. It’s also very convenient to use optional::value_or() as a way to explicitly recover from overflow.

Exported from RIPD-1791

**Comment by intelliot** [comment]
May be fixed by #4243
