### ISSUE TITLE
Users would like rippled to return configurable CORS header

### ISSUE THREAD

**Issue by carlhua** [XRPLF/rippled#3513]
rippled's JSON-RPC API would be very convenient to use from a web app, because it can leverage many of the existing AJAX paradigms and tools. (Existing web apps can use the WebSocket interface, but there's far less tooling around WebSocket.) However, at present, there is no way for a web page in a modern browser to access JSON-RPC without going through a reverse proxy, because same origin policies prevent a webpage from connecting to something that's not on the same domain and port.

If rippled's JSON-RPC interface supported the OPTIONS method and the [Access-Control-Allow-Origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Access-Control-Allow-Origin) header, it would be possible for scripts to access a rippled running on a different domain or subdomain. Minimal functionality would be a config option in the RPC port stanza to permit Access-Control-Allow-Origin: *, but better yet would be the functionality to specify one or even more origins to allow.

Multiple origins would entail reading the `Origin` header of the request and setting the value of the Access-Control-Allow-Origin header in the response accordingly if it's one of the configured domains.

Exported from RIPD-1091

**Comment by intelliot** [comment]
Closing because:
1. This issue has been inactive for years.
2. WebSocket actually works quite well.
3. This is a feature that could be implemented in Clio, and there is not necessarily a need to also do it in `rippled`, as Clio is the future of the XRPL API server.
    - https://github.com/XRPLF/clio/issues/914

If anyone is interested in this feature in `rippled` specifically, feel free to comment here or [open a new issue](https://github.com/XRPLF/rippled/issues/new/choose).

**Comment by mvadari** [comment]
This is still a big problem for a lot of browser applications. It's a lot easier to set one up with HTTP instead of Websocket.

**Comment by intelliot** [comment]
Thanks for commenting. Can you give an example? It seems like Websocket has fairly wide usage these days.

**Comment by intelliot** [comment]
Would it be sufficient for this feature to be added in Clio? 

The plan is for Clio to be the API server for the XRP Ledger, with `rippled` reducing its scope to implementing the p2p protocol, transaction processing, consensus.

- https://github.com/XRPLF/clio/issues/914

**Comment by mvadari** [comment]
Clio would probably be sufficient, though `rippled` would be ideal, especially since a fair amount of public infra is still `rippled`.
