### ISSUE TITLE
Reduce complexity of STAmount class

### ISSUE THREAD

**Issue by carlhua** [XRPLF/rippled#3530]
The class STAmount is being split into two distinct objects: one dealing with serialization and another dealing with the "amount" business logic.

STAmount contains many convenience wrapper functions which complicate the use of the class and migration to the new code. Reduce the public interface by eliminating wrapper, unused of single-use functions.

Exported from RIPD-867

**Comment by intelliot** [comment]
- https://github.com/XRPLF/rippled/pull/1058
