### ISSUE TITLE
Add protocol close message

### ISSUE THREAD

**Issue by carlhua** [XRPLF/rippled#3531]
The ripple peer protocol needs a "close" message. This indicates to the receiving peer that no more messages will be sent on the connection. The behavior of a peer upon receiving the close message, should be to close the connection.

This allows the connection to be closed gracefully when session is over.

Exported from RIPD-539

**Comment by intelliot** [comment]
- https://github.com/XRPLF/rippled/pull/3839 (reverted)
- https://github.com/XRPLF/rippled/pull/4861
