### ISSUE TITLE
Revise or deprecate ledger_header command

### ISSUE THREAD

**Issue by carlhua** [XRPLF/rippled#3539]
The ledger_header admin command provides the ledger header information in JSON and binary formats.

The ledger public command, meanwhile, provides the ledger header information in JSON format only.

Rather than having two commands that overlap so closely in functionality, we should consolidate them. Since it doesn't make sense to retrieve the same information in two different formats at once, the most effective solution would be to:

1. [x] Add a "binary" option to the ledger command (default:false). If true, then return the binary form of the ledger header instead of the JSON form. If false or omitted, return the same information as currently provided.
2. [ ] Deprecate the now completely redundant ledger_header admin command.

Exported from RIPD-889

**Comment by mDuo13** [comment]
I thought this was done already... Now I'm unsure.

**Comment by cjcobb23** [comment]
I confirmed that 1 is already done.

**Comment by mDuo13** [comment]
It's [not documented](https://xrpl.org/ledger-methods.html) either, so in that sense it's kind of like it's deprecated?

**Comment by mDuo13** [comment]
I guess the only remaining step would be to remove `ledger_header` entirely from APIv2?

**Comment by mDuo13** [comment]
The `ledger_header` API method is not currently documented and is not implemented in Clio but is currently still available in rippled under API v1. IMO we should remove it (maybe from both, definitely from API v2)

**Comment by Bronek** [comment]
I'm on it
