### ISSUE TITLE
rippled does not produce core files when started with systemd Version: 1.7

### ISSUE THREAD

**Issue by mtrippled** [XRPLF/rippled#3630]
Found on Ubuntu 18.04LTS, rippled does not produce core files when started with systemctl as installed by the deb package.

**Comment by mtrippled** [comment]
The issue here is that systemd has its own configuration for generating core files, documented for each of the major Linux distributions. Since systemd is now the parent of rippled that respawns, systemd now must be configured to generate cores. Pior versions of rippled had rippled itself spawn and re-spawn a child process. I had custom core file configuration in /etc/sysctl.conf that broke with the new change. I'm not sure if this needs to be documented for server operators. @mduo ?

**Comment by MarkusTeufelberger** [comment]
What exactly do you mean by "core file"? core dumps in case the process crashes?

**Comment by mtrippled** [comment]
> What exactly do you mean by "core file"? core dumps in case the process crashes?

Yes

**Comment by nbougalis** [comment]
We should definitely document this and, if possible, link to the details for the major Linux distributions.

**Comment by intelliot** [comment]
1. Confirm that we have rippled generating core files under systemd now
2. Check to see if the default `.deb` / `.rpm` packages do so (with no additional changes by server operators)

If no action is needed to get a core file when rippled crashes, then we can close this issue as "not-planned".

If server admins have to configure something non-default to save a core file in the event that their `rippled` crashes, that should be documented (probably in the install instructions).

**Comment by legleux** [comment]
It seems the only config needed for `rippled` to generate core dumps when run as a `systemd` service is adding `LimitCORE=infinity` to the service file.
Core dumps appear in `/var/lib/apport/coredumps` then can be loaded with gdb (provided the `rippled-dbgsym` package was installed) like:
`gdb <path_to_rippled> <path_to_core_file>` 

We could add this as the default to the service file but probaly just document it as the as `rippled` core files can be very large.

I'm not sure what to do about this on CentOS, the same setup doesn't seem to work.

**Comment by intelliot** [comment]
@legleux can you open a PR for xrpl-dev-portal to add that information somewhere in the docs? maybe https://xrpl.org/update-rippled-manually-on-ubuntu.html ?

**Comment by legleux** [comment]
Merged with: https://github.com/XRPLF/xrpl-dev-portal/pull/2264
Documented at [Install on Ubuntu](https://xrpl.org/install-rippled-on-ubuntu.html)
