### ISSUE TITLE
Always return `ledger_index` as int, not str, in JSON

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/rippled#3652]
## Summary
This is the "breaking change" follow up to #3533 . The API (v2 or higher) should always return `ledger_index` fields formatted as the same data type, probably numbers/integers, when serialized to JSON.

## Motivation
See https://github.com/ripple/rippled/issues/3533#issuecomment-675671496 for some examples of places where `ledger_index` is returned as an string-integer rather than a proper integer.

**Comment by Bronek** [comment]
Note, [this change](https://github.com/XRPLF/rippled/pull/4820) is planned for API version 3 (not 2)
