### ISSUE TITLE
Websocket code refactoring to improve performance

### ISSUE THREAD

**Issue by carlhua** [XRPLF/rippled#3655]
Refactor the Websocket code - Do away with WSMsg and the buffer copying, rework the entire RPC and subscription code paths to yield data on demand from the coroutine. Send WebSocket messages in individual frames to support streaming.

For WebSocket subscriptions, share the data buffers instead of making a copy for each connection. In addition, when permessage-deflate is active on a stream, the calculation for determining the message size became more complex, and broke the read_message_max option for compressed streams.

Exported from RIPD-1123

**Comment by intelliot** [comment]
@mtrippled does it seem likely that this would improve performance for servers that are handling a large number of websocket connections/requests?

**Comment by mtrippled** [comment]
I really doubt this would be worth the time. Clio is designed for handling
lots of rpc traffic, and it probably is already optimized.

I think this can be safely closed.
