### ISSUE TITLE
libpq.so.5 missing in reporting mode (Version: 1.7.2)

### ISSUE THREAD

**Issue by N3TC4T** [XRPLF/rippled#3881]
## Issue Description
When rippled compiled with `-Dreporting=ON` and PostgreSQL is not installed on the server you will get below error message when running rippled:

`error while loading shared libraries: libpq.so.5: cannot open shared object file: No such file or directory`

the solution would be to install required dependency by:

`sudo apt-get install libpq-dev`

I guess we can add this somewhere in the documentation. 

## Steps to Reproduce
Compile rippled with `-Dreporting=ON` in `Ubuntu 20` without PostgreSQL installed and run executable `rippled`

```
cmake -DCMAKE_BUILD_TYPE=Release -Dreporting=ON -DCMAKE_INSTALL_PREFIX=/opt/ripple ..
cmake --build . --target install -- -j8
```

## Expected Result
Should run rippled without problem

## Environment
Ubuntu 20.04.2 LTS with Boost 1.70

**Comment by cjcobb23** [comment]
We actually try to build libpq ourselves if it's not installed: https://github.com/ripple/rippled/blob/7bd5d51e4e4e76a5547051d30b330739618eddb0/Builds/CMake/deps/Postgres.cmake#L25

Installing it of course fixes the problem. This passes in CI without installing libpq-dev, though that's running on Ubuntu 18.04. What compiler are you using? Also, can you check if there are any other errors in the build?

Also, can you go into the `.nih` folder (it's hidden at the root level, once you actually try to build), and execute `find . -name "libpq.*"`, and post the output here?

**Comment by N3TC4T** [comment]
There is no error, I can see that the cmake cannot find any postgres library in the system.

```
Could NOT find PostgreSQL (missing: PostgreSQL_LIBRARY PostgreSQL_INCLUDE_DIR PostgreSQL_TYPE_INCLUDE_DIR) 
find_package did not find postgres
No system installed Postgres found. Will build
```

also looks like in the build process the lib is already compiled

```
./unix_makefiles/GNU_9.3.0/Release/src/postgres_src/doc/src/sgml/libpq.sgml
./unix_makefiles/GNU_9.3.0/Release/src/postgres_src/src/include/libpq/libpq.h
./unix_makefiles/GNU_9.3.0/Release/src/postgres_src/src/interfaces/libpq/libpq.so
./unix_makefiles/GNU_9.3.0/Release/src/postgres_src/src/interfaces/libpq/libpq.so.5
./unix_makefiles/GNU_9.3.0/Release/src/postgres_src/src/interfaces/libpq/libpq.a
./unix_makefiles/GNU_9.3.0/Release/src/postgres_src/src/interfaces/libpq/libpq.so.5.15
./unix_makefiles/GNU_9.3.0/Release/src/postgres_src/src/interfaces/libpq/libpq.pc
```


I guess it can be something in `Ubuntu 20` ?

**Comment by cjcobb23** [comment]
Hmm. I spun up an Ubuntu 20.04.2 TLS VM on EC2 and was not able to reproduce this. I built reporting mode, and was able to run without errors. Can you try to build without installing? Meaning the executable will just be in the build folder.

**Comment by N3TC4T** [comment]
Yeah, it works without `--target install` :+1:

**Comment by cjcobb23** [comment]
Ok, we will work this and see what's going wrong when using `--target install`. Thanks for reporting.

**Comment by mickarena** [comment]
Ok, we will work this and see what's going wrong when using --target install. Thanks for reporting this issue.

**Comment by legleux** [comment]
This was fixed a long time ago
