### ISSUE TITLE
Add other currencies' faucet in XRP-L testnet

### ISSUE THREAD

**Issue by wojake** [XRPLF/rippled#3897]
## Summary
Add standard currencies in XRP-L testnet for developers to operate their applications efficiently with active offers on the native DeX. 

## Motivation
Upgrading trading liquidity on buy/sell order books on the native DeX, this will tremendously increase the ease of testing for developers, students, and institutions.

I am fully aware that users can create their own native token on the testnet and exchange from there on, to enhance the experience for the users, we should create standard currencies to allow the ease of testing applications.

## Solution
**1. Issue currencies using a Ripple owned wallet, here are a few suggested currencies to be added:**
- US Dollar
- Euro
- Bitcoin
- Ethereum

**2. Establish faucets for the respective currencies in xrpl.org _(https://xrpl.org/xrp-testnet-faucet.html)_**

**3. Run servers that actively exchange the standard currencies to XRP (_vice versa_) using different wallets with different trading price**

**Comment by nbougalis** [comment]
This is probably not the right repo for this, but is an interesting suggestion.

Tagging @intelliot and @mDuo13 for visibility.

**Comment by mDuo13** [comment]
Cool idea, and could interact neatly with another idea I had which is kind of the reverse of this. (I was thinking a Testnet bot that goes out of its way to acquire various tokens issued in the Testnet would be neat.) An "arbitrary token faucet" would be probably easier to set up and run than what I had in mind.

**Comment by RaynerLim** [comment]
Yes this is definitely needed as well as an issuer address for issued currencies as I am working on an app which does all its transactions on the xrp ledger but realized that there does not seem to be any issuer for buy or sending issued currency on the testnet other than to create your own issuer

**Comment by wojake** [comment]
Closing, Issue does not relate to rippled.
