### ISSUE TITLE
Request for a possibility to create a true market order/offer

### ISSUE THREAD

**Issue by KoenPaas** [XRPLF/rippled#3961]
## Summary
Currently it is not natively supported to create a [market order](https://www.investopedia.com/terms/m/marketorder.asp)
A work around is to either set the limit price to the lowest/highest possible which makes it effectively a market order or to add/subtract a percentage.

I understand that a Market order is a dangerous type, it would however be a nice addition to the dex.

## Solution
The solution would be to create a new flag for this behaviour or the possibility to set the value at -1 (TakerPays) on the OfferCreate

**Comment by intelliot** [comment]
As previously stated, you can create a market order by creating an offer with a price that is far worse than what the market is currently offering.

**Comment by KoenPaas** [comment]
@intelliot I understand that you can practically create one, however as a dex interface provider I can’t determine if it was created as a limit order or as a market order.

therefore it would be cool if a true market order would be possible.

**Comment by MarkusTeufelberger** [comment]
As there are no true market orders possible currently, all orders are limit orders, so no interface issue there.
