### ISSUE TITLE
rippled often return telINSUF_FEE_P (Version: 1.7.3)

### ISSUE THREAD

**Issue by niso1985** [XRPLF/rippled#4006]
related: https://github.com/ripple/rippled/issues/3594#issuecomment-681148951

## Issue Description

We run two rippled on managed server environment. Recently, both of the rippled start to function weirdly. They often return telINSUF_FEE_P status after transaction submit.

We have two questions.
 - Was there any network upgrade which affect performance after 1.7.3 upgrade?
 - Is this error avoidable if we set minimum fee more than 10?

## Steps to Reproduce

Run rippled server v1.7.3.

## Expected Result

Rippled will run just fine without cpu/ram increase over time.

## Actual Result

Rippled will run with cpu/ram increase over time, returns telINSUF_FEE_P occasionally and stay unstable over time.

## Environment

uname -a
Linux *** 3.10.0-693.el7.x86_64 #1 SMP Thu Jul 6 19:56:57 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.4 (Maipo)

rippled version 1.7.3

## Supporting Files
![01-20211001-20211126](https://user-images.githubusercontent.com/2194255/143796480-737d4288-0e72-43f0-8559-be2b584feb52.png)
![02-20211001-20211126](https://user-images.githubusercontent.com/2194255/143796489-d863a32f-ea72-4e64-a8cf-213796dca8cf.png)
![02-20211115-20211126](https://user-images.githubusercontent.com/2194255/143796492-22c4aa91-307d-4f37-bb0f-0c3b9a3ea96e.png)

**Comment by intelliot** [comment]
@niso1985 - After getting `telINSUF_FEE_P`, does your transaction ultimately succeed (after some time)? You'll need to query (e.g. using `tx`) to see if that's the case.

`telINSUF_FEE_P` is a provisional (tentative) result. If the server's load factor goes down (which is common) then (unless you specified `fail_hard`) rippled will automatically retry the transaction a few times.

As for your questions:

- Was there any network upgrade which affect performance after 1.7.3 upgrade?
  - No, there was no network (protocol) upgrade that would adversely affect performance, as far as we know. However, overall network activity and the ledger size has grown, which leads to performance issues and elevated load for some nodes.
- Is this error avoidable if we set minimum fee more than 10?
  - Yes. Also, note that this error is tentative (provisional). It does not mean that your transaction failed, but only that it was not immediately applied to the node's open ledger.

**Comment by mvadari** [comment]
Closing this issue as it was likely related to the network instability at the time and is no longer relevant (especially since tooling etc. now handles fee escalation better).
