### ISSUE TITLE
CI: Improve instructions for finding and applying the patch generated by failed Github Actions (Version: 1.8.1)

### ISSUE THREAD

**Issue by ximinez** [XRPLF/rippled#4020]
## Issue Description

The instructions provided on failed jobs ([example](https://github.com/ripple/rippled/runs/4455580047)) don't clearly explain where to find the generated patch file. This can be a problem for anyone who is not familiar with how Github Actions pages are organized.

The general idea is: 
> From the details page, click on "Summary", then scroll down to the "Artifacts" section. There's a clang-format.patch/levelization.patch file there. Download it into your repo then run `git apply [patchfile]`. Commit and push.

**Comment by abu1861** [comment]
kindly assign to me.

**Comment by abuharish02** [comment]
![Screenshot (25)](https://user-images.githubusercontent.com/111338069/202431515-8acc1dfa-aaa1-465b-b539-7faef77f6808.png)
Hey,  "clang-format.patch" file is not available. Kindly provide me.

**Comment by intelliot** [comment]
To download the patch file:
1. Next to `clang-format / check (pull_request) Failing after #s` -> click **Details**
2. Left menu -> click **Summary**
3. Near bottom right under `Artifacts` -> click **clang-format.patch**
