### ISSUE TITLE
Multiple submits of same transaction return different error codes (Version: 1.8.1)

### ISSUE THREAD

**Issue by AlexisChevalier** [XRPLF/rippled#4075]
## Issue Description
I notice that when I retry to submit the same signed transaction to a Rippled node I get different results between the first call and the subsequent ones. This behavior resets after some time, so I assume there must be some internal caching or something similar, but I am not sure that the responses from the server are the expected ones.

In our application we rebroadcast periodically the transaction in order to prevent against network issues and this causes some unexpected behaviour on our end, I wanted to know if this was expected behaviour or if this is a bug ?

Thanks in advance for your help

## Steps to Reproduce
Submit twice the following RPC request on a testnet node (the signed transaction sends the same currency to itself, so it is invalid anyway):
```
{
    "method": "submit",
    "params": [
        {
            "tx_blob": "120000228000000024016AF3ED201B0175DF9C6140000000000186A06840000000000013EC732102DB6E4F9FF31A332346486698DBC836B036007C82AEFCF8368A82DC16939F533574463044022019E5D53DC4626F8D0AA5A755AFB25D2E6A573DBF9AC7B3098312988FC44104EE0220163054176F15E7E71A520EFFF8FAAA79E5FCA45E89AF84A6A3E9DE1FA2731F2081146FD8E6DC9907866D0F2AD3BE0B77A696C59D34B783146FD8E6DC9907866D0F2AD3BE0B77A696C59D34B7"
        }
    ]
}
```

## Expected Result
I'd expect to have twice the same error result: 
```
"engine_result": "temREDUNDANT",
"engine_result_code": -275,
"engine_result_message": "Sends same currency to self.",
```

## Actual Result
I have a first result with the expected error result:
```
{
    "result": {
        "accepted": true,
        "account_sequence_available": 23786477,
        "account_sequence_next": 23786477,
        "applied": false,
        "broadcast": false,
        "engine_result": "temREDUNDANT",
        "engine_result_code": -275,
        "engine_result_message": "Sends same currency to self.",
        "kept": true,
        "open_ledger_cost": "10",
        "queued": false,
        "status": "success",
        "tx_blob": "120000228000000024016AF3ED201B0175DF9C6140000000000186A06840000000000013EC732102DB6E4F9FF31A332346486698DBC836B036007C82AEFCF8368A82DC16939F533574463044022019E5D53DC4626F8D0AA5A755AFB25D2E6A573DBF9AC7B3098312988FC44104EE0220163054176F15E7E71A520EFFF8FAAA79E5FCA45E89AF84A6A3E9DE1FA2731F2081146FD8E6DC9907866D0F2AD3BE0B77A696C59D34B783146FD8E6DC9907866D0F2AD3BE0B77A696C59D34B7",
        "tx_json": {
            "Account": "rBUPqttkLL5uHvp32y9V4yuXnZWkmq5TRQ",
            "Amount": "100000",
            "Destination": "rBUPqttkLL5uHvp32y9V4yuXnZWkmq5TRQ",
            "Fee": "5100",
            "Flags": 2147483648,
            "LastLedgerSequence": 24502172,
            "Sequence": 23786477,
            "SigningPubKey": "02DB6E4F9FF31A332346486698DBC836B036007C82AEFCF8368A82DC16939F5335",
            "TransactionType": "Payment",
            "TxnSignature": "3044022019E5D53DC4626F8D0AA5A755AFB25D2E6A573DBF9AC7B3098312988FC44104EE0220163054176F15E7E71A520EFFF8FAAA79E5FCA45E89AF84A6A3E9DE1FA2731F20",
            "hash": "BD1E2FDA03F5495EC9A08B9958A6007FF8CC9D52B8EBE9E7FC6A48B3D89D2445"
        },
        "validated_ledger_index": 24534927
    }
}
```

And a second result with an unrelated error:
```
{
    "result": {
        "accepted": false,
        "applied": false,
        "broadcast": false,
        "engine_result": "temBAD_SIGNATURE",
        "engine_result_code": -282,
        "engine_result_message": "Malformed: Bad signature.",
        "kept": false,
        "queued": false,
        "status": "success",
        "tx_blob": "120000228000000024016AF3ED201B0175DF9C6140000000000186A06840000000000013EC732102DB6E4F9FF31A332346486698DBC836B036007C82AEFCF8368A82DC16939F533574463044022019E5D53DC4626F8D0AA5A755AFB25D2E6A573DBF9AC7B3098312988FC44104EE0220163054176F15E7E71A520EFFF8FAAA79E5FCA45E89AF84A6A3E9DE1FA2731F2081146FD8E6DC9907866D0F2AD3BE0B77A696C59D34B783146FD8E6DC9907866D0F2AD3BE0B77A696C59D34B7",
        "tx_json": {
            "Account": "rBUPqttkLL5uHvp32y9V4yuXnZWkmq5TRQ",
            "Amount": "100000",
            "Destination": "rBUPqttkLL5uHvp32y9V4yuXnZWkmq5TRQ",
            "Fee": "5100",
            "Flags": 2147483648,
            "LastLedgerSequence": 24502172,
            "Sequence": 23786477,
            "SigningPubKey": "02DB6E4F9FF31A332346486698DBC836B036007C82AEFCF8368A82DC16939F5335",
            "TransactionType": "Payment",
            "TxnSignature": "3044022019E5D53DC4626F8D0AA5A755AFB25D2E6A573DBF9AC7B3098312988FC44104EE0220163054176F15E7E71A520EFFF8FAAA79E5FCA45E89AF84A6A3E9DE1FA2731F20",
            "hash": "BD1E2FDA03F5495EC9A08B9958A6007FF8CC9D52B8EBE9E7FC6A48B3D89D2445"
        }
    }
}
```

We have seen the exact same pattern with a transaction trying to send 0 XRP, but this time the first request returns a `temBAD_AMOUNT` and the subsequent ones return a `temBAD_SIGNATURE`.

## Environment
Our nodes are hosted by a SaaS provider, but I have been able to reproduce the issue using https://s.altnet.rippletest.net:51234/.

## Supporting Files
No files to provide

**Comment by ximinez** [comment]
First, and most importantly, the result returned from `submit` is always preliminary, and subject to change. See [Reliable Transaction Submission](https://xrpl.org/reliable-transaction-submission.html) for more detailed information.

That said, your guess about an internal cache appears to be spot-on. If a transaction gets any `tem` result, indicating that it is malformed, a flag is set indicating the transaction is bad: https://github.com/ripple/rippled/blob/develop/src/ripple/app/misc/NetworkOPs.cpp#L1353-L1354. If the same transaction is seen again later, something that is more of an issue with transactions coming from the peer network, rippled sees that flag set, and sets the result to `temBAD_SIGNATURE`: https://github.com/ximinez/rippled/blob/6b1a820ff8be5b1f22a6ffe6cf18ca5bd0081972/src/ripple/app/misc/NetworkOPs.cpp#L1170-L1178

I would say that this is a bug, but a relatively small one. The most important thing about the result is that it's telling you the transaction is malformed, which is true for both results. Any more detail for that is generally intended for a human to look at to be able to make a correction. The assumption here is that a human is going to look at the result the first time it happens, and not resubmit a known-bad transaction. (With a one or two extremely narrow exceptions related to the timing of amendments being enabled, if an app is resubmitting a known-bad transaction, the app is behaving badly.)

It might be worth changing the result for a known-bad transaction to be something more generic, like `temMALFORMED`, but right now I don't think anything more than that is necessary or useful.

**Comment by intelliot** [comment]
@ximinez is correct: rippled caches almost all submitted transactions (unless you specify `fail_hard` when submitting) and automatically retries them a few times. That's why it's generally not safe to use the immediate response from transaction submission for any business logic purpose. It's interesting for debugging and to see what's going on, but your app should not make any decisions based on the response (unless you use `fail_hard`).

Notice in the response: `"kept": true` - this means rippled stored the transaction (and may retry it a few times before dropping it).


> _Sidenote:_
> Ideally, I think `temREDUNDANT`, `temBAD_AMOUNT`, and in fact all `tem` codes should be final errors and rippled should not keep or retry them (and the response should say `"kept": false`). But this is a larger, separate discussion and would be a change in behavior from the status quo.

**Comment by AlexisChevalier** [comment]
Thanks for your detailed responses.

We are using this response to determine if we should keep retrying to broadcast or if we should give up and forward some feedback to the user. Having deterministic responses is important for us because if we have a network error during the first request the only feedback that we have is `tem_BAD_SIGNATURE`, which is something that will trigger a bug on our end rather than a useful information for the end user.

I have tried to use `fail_hard` as you suggested, but it doesn't seem to change the result:

```
{
    "method": "submit",
    "params": [
        {
            "tx_blob": "120000228000000024016AF3ED201B0175DF9C6140000000000186A06840000000000013EC732102DB6E4F9FF31A332346486698DBC836B036007C82AEFCF8368A82DC16939F533574463044022019E5D53DC4626F8D0AA5A755AFB25D2E6A573DBF9AC7B3098312988FC44104EE0220163054176F15E7E71A520EFFF8FAAA79E5FCA45E89AF84A6A3E9DE1FA2731F2081146FD8E6DC9907866D0F2AD3BE0B77A696C59D34B783146FD8E6DC9907866D0F2AD3BE0B77A696C59D34B7",
            "fail_hard": true
        }
    ]
}
```

First response:
```
{
    "result": {
        "accepted": false,
        "account_sequence_available": 23786477,
        "account_sequence_next": 23786477,
        "applied": false,
        "broadcast": false,
        "engine_result": "temREDUNDANT",
        "engine_result_code": -275,
        "engine_result_message": "Sends same currency to self.",
        "kept": false,
        "open_ledger_cost": "10",
        "queued": false,
        "status": "success",
        "tx_blob": "120000228000000024016AF3ED201B0175DF9C6140000000000186A06840000000000013EC732102DB6E4F9FF31A332346486698DBC836B036007C82AEFCF8368A82DC16939F533574463044022019E5D53DC4626F8D0AA5A755AFB25D2E6A573DBF9AC7B3098312988FC44104EE0220163054176F15E7E71A520EFFF8FAAA79E5FCA45E89AF84A6A3E9DE1FA2731F2081146FD8E6DC9907866D0F2AD3BE0B77A696C59D34B783146FD8E6DC9907866D0F2AD3BE0B77A696C59D34B7",
        "tx_json": {
            "Account": "rBUPqttkLL5uHvp32y9V4yuXnZWkmq5TRQ",
            "Amount": "100000",
            "Destination": "rBUPqttkLL5uHvp32y9V4yuXnZWkmq5TRQ",
            "Fee": "5100",
            "Flags": 2147483648,
            "LastLedgerSequence": 24502172,
            "Sequence": 23786477,
            "SigningPubKey": "02DB6E4F9FF31A332346486698DBC836B036007C82AEFCF8368A82DC16939F5335",
            "TransactionType": "Payment",
            "TxnSignature": "3044022019E5D53DC4626F8D0AA5A755AFB25D2E6A573DBF9AC7B3098312988FC44104EE0220163054176F15E7E71A520EFFF8FAAA79E5FCA45E89AF84A6A3E9DE1FA2731F20",
            "hash": "BD1E2FDA03F5495EC9A08B9958A6007FF8CC9D52B8EBE9E7FC6A48B3D89D2445"
        },
        "validated_ledger_index": 24559119
    }
}
```

Second response:
```
{
    "result": {
        "accepted": false,
        "applied": false,
        "broadcast": false,
        "engine_result": "temBAD_SIGNATURE",
        "engine_result_code": -282,
        "engine_result_message": "Malformed: Bad signature.",
        "kept": false,
        "queued": false,
        "status": "success",
        "tx_blob": "120000228000000024016AF3ED201B0175DF9C6140000000000186A06840000000000013EC732102DB6E4F9FF31A332346486698DBC836B036007C82AEFCF8368A82DC16939F533574463044022019E5D53DC4626F8D0AA5A755AFB25D2E6A573DBF9AC7B3098312988FC44104EE0220163054176F15E7E71A520EFFF8FAAA79E5FCA45E89AF84A6A3E9DE1FA2731F2081146FD8E6DC9907866D0F2AD3BE0B77A696C59D34B783146FD8E6DC9907866D0F2AD3BE0B77A696C59D34B7",
        "tx_json": {
            "Account": "rBUPqttkLL5uHvp32y9V4yuXnZWkmq5TRQ",
            "Amount": "100000",
            "Destination": "rBUPqttkLL5uHvp32y9V4yuXnZWkmq5TRQ",
            "Fee": "5100",
            "Flags": 2147483648,
            "LastLedgerSequence": 24502172,
            "Sequence": 23786477,
            "SigningPubKey": "02DB6E4F9FF31A332346486698DBC836B036007C82AEFCF8368A82DC16939F5335",
            "TransactionType": "Payment",
            "TxnSignature": "3044022019E5D53DC4626F8D0AA5A755AFB25D2E6A573DBF9AC7B3098312988FC44104EE0220163054176F15E7E71A520EFFF8FAAA79E5FCA45E89AF84A6A3E9DE1FA2731F20",
            "hash": "BD1E2FDA03F5495EC9A08B9958A6007FF8CC9D52B8EBE9E7FC6A48B3D89D2445"
        }
    }
}
```

I noticed the `"kept": false,` in both respones, which seems to indicate that rippled didn't stored the transaction, but for some reason there still seems to be some cache involved there since the `engine_*` fields are still different between the two requests.

Am I not using `fail_hard` correctly ? or is there something else that I am missing ?

Thanks

**Comment by ximinez** [comment]
1. You used `fail_hard` correctly. The "bad" flag I referenced earlier is set regardless of `fail_hard`, because it is keyed on the transaction hash. The transaction itself is not kept.
2. Regardless of the exact code, you should never rebroadcast a transaction where the result code starts with `tem`, because that transaction will never succeed. I would even go so far as to say that if you get any response other than those starting with `ter`, rebroadcasting is probably a waste of time. And even `ter` codes will usually be retried by the rippled node you submitted to. So my suggestion would be to kick any `tem` result back to the user.
3. As much as possible, you should avoid even creating malformed transactions in your code. Most if not all of the `tem` errors can be detected and/or avoided client-side.
4. Unfortunately, there is no workaround that I know to the `temBAD_SIGNATURE` result on subsequent submissions. Changing that will require a code change, but even with a change, it'll likely be a generic error instead of the original result.
5. A much better method to see if a transaction has been received by the server is to use the `tx` command to look up the transaction hash. If it was not processed at all, you'll get a "Transaction not found" message, which could indicate it's worth resubmitting, or you'll get the transaction back with a flag indicating whether the transaction has included in a validated ledger or not (`validated`). (You'll need to use `ledger_index: current` if you might be talking to a reporting server.)

**Comment by AlexisChevalier** [comment]
Thanks for the precisions and the clarification regarding `fail_hard`.

Regarding your point 2, we are rebroadcasting to handle cases where we have a failure (network, crash, etc..) between the broadcast request and the response, so in some cases we cannot be sure whether the transaction has been received by the node or not.
Usually with other blockchain nodes we have either a deterministic responses for erroneous cases, or an information telling us that the node already knows that transaction.

Regading point 3 you are definitely right, I already created an issue for us to add those checks in our application, but I think we will discover other cases like this later, so I prefer to have a robust error handling strategy.

If I may share my point of view regarding point 4 and 5, I understand that querying the `tx` command would inform me of the validation or non-validation of a submitted TX, and whilst this helps with reliable broadcasting it doesn't entierly solve the issue because I cannot access the real, original, error code if I missed it due to a network issue (which would be nice to have in logs/API feedback).
I kind of agree with the sidenode of @intelliot on this, if an error code is considered "final", then there I don't see much interest in keeping the transaction hash in cache, I'd argue it makes reliable broadcast more complicated to achieve.
But I understand this would require changes.

If you can confirm that receiving `temBAD_SIGNATURE` (or any other `tem_*` always means that the transaction will not be accepted on-chain (either because the signature is actually invalid or because it hides another definitive error) then I think this is something I can work with in order to handle such errors, we might have some loss of precision in the error response sometimes but it would already be much better.

Thanks

**Comment by ximinez** [comment]
> Thanks for the precisions and the clarification regarding `fail_hard`.

You're welcome. 

> Regarding your point 2, we are rebroadcasting to handle cases where we have a failure (network, crash, etc..) between the broadcast request and the response, so in some cases we cannot be sure whether the transaction has been received by the node or not. Usually with other blockchain nodes we have either a deterministic responses for erroneous cases, or an information telling us that the node already knows that transaction.

Yeah, that's fair. That's a very specific edge case, but certainly possible. Do be aware that if the node does have the transaction when you resubmit it, the result will *not* be `tesSUCCESS`. It will most likely be `tefALREADY` if the transaction has not been validated, or `tefPAST_SEQ` if it has. But you'll also get `tefPAST_SEQ` if *another* transaction using the same sequence number was validated instead, which is why `tx` is so important.

> Regading point 3 you are definitely right, I already created an issue for us to add those checks in our application, but I think we will discover other cases like this later, so I prefer to have a robust error handling strategy.

Agreed.

> If you can confirm that receiving `temBAD_SIGNATURE` (or any other `tem_*` always means that the transaction will not be accepted on-chain (either because the signature is actually invalid or because it hides another definitive error) then I think this is something I can work with in order to handle such errors, we might have some loss of precision in the error response sometimes but it would already be much better.

It can only be guaranteed to not be validated if you use `fail_hard: true` and are submitting to a node you trust.

I'll emphasize again that the initial response code is tentative. `fail_hard` narrows that down, but even a transaction that gets `tesSUCCESS` can end up not getting validated, or get validated with only a fee claimed (`tec` codes), and that result is only final if it's in the metadata from a validated ledger.

**Comment by AlexisChevalier** [comment]
Ok, makes sense, I will schedule the appropriate changes on our end.

Regarding the issue I'll leave it up to you if you want to close it or keep it open and consider the non-determinism of failure code as a bug or not.

Thank you very much for the help on the topic.

**Comment by intelliot** [comment]
The non-determinism of failure codes, in the way you described, is expected behavior. I would be in favor of updating the documentation to make this more clear, and opened https://github.com/XRPLF/xrpl-dev-portal/issues/1680 to track this.
