### ISSUE TITLE
Feature Request: add ability to specify network alongside ip for admin option

### ISSUE THREAD

**Issue by gituser** [XRPLF/rippled#4076]
## Summary
Currently there is no way to specify a subnet for admin option, e.g. `10.0.0.0/24` in various parts of `rippled.cfg`, e.g.
`admin = 10.0.0.0/24`
or 
`admin = 10.0.0.0/8`

The only way is to restrict `admin` specific commands to a single IP address.

## Motivation
When you have multiple hosts running and want to access `admin` features you need to workaround this either with:
* iptables
* add multiple port definitions and specify for each port different `admin` directive

## Solution
Add an ability to restrict `admin` option with network definition alongside IP.

**Comment by mtrippled** [comment]
@gituser 
Good idea--I implemented this: [](https://github.com/ripple/rippled/pull/4088)

After it passes code review, it will then be included in an upcoming release. You can also try it before then if you build this branch and deploy it, but be aware that it hasn't yet gone through all of the review and testing phases.

**Comment by mtrippled** [comment]
Here's the configuration instructions: https://github.com/ripple/rippled/pull/4088

**Comment by mtrippled** [comment]
Here are the new configuration instructions: https://github.com/ripple/rippled/blob/79e77070e5cad0b29eabf546a75eb88080af0c5a/cfg/rippled-example.cfg#L203-L213

**Comment by gituser** [comment]
@mtrippled sick! I'll try your branch and report back, big thanks for implementing this!

**Comment by intelliot** [comment]
Fixed by #4088
