### ISSUE TITLE
Still no contributing.md

### ISSUE THREAD

**Issue by RichardAH** [XRPLF/rippled#4117]
https://github.com/ripple/rippled/pull/3955
https://github.com/ripple/rippled/issues/3312
https://github.com/ripple/rippled/pull/3922

Why?

**Comment by wojake** [comment]
Honestly, this is just a guess but I think the maintainers want to write a complete and understandable contributing page for devs to refer to. The contributing.md that I provided is a good base format to start off, but it looks complete to me and understandable to me.

**Comment by intelliot** [comment]
Just linking so that anyone coming across this issue has context: #4214

**Comment by intelliot** [comment]
Fixed by https://github.com/XRPLF/rippled/pull/4214. (I'd close this issue, as well as https://github.com/XRPLF/rippled/issues/3312, but I don't have permission.)

**Comment by WietseWind** [comment]
> Fixed by #4214. (I'd close this issue, as well as #3312, but I don't have permission.)

Thank you! And you should have permission now :)
