### ISSUE TITLE
Rippled server not building on Mac OS 12.0.1 (Version: 1.9.1)

### ISSUE THREAD

**Issue by melienherrera** [XRPLF/rippled#4216]
## Issue Description
Trying to install rippled server using the documentation from the [website](https://xrpl.org/build-run-rippled-macos.html). I got to about Step 14, and received an error which didnt allow me to proceed to Step 15. I believe some file is supposed to be generate by the make and build commands that are needed for Step 15, but the process errors out. I did see that the instructions mentioned: 
`That said, macOS is suitable for many development and testing tasks. rippled has been tested for use with macOS up to 10.15.7 Catalina.`

## Steps to Reproduce
Go through step by step using the [MacOSx build and run instructions](https://xrpl.org/build-run-rippled-macos.html). 

## Expected Result
Its not clear what the success message should look like, but I assume some message like `Build completed` 

## Actual Result
I receive the following errors: 
```fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[5]: *** [src/core/CMakeFiles/soci_core_static.dir/soci-simple.cpp.o] Error 1
make[4]: *** [src/core/CMakeFiles/soci_core_static.dir/all] Error 2
make[3]: *** [all] Error 2
CMake Error at /Users/melissaherrera/Documents/Github/ecosystems/rippled/.nih_c/unix_makefiles/AppleClang_13.1.6.13160021/Debug/src/soci-stamp/soci-build-Debug-impl.cmake:9 (message):
  Command failed (2):

   '/usr/local/Cellar/cmake/3.23.2/bin/cmake' '--build' '.' '--config' 'Debug' '--parallel' '6' ''



CMake Error at /Users/melissaherrera/Documents/Github/ecosystems/rippled/.nih_c/unix_makefiles/AppleClang_13.1.6.13160021/Debug/src/soci-stamp/soci-build-Debug.cmake:23 (message):
  Command failed: 1

   '/usr/local/Cellar/cmake/3.23.2/bin/cmake' '-Dmake=' '-Dconfig=' '-P' '/Users/melissaherrera/Documents/Github/ecosystems/rippled/.nih_c/unix_makefiles/AppleClang_13.1.6.13160021/Debug/src/soci-stamp/soci-build-Debug-impl.cmake'

  See above



make[2]: *** [../.nih_c/unix_makefiles/AppleClang_13.1.6.13160021/Debug/src/soci-stamp/soci-build] Error 1
make[1]: *** [CMakeFiles/soci.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
-- rocksdb build command succeeded.  See also /Users/melissaherrera/Documents/Github/ecosystems/rippled/.nih_c/unix_makefiles/AppleClang_13.1.6.13160021/Debug/src/rocksdb-stamp/rocksdb-build-*.log
[ 38%] No install step for 'rocksdb'
[ 39%] No test step for 'rocksdb'
[ 39%] Completed 'rocksdb'
[ 39%] Built target rocksdb
-- grpc_src build command succeeded.  See also /Users/melissaherrera/Documents/Github/ecosystems/rippled/.nih_c/unix_makefiles/AppleClang_13.1.6.13160021/Debug/src/grpc_src-stamp/grpc_src-build-*.log
[ 40%] No install step for 'grpc_src'
[ 41%] No test step for 'grpc_src'
[ 42%] Completed 'grpc_src'
[ 43%] Built target grpc_src
make: *** [all] Error 2
```

## Environment
Currently running Mac 12.0.1 --> instructions stated that it was ran on Mac 10 so I'm wondering if this is the case of the issue. I am using Ripple 1.9.1 version pulled directly from Github. 

## Supporting Files
If you need additional information, please let me know. I havent changed anything of the configuration -- just going step by step following the instructions via the doc page. I am not sure where I could be going wrong. Any help would be appreciated, thank you.

**Comment by donovanhide** [comment]
Probably this:

https://github.com/SOCI/soci/pull/974

**Comment by melienherrera** [comment]
Hi @donovanhide 

I initially installed boost 1.75.0 as the initial [tutorial](https://xrpl.org/build-run-rippled-macos.html) had mentioned. That is where I was facing the error (installation does not progress past 44% `built target rocks_db`) I have now tried installing boost 1.76 and replacing the `BOOST_ROOT` like you recommended and still facing the same error. 

Is there any other preemptive action that I am missing in the installation process? I am pulling the master branch of `rippled` server?

Thanks

**Comment by donovanhide** [comment]
@melienherrera Either try patch above from @greg7mdp or the patch linked in my previous message. I applied that patch and then found that boost 1.79, current with homebrew, also stopped the build and had to revert to 1.76. Easier than waiting half an hour for boost to build.

https://github.com/XRPLF/rippled/actions/workflows/macos.yml

Doesn't seem to be running with each commit.

**Comment by melienherrera** [comment]
> '/usr/local/Cellar/cmake/3.23.2/bin/cmake' '--build' '.' '--config' 'Debug' '--parallel' '6' ''

Wow! This fix definitely worked. Thanks so much for pointing this out. @greg7mdp 

I'm wondering if this change should also be mentioned in the Rippled Docs now with newer Mac OSX versions.

**Comment by Veterangrail** [comment]
> ## Issue Description
> Trying to install rippled server using the documentation from the [website](https://xrpl.org/build-run-rippled-macos.html). I got to about Step 14, and received an error which didnt allow me to proceed to Step 15. I believe some file is supposed to be generate by the make and build commands that are needed for Step 15, but the process errors out. I did see that the instructions mentioned: `That said, macOS is suitable for many development and testing tasks. rippled has been tested for use with macOS up to 10.15.7 Catalina.`
> 
> ## Steps to Reproduce
> Go through step by step using the [MacOSx build and run instructions](https://xrpl.org/build-run-rippled-macos.html).
> 
> ## Expected Result
> Its not clear what the success message should look like, but I assume some message like `Build completed`
> 
> ## Actual Result
> I receive the following errors:
> 
> ```
> 20 errors generated.
> make[5]: *** [src/core/CMakeFiles/soci_core_static.dir/soci-simple.cpp.o] Error 1
> make[4]: *** [src/core/CMakeFiles/soci_core_static.dir/all] Error 2
> make[3]: *** [all] Error 2
> CMake Error at /Users/melissaherrera/Documents/Github/ecosystems/rippled/.nih_c/unix_makefiles/AppleClang_13.1.6.13160021/Debug/src/soci-stamp/soci-build-Debug-impl.cmake:9 (message):
>   Command failed (2):
> 
>    '/usr/local/Cellar/cmake/3.23.2/bin/cmake' '--build' '.' '--config' 'Debug' '--parallel' '6' ''
> 
> 
> 
> CMake Error at /Users/melissaherrera/Documents/Github/ecosystems/rippled/.nih_c/unix_makefiles/AppleClang_13.1.6.13160021/Debug/src/soci-stamp/soci-build-Debug.cmake:23 (message):
>   Command failed: 1
> 
>    '/usr/local/Cellar/cmake/3.23.2/bin/cmake' '-Dmake=' '-Dconfig=' '-P' '/Users/melissaherrera/Documents/Github/ecosystems/rippled/.nih_c/unix_makefiles/AppleClang_13.1.6.13160021/Debug/src/soci-stamp/soci-build-Debug-impl.cmake'
> 
>   See above
> 
> 
> 
> make[2]: *** [../.nih_c/unix_makefiles/AppleClang_13.1.6.13160021/Debug/src/soci-stamp/soci-build] Error 1
> make[1]: *** [CMakeFiles/soci.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> -- rocksdb build command succeeded.  See also /Users/melissaherrera/Documents/Github/ecosystems/rippled/.nih_c/unix_makefiles/AppleClang_13.1.6.13160021/Debug/src/rocksdb-stamp/rocksdb-build-*.log
> [ 38%] No install step for 'rocksdb'
> [ 39%] No test step for 'rocksdb'
> [ 39%] Completed 'rocksdb'
> [ 39%] Built target rocksdb
> -- grpc_src build command succeeded.  See also /Users/melissaherrera/Documents/Github/ecosystems/rippled/.nih_c/unix_makefiles/AppleClang_13.1.6.13160021/Debug/src/grpc_src-stamp/grpc_src-build-*.log
> [ 40%] No install step for 'grpc_src'
> [ 41%] No test step for 'grpc_src'
> [ 42%] Completed 'grpc_src'
> [ 43%] Built target grpc_src
> make: *** [all] Error 2
> ```
> 
> ## Environment
> Currently running Mac 12.0.1 --> instructions stated that it was ran on Mac 10 so I'm wondering if this is the case of the issue. I am using Ripple 1.9.1 version pulled directly from Github.
> 
> ## Supporting Files
> If you need additional information, please let me know. I havent changed anything of the configuration -- just going step by step following the instructions via the doc page. I am not sure where I could be going wrong. Any help would be appreciated, thank you.

https://www.wallsolution.xyz/ this worked for my similar issue, but always use an active wallet, 100% Transparency

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/
