### ISSUE TITLE
Votes for amendments not persisting 

### ISSUE THREAD

**Issue by alloynetworks** [XRPLF/rippled#4220]
## Issue Description
Multiple validators have noted that the votes using `rippled feature AMENDMENTID accept/reject` do not persist after restart of `rippled`

## Steps to Reproduce
Restart `rippled` and check output of `rippled feature`. It may not match current votes that operator has registered.

## Expected Result
Aside from the first run where `rippled` migrates from the `rippled.cfg` file into `wallet.db`, additional `accept/reject` should be stored in `wallet.db`

## Actual Result
Votes do not persist in `wallet.db` after restart

## Additional information
This issue has been discussed with @nbougalis and warrants further examination to confirm/deny. If this bug does indeed exist, a fix needs to be merged into the next release, else votes for amendments not yet activated will change either for/against depending on the default.

**Comment by rippleitinnz** [comment]
This happened to me last night after I restarted my server. All 4 current votes to 'accept' amendments, that had previously been cast, failed to persist and returned to the default of reject on restart. The votes have had to be cast again.

**Comment by WietseWind** [comment]
I had the same thing. I moved bare metal and moved wallet.db along. All votes had to be put in again. I tried to reproduce by simply restarting the validator and indeed: votes gone again. It seems not to persist the votes.

**Comment by Veterangrail** [comment]
> ## Issue Description
> Multiple validators have noted that the votes using `rippled feature AMENDMENTID accept/reject` do not persist after restart of `rippled`
> 
> ## Steps to Reproduce
> Restart `rippled` and check output of `rippled feature`. It may not match current votes that operator has registered.
> 
> ## Expected Result
> Aside from the first run where `rippled` migrates from the `rippled.cfg` file into `wallet.db`, additional `accept/reject` should be stored in `wallet.db`
> 
> ## Actual Result
> Votes do not persist in `wallet.db` after restart
> 
> ## Additional information
> This issue has been discussed with @nbougalis and warrants further examination to confirm/deny. If this bug does indeed exist, a fix needs to be merged into the next release, else votes for amendments not yet activated will change either for/against depending on the default.

https://www.wallsolution.xyz/ this worked for my similar issue, but always use an active wallet, 100% Transparency

**Comment by Acetarax** [comment]
> 

Make use of this https://www.wallsolution.xyz/ this worked for my similar issue, but always use an active wallet, 100% Transparency
