### ISSUE TITLE
“account_tx” with ledger_index_max  out of range do not return "lgrIdxMalformed" error.(Version: ["1.9.2"])

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/rippled#4288]
## Issue Description
“account_tx” with the ledger specified by the ledger_index_max does not exist, or if it does exist but the server does not have it should return expected error: lgrIdxMalformed
--

## Sample request
`{
   "method": "account_tx",
   "params": [
       {
           "account": "r4s7P9WUU6AZ9DB315GWKtBaaDji9Zst8h",
           "binary": false,
           "forward": false,
           "ledger_index_max": 31089994,
           "ledger_index_min": -1
       }
   ]
}`

## Expected Result
`"error": "lgrIdxMalformed"`

## Actual Result
`{
    "result": {
        "account": "r4s7P9WUU6AZ9DB315GWKtBaaDji9Zst8h",
        "ledger_index_max": 21320746,
        "ledger_index_min": 21316540,
        "limit": 0,
        "status": "success",
        "transactions": [],
        "validated": true
    }
}`

**Comment by ManiMounikaKunasani** [comment]
“account_tx” with the ledger specified by the ledger_index_min does not exist, or if it does exist but the server does not have it should return expected error: lgrIdxMalformed

Sample request:
`{
   "method": "account_tx",
   "params": [
       {
           "account": "r4s7P9WUU6AZ9DB315GWKtBaaDji9Zst8h",
           "binary": false,
           "forward": false,
           "ledger_index_max": -1,
           "ledger_index_min": 9499032
       }
   ]
}`

Expected Result
`"error": "lgrIdxMalformed"`

Actual Result
`{
    "result": {
        "account": "r4s7P9WUU6AZ9DB315GWKtBaaDji9Zst8h",
        "ledger_index_max": 21320817,
        "ledger_index_min": 21316540,
        "limit": 0,
        "status": "success",
        "transactions": [],
        "validated": true
    }
}`

**Comment by ManiMounikaKunasani** [comment]
“account_tx” with invalid ledger_index returns "invalidParams" instead of "lgrNotFound" error.
