### ISSUE TITLE
“ledger_entry” without default parameters not returning "invalidParams" error.

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/rippled#4303]
## Issue Description
“ledger_entry” with one or more fields are specified incorrectly, or one or more required fields are missing i.e., without index, account_root , directory, offer, ripple_state, check, escrow, payment_channel, deposit_preauth, ticket should result in invalidParams error.

## Steps to Reproduce
{
    "method": "ledger_entry",
    "params": [
        {
            "ledger_index": "validated"
        }
    ]
}

## Expected Result
invalidParams

## Actual Result
unknownOption

**Comment by arihantkothari** [comment]
should `malformedRequest`, `malformedAddress`, `malformedCurrency` also be `invalidParams` ?

**Comment by arihantkothari** [comment]
What is wrong with throwing `unknowOption` error ? 

Accord to [link](https://xrpl.org/ledger_entry.html#possible-errors),
unknownOption - The fields provided in the request did not match any of the expected request formats.
invalidParams - One or more fields are specified incorrectly, or one or more required fields are missing.
