### ISSUE TITLE
"account_nfts" with limit zero is returning available account_nfts.

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/rippled#4313]
## Issue Description
"account_nfts" with limit zero should either return "error_message": "limitNotPositive" or empty "account_nfts" list but instead the response has available account_nfts.

## Steps to Reproduce
`{
  "method": "account_nfts",
  "params": [{
    "account": "rKw2e76tXWz1r7U3rxRurZimZNZoAfJwt3",
    "limit": 0
  }]
}`

## Expected Result
`{
    "result": {
        "error": "invalidParams",
        "error_code": 31,
        "error_message": "limitNotPositive",
        "status": "error",
        "type": "response",
        "request": {
            "method": "account_nfts",
            "params": [
                {
                    "account": "rKw2e76tXWz1r7U3rxRurZimZNZoAfJwt3",
                    "ledger_index": "21972260",
                    "limit": 0
                }
            ]
        }
    }
}`
or
empty account_nfts list

## Actual Result
`{
    "result": {
        "account": "rKw2e76tXWz1r7U3rxRurZimZNZoAfJwt3",
        "account_nfts": [
            {
                "Flags": 0,
                "Issuer": "r4M5u59x7AAFG8pfZsGWZEYySvtEgnEaSt",
                "NFTokenID": "00000000EA45F1C360D23513A4BB457C574D2F4A1191C69D0000099B00000000",
                "NFTokenTaxon": 0,
                "nft_serial": 0
            },
            {
                "Flags": 0,
                "Issuer": "rKw2e76tXWz1r7U3rxRurZimZNZoAfJwt3",
                "NFTokenID": "00000000C742181B81333AB755A8FD87B466902DAB3904E916E5DA9C00000001",
                "NFTokenTaxon": 0,
                "nft_serial": 1
            },
            {
                "Flags": 0,
                "Issuer": "rKw2e76tXWz1r7U3rxRurZimZNZoAfJwt3",
                "NFTokenID": "00000000C742181B81333AB755A8FD87B466902DAB3904E92DCBAB9D00000002",
                "NFTokenTaxon": 0,
                "nft_serial": 2
            },
            {
                "Flags": 0,
                "Issuer": "rKw2e76tXWz1r7U3rxRurZimZNZoAfJwt3",
                "NFTokenID": "00000000C742181B81333AB755A8FD87B466902DAB3904E944B17C9E00000003",
                "NFTokenTaxon": 0,
                "nft_serial": 3
            },
            {
                "Flags": 0,
                "Issuer": "rKw2e76tXWz1r7U3rxRurZimZNZoAfJwt3",
                "NFTokenID": "00000000C742181B81333AB755A8FD87B466902DAB3904E95B974D9F00000004",
                "NFTokenTaxon": 0,
                "nft_serial": 4
            },
            {
                "Flags": 0,
                "Issuer": "rKw2e76tXWz1r7U3rxRurZimZNZoAfJwt3",
                "NFTokenID": "00000000C742181B81333AB755A8FD87B466902DAB3904E9727D1EA000000005",
                "NFTokenTaxon": 0,
                "nft_serial": 5
            }
        ],
        "ledger_current_index": 22137539,
        "status": "success",
        "validated": false
    }
}`

**Comment by ledhed2222** [comment]
doesn't this behavior contradict what you wrote in issue 4314?

**Comment by mounikakun** [comment]
Nope. Issue 4314 is about account_nfts with unassociated marker as in marker from other API and this issue is about limit value zero. Expected result for both cases is an error or empty list.

**Comment by ledhed2222** [comment]
i don't see why these two cases should result in the same outcome - they are two different cases. it makes sense to me that a limit input of 0 would result in an error.
