### ISSUE TITLE
For nft_buy_offers and nft_sell_offers with "limit":0 in the request returns empty offers list instead of "invalidParams" error.

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/rippled#4315]
## Steps to Reproduce
`{
  "method": "nft_sell_offers",
  "params": [{
    "nft_id": "000000004C17E5B8E33245D98126F4A6DF4EA57FF71C027B0000099B00000000",
    "ledger_index": "validated",
    "limit": 0
  }]
}`

`{
  "method": "nft_buy_offers",
  "params": [{
    "nft_id": "00080000B99F877D1AA8CD9C4C0110DA670BCB86138D54CF16E5DA9C00000001",
    "ledger_index": "validated",
    "limit": 0
  }]
}`

## Expected Result
`{
    "result": {
        "error": "invalidParams",
        "error_code": 31,
        "error_message": "limitNotPositive",
        "status": "error",
        "type": "response",
        "request": {
            "method": "nft_buy_offers",
            "params": [
                {
                    "nft_id": "00080000B99F877D1AA8CD9C4C0110DA670BCB86138D54CF16E5DA9C00000001",
                    "ledger_index": "validated",
                    "limit": 0
                }
            ]
        }
    },
}`
## Actual Result
`{
    "result": {
        "limit": 0,
        "marker": "122DA77793E227FC22BC42CF4180094A032DB97C1D8CD721D9C47CF40D21BF10",
        "nft_id": "00080000B99F877D1AA8CD9C4C0110DA670BCB86138D54CF16E5DA9C00000001",
        "offers": [],
        "status": "success"
    }
}`

**Comment by intelliot** [comment]
@shawnxie999 @ledhed2222 do you agree that this is an issue? If so, is it worth prioritizing?

**Comment by ledhed2222** [comment]
what environment is this that you're testing this on? I don't see this behavior. What is happening (and what should happen) when you provide a limit of 0 is that it defaults to the default limit of 50. I can't recreate getting an empty array of offers.
