### ISSUE TITLE
[Occasionally, blocks cannot be obtained] (Version: [1.9.4])

### ISSUE THREAD

**Issue by 1143857824** [XRPLF/rippled#4324]
## Issue Description
Occasionally, the block content cannot be obtained

## Steps to Reproduce
nothing

## Expected Result
The interface provides services stably

## Actual Result
Occasionally, the interface returns an error
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/57594569/196362608-fb21af8a-3988-40a4-8c50-7c8fd848a8da.png)

## Environment
Operating system: amazon linux
cpu: 16vCpu
Memory: 45G
Hard disk: aws io2/20000 iops
Node startup mode: Docker
Node version: 1.9.4

## Supporting Files
Nothing

**Comment by MarkusTeufelberger** [comment]
What does server_info say on that node?

**Comment by 1143857824** [comment]
@MarkusTeufelberger  
Hello, this is our node server_ Info and our test request. There are hundreds of blocks in the middle that cannot be accessed

[root@nwo-chain-node-ap26c ~]# curl -X POST -H 'Content-Type: application/json' --data '{"method": "server_info", "params": [{"api_version": 1}]}' http://127.0.0.1:61076 | python3 -m
 json.tool                                                                                                                                                                            
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                                                                                       
                                 Dload  Upload   Total   Spent    Left  Speed                                                                                                         
100  2605  100  2548  100    57  2488k  57000 --:--:-- --:--:-- --:--:-- 2543k                                                                                                        
{                                                                                                                                                                                     
    "result": {                                                                                                                                                                       
        "info": {                                                                                                                                                                     
            "build_version": "1.9.4",                                                                                                                                                 
            "complete_ledgers": "73286078-75156434",                                                                                                                                  
            "hostid": "wallet-xrp-mainnet-01",                                                                                                                                        
            "initial_sync_duration_us": "875663785",                                                                                                                                  
            "io_latency_ms": 1,                                                                                                                                                       
            "jq_trans_overflow": "3940",                                                                                                                                              
            "last_close": {                                                                                                                                                           
                "converge_time_s": 2.949,                                                                                                                                             
                "proposers": 35                                                                                                                                                       
            },                                                                                                                                                                        
            "load": {                                                                                                                                                                 
                "job_types": [                                                                                                                                                        
                    {                                                                                                                                                                 
                        "avg_time": 48,                                                                                                                                               
                        "job_type": "clientFeeChange",                                                                                                                                
                        "peak_time": 200,                                                                                                                                             
                        "per_second": 1                                                                                                                                               
                    },                                                                                                                                                                
                    {                                                                                                                                                                 
                        "avg_time": 6399,                                                                                                                                             
                        "in_progress": 1,                                                                                                                                             
                        "job_type": "clientRPC",                                                                                                                                      
                        "over_target": true,                                                                                                                                          
                        "peak_time": 105287,                                                                                                                                          
                        "per_second": 1                                                                                                                                               
                    },                                                                                                                                                                
                    {                                                                                                                                                                 
                        "avg_time": 57,                                                                                                                                               
                        "job_type": "untrustedValidation",                                                                                                                            
                        "peak_time": 367,                                                                                                                                             
                        "per_second": 41                                                                                                                                              
                    },                                                                                                                                                                
                    {                                                                                                                                                                 
                        "avg_time": 99,                                                                                                                                               
                        "in_progress": 1,                                                                                                                                             
                        "job_type": "ledgerRequest",                                                                                                                                  
                        "peak_time": 734,                                                                                                                                             
                        "per_second": 3                                                                                                                                               
                    },                                                                                                                                                                
                    {                                                                                                                                                                 
                        "avg_time": 36,                                                                                                                                               
                        "job_type": "transaction",                                                                                                                                    
                        "peak_time": 266,                                                                                                                                             
                        "per_second": 17                                                                                                                                              
                    },                                                                                                                                                                
                    {                                                                                                                                                                 
                        "avg_time": 1,                                                                                                                                                
                        "job_type": "batch",                                                                                                                                          
                        "peak_time": 327,                                                                                                                                             
                        "per_second": 17                                                                                                                                              
                    },                                                                                                                                                                
                    {                                                                                                                                                                 
                        "avg_time": 111,                                                                                                                                              
                        "in_progress": 3,                                                                                                                                             
                        "job_type": "ledgerData",                                                                                                                                     
                        "peak_time": 1063,                                                                                                                                            
                        "per_second": 1,                                                                                                                                              
                        "waiting": 1                                                                                                                                                  
                    },                                                                                                                                                                
                    {                                                                                                                                                                 
                        "avg_time": 1,                                                                                                                                                
                        "in_progress": 1,                                                                                                                                             
                        "job_type": "advanceLedger",                                                                                                                                  
                        "peak_time": 93,                                                                                                                                              
                        "per_second": 11                                                                                                                                              
                    },                                                                                                                                                                
                    {                                                                                                                                                                 
                        "avg_time": 9,                                                                                                                                                
                        "job_type": "fetchTxnData",                                                                                                                                   
                        "peak_time": 73,                                                                                                                                              
                        "per_second": 12                                                                                                                                              
                    },                                                                                                                                                                
                    {                                                                                                                                                                 
                        "avg_time": 19,                                                                                                                                               
                        "job_type": "trustedValidation",                                                                                                                              
                        "peak_time": 215,                                                                                                                                             
                        "per_second": 11                                                                                                                                              
                    },                                                                                                                                                                
                    {                                                                                                                                                                 
                        "avg_time": 39,                                                                                                                                               
                        "job_type": "trustedProposal",                                                                                                                                
                        "peak_time": 319,                                                                                                                                             
                        "per_second": 12                                                                                                                                              
                    },                                                                                                                                                                
                    {                                                                                                                                                                 
                        "job_type": "peerCommand",                                                                                                                                    
                        "peak_time": 3,                                                                                                                                               
                        "per_second": 819                                                                                                                                             
                    },                                                                                                                                                                
                    {                                                                                                                                                                 
                        "job_type": "processTransaction",                                                                                                                             
                        "per_second": 17                                                                                                                                              
                    },                                                                                                                                                                
                    {                                                                                                                                                                 
                        "job_type": "SyncReadNode",                                                                                                                                   
                        "peak_time": 6,                                                                                                                                               
                        "per_second": 1099                                                                                                                                            
                    },                                                                                                                                                                
                    {                                                                                                                                                                 
                        "job_type": "AsyncReadNode",                                                                                                                                  
                        "peak_time": 4,                                                                                                                                               
                        "per_second": 8844                                                                                                                                            
                    },                                                                                                                                                                
                    {                                                                                                                                                                 
                        "job_type": "WriteNode",                                                                                                                                      
                        "peak_time": 2,                                                                                                                                               
                        "per_second": 420                                                                                                                                             
                    }                                                                                                                                                                 
                ],                                                                                                                                                                    
                "threads": 6                                                                                                                                                          
            },                                                                                                                                                                        
            "load_factor": 529.40234375,                                                                                                                                              
            "load_factor_fee_escalation": 529.40234375,                                                                                                                               
            "load_factor_server": 1,                                                                                                                                                  
            "node_size": "tiny",                                                                                                                                                      
            "peer_disconnects": "39",                                                                                                                                                 
            "peer_disconnects_resources": "0",                                                                                                                                        
            "peers": 10,                                                                                                                                                              
            "pubkey_node": "n9MCJva9vzvb6Rqv62xjex1J3g8YwqJZLdcjFZnJ6FeFsLpG198H",                                                                                                    
            "pubkey_validator": "none",                                                                                                                                               
            "published_ledger": 75156434,                                                                                                                                             
            "server_state": "full",                                                                                                                                                   
            "server_state_duration_us": "253732691",                                                                                                                                  
            "state_accounting": {                                                                                                                                                     
                "connected": {                                                                                                                                                        
                    "duration_us": "970464485",                                                                                                                                       
                    "transitions": "179"                                                                                                                                              
                },                                                                                                                                                                    
                "disconnected": {                                                                                                                                                     
                    "duration_us": "1053519",                                                                                                                                         
                    "transitions": "2"                                                                                                                                                
                },                                                                                                                                                                    
                "full": {                                                                                                                                                             
                    "duration_us": "1812074131316",                                                                                                                                   
                    "transitions": "265"                                                                                                                                              
                },                                                                                                                                                                    
                "syncing": {                                                                                                                                                          
                    "duration_us": "113826422",                                                                                                                                       
                    "transitions": "90"                                                                                                                                               
                },                                                                                                                                                                    
                "tracking": {                                                                                                                                                         
                    "duration_us": "289075539",                                                                                                                                       
                    "transitions": "265"                                                                                                                                              
                }                                                                                                                                                                     
            },                                                                                                                                                                        
            "time": "2022-Oct-19 03:11:48.700315 UTC",                                                                                                                                
            "uptime": 1813448,                                                                                                                                                        
            "validated_ledger": {                                                                                                                                                     
                "age": 4,                                                                                                                                                             
                "base_fee_xrp": 1e-05,                                                                                                                                                
                "hash": "81452D261F9E60B4DA033E5159B9D1FDBF94ACEBBEB36E5FA29809804760E264",                                                                                           
                "reserve_base_xrp": 10,                                                                                                                                               
                "reserve_inc_xrp": 2,                                                                                                                                                 
                "seq": 75157038                                                                                                                                                       
            },                                                                                                                                                                        
            "validation_quorum": 28,                                                                                                                                                  
            "validator_list": {                                                                                                                                                       
                "count": 2,                                                                                                                                                           
                "expiration": "2023-Apr-04 00:00:00.000000000 UTC",                                                                                                                   
                "status": "active"                                                                                                                                                    
            }                                                                                                                                                                         
        },                                                                                                                                                                            
        "status": "success"                                                                                                                                                           
    }                                                                                                                                                                                 
}                                                                                                                                                                                     
[root@nwo-chain-node-ap26c ~]#                                                                                                                                                        
[root@nwo-chain-node-ap26c ~]#                                                                                                                                                        
[root@nwo-chain-node-ap26c ~]#                                                                                                                                                        
[root@nwo-chain-node-ap26c ~]#                                                                                                                                                        
[root@nwo-chain-node-ap26c ~]#                                                                                                                                                        
[root@nwo-chain-node-ap26c ~]# curl -X POST -H 'Content-Type: application/json' --data '{"method": "ledger", "params": [{"ledger_index": 75156434,"transactions": false,"expand":true}
]}' http://127.0.0.1:61076                                                                                                                                                            
                                                                                                                                                                                      
                                                                                                                                                                                      
                                                                                                                                                                                      
                                                                                                                                                                                      
{"result":{"ledger":{"accepted":true,"account_hash":"781B77715C347DD9F2A99DE724ED07951547562AB6AA561DCD50938BBA434211","close_flags":0,"close_time":719461971,"close_time_human":"2022
-Oct-19 02:32:51.000000000 UTC","close_time_resolution":10,"closed":true,"hash":"27FBEB026F2D624B7B5E1CC693CB879030268C9AB4FADA94A045D03B9925C224","ledger_hash":"27FBEB026F2D624B7B5E
1CC693CB879030268C9AB4FADA94A045D03B9925C224","ledger_index":"75156434","parent_close_time":719461970,"parent_hash":"AF545AE91C6FF7E3C60F5DDAA71CB25A5C0E9762BB7BA77A4D9CAAC5F1949040"
,"seqNum":"75156434","totalCoins":"99989245184412282","total_coins":"99989245184412282","transaction_hash":"691E5D0AAAD345D29774C5F7D6B0BF546C3853021E75E0D953736E5821BDBFBD"},"ledger
_hash":"27FBEB026F2D624B7B5E1CC693CB879030268C9AB4FADA94A045D03B9925C224","ledger_index":75156434,"status":"success","validated":true}}                                               
                                                                                                                                                                                      
[root@nwo-chain-node-ap26c ~]#                                                                                                                                                        
[root@nwo-chain-node-ap26c ~]#                                                                                                                                                        
[root@nwo-chain-node-ap26c ~]#                                                                                                                                                        
[root@nwo-chain-node-ap26c ~]#                                                                                                                                                        
[root@nwo-chain-node-ap26c ~]#                                                                                                                                                        
[root@nwo-chain-node-ap26c ~]#                                                                                                                                                        
[root@nwo-chain-node-ap26c ~]# curl -X POST -H 'Content-Type: application/json' --data '{"method": "ledger", "params": [{"ledger_index": 75156414,"transactions": false,"expand":true}
]}' http://127.0.0.1:61076                                                                                                                                                            
{"result":{"ledger":{"accepted":true,"account_hash":"76725603C5148DF126755434E037DBE45C6ED9536093C90E18AA157FBCCF19A6","close_flags":0,"close_time":719461892,"close_time_human":"2022
-Oct-19 02:31:32.000000000 UTC","close_time_resolution":10,"closed":true,"hash":"3162A7431476E3BED5B66F5701AAA0A93EFE3F7A4E517E8F5E21093B9EB9A360","ledger_hash":"3162A7431476E3BED5B6
6F5701AAA0A93EFE3F7A4E517E8F5E21093B9EB9A360","ledger_index":"75156414","parent_close_time":719461891,"parent_hash":"B1C5A755B73FB84FF6DD302CC874D1BEAB6F46B682D6C685F1DF726279BB039A"
,"seqNum":"75156414","totalCoins":"99989245185528627","total_coins":"99989245185528627","transaction_hash":"45241447C86EB5B313CC7A577DB1B921C820B6016890225C793F5E0AABAB18C2"},"ledger
_hash":"3162A7431476E3BED5B66F5701AAA0A93EFE3F7A4E517E8F5E21093B9EB9A360","ledger_index":75156414,"status":"success","validated":true}}                                               
                                                                                                                                                                                      
[root@nwo-chain-node-ap26c ~]# curl -X POST -H 'Content-Type: application/json' --data '{"method": "ledger", "params": [{"ledger_index": 75156444,"transactions": false,"expand":true}
]}' http://127.0.0.1:61076                                                                                                                                                            
{"result":{"error":"lgrNotFound","error_code":21,"error_message":"ledgerNotFound","request":{"command":"ledger","expand":true,"ledger_index":75156444,"transactions":false},"status":"
error"}}                                                                                                                                                                              
                                                                                                                                                                                      
[root@nwo-chain-node-ap26c ~]# curl -X POST -H 'Content-Type: application/json' --data '{"method": "ledger", "params": [{"ledger_index":75157064,"transactions": false,"expand":true}]
}' http://127.0.0.1:61076                                                                                                                                                             
{"result":{"ledger":{"accepted":true,"account_hash":"FF3C221D643BA07A3FD3BA4CC31DE49E9ACEF19E6191EC1573194829B43BA9A9","close_flags":0,"close_time":719464401,"close_time_human":"2022
-Oct-19 03:13:21.000000000 UTC","close_time_resolution":10,"closed":true,"hash":"A24A85B2E3BC5CD1CE6F663B678F086FCADEA76BE0396C262286C1EB79EB5CA5","ledger_hash":"A24A85B2E3BC5CD1CE6F
663B678F086FCADEA76BE0396C262286C1EB79EB5CA5","ledger_index":"75157064","parent_close_time":719464400,"parent_hash":"0EEED45C95932B807B47168B5304FB1DFE5F8ADBAFE07D5DE00A68D9DABC5304"
,"seqNum":"75157064","totalCoins":"99989245158445635","total_coins":"99989245158445635","transaction_hash":"59F37FB4D04AB20C2E7525D02667879884FC75C6E4426CBE714B93CCEB1E9AE8"},"ledger
_hash":"A24A85B2E3BC5CD1CE6F663B678F086FCADEA76BE0396C262286C1EB79EB5CA5","ledger_index":75157064,"status":"success","validated":true}}

**Comment by 1143857824** [comment]
Hello  @MarkusTeufelberger  
We found that this "complete_leaders" has multiple ranges. Blocks can be obtained within the scope. But blocks outside the scope cannot be accessed. This is why. And can we avoid this problem?

![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/57594569/196890906-bac54e07-0b7a-4231-a92c-0ef7fdf7d9b2.png)
![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/57594569/196891759-c749d987-9302-4bb4-afa8-036bda066850.png)

**Comment by intelliot** [comment]
Find more info about handling ledger gaps here: https://xrpl.org/diagnosing-problems.html#get-the-server_info
