### ISSUE TITLE
api not available

### ISSUE THREAD

**Issue by COLUD4** [XRPLF/rippled#4334]
![截屏2022-11-03 18 02 43](https://user-images.githubusercontent.com/21240219/199693222-b4e89b77-5bae-4e3f-9b7b-cc31a00c5f5a.png)

**Comment by MarkusTeufelberger** [comment]
Your request is cut off in that picture...

**Comment by COLUD4** [comment]
![截屏2022-11-03 18 42 06](https://user-images.githubusercontent.com/21240219/199700841-8230c863-0b02-4511-b858-312314b660ab.png)

**Comment by COLUD4** [comment]
> Your request is cut off in that picture...
curl -s -X GET http://127.0.0.1:5005

**Comment by COLUD4** [comment]
> Your request is cut off in that picture...

./rippled --conf=/mnt/xrpmain/core/opt/ripple/etc/rippled.cfg

**Comment by MarkusTeufelberger** [comment]
What would you expect as a response from this (empty) API call? Please consult the documentation about what API calls are actually available and how to use them, I don't see anything that points to an issue in your picture.

**Comment by COLUD4** [comment]
> What would you expect as a response from this (empty) API call? Please consult the documentation about what API calls are actually available and how to use them, I don't see anything that points to an issue in your picture.
![截屏2022-11-03 18 49 30](https://user-images.githubusercontent.com/21240219/199702163-fd8765fa-d2c0-415c-9400-d5cca155312d.png)

**Comment by COLUD4** [comment]
> > What would you expect as a response from this (empty) API call? Please consult the documentation about what API calls are actually available and how to use them, I don't see anything that points to an issue in your picture.
> > ![截屏2022-11-03 18 49 30](https://user-images.githubusercontent.com/21240219/199702163-fd8765fa-d2c0-415c-9400-d5cca155312d.png)


![截屏2022-11-03 18 53 45](https://user-images.githubusercontent.com/21240219/199703084-b58db1e3-5ed9-4521-8e26-764f6593a482.png)

**Comment by COLUD4** [comment]
curl -H 'Content-Type: application/json' -d '{"id":1, "jsonrpc":"2.0", "method": "tx_history", "params":[{"start":0}]}' http://127.0.0.1:5005
This gives access to information

**Comment by MarkusTeufelberger** [comment]
Ah, you found out already, good job! :-)
