### ISSUE TITLE
Mac error: no member named 'comp' in boost::intrusive

### ISSUE THREAD

**Issue by stevebanik** [XRPLF/rippled#4344]
Consolidate compiler generated dependencies of target rippled
[ 79%] Building CXX object CMakeFiles/rippled.dir/Unity/unity_23_cxx.cxx.o
[ 79%] Building CXX object CMakeFiles/rippled.dir/Unity/unity_21_cxx.cxx.o
[ 79%] Building CXX object CMakeFiles/rippled.dir/Unity/unity_20_cxx.cxx.o
[ 79%] Building CXX object CMakeFiles/rippled.dir/Unity/unity_19_cxx.cxx.o
In file included from /Users/newuser/git/rippled/my_build/CMakeFiles/rippled.dir/Unity/unity_23_cxx.cxx:25:
In file included from /Users/newuser/git/rippled/src/test/beast/aged_associative_container_test.cpp:23:
In file included from /Users/newuser/git/rippled/src/ripple/beast/container/aged_map.h:23:
/Users/newuser/git/rippled/src/ripple/beast/container/detail/aged_ordered_container.h:1435:53: error: no member named 'comp' in 'boost::intrusive::set_impl<boost::intrusive::bhtraits<beast::detail::aged_ordered_container<false, false, std::__1::basic_string<char>, void, std::__1::chrono::steady_clock, std::__1::less<std::__1::basic_string<char>>, std::__1::allocator<std::__1::basic_string<char>>>::element, boost::intrusive::rbtree_node_traits<void *, false>, boost::intrusive::normal_link, boost::intrusive::dft_tag, 3>, void, beast::detail::aged_ordered_container<false, false, std::__1::basic_string<char>, void, std::__1::chrono::steady_clock, std::__1::less<std::__1::basic_string<char>>, std::__1::allocator<std::__1::basic_string<char>>>::KeyValueCompare, unsigned long, true, void>'
    : m_config(other.m_config), m_cont(other.m_cont.comp())
                                       ~~~~~~~~~~~~ ^
/Users/newuser/git/rippled/src/test/beast/aged_associative_container_test.cpp:738:22: note: in instantiation of member function 'beast::detail::aged_ordered_container<false, false, std::__1::basic_string<char>, void, std::__1::chrono::steady_clock, std::__1::less<std::__1::basic_string<char>>, std::__1::allocator<std::__1::basic_string<char>>>::aged_ordered_container' requested here
    checkMapContents(c, v);
                     ^
/Users/newuser/git/rippled/src/test/beast/aged_associative_container_test.cpp:750:5: note: in instantiation of function template specialization 'beast::aged_associative_container_test_base::checkContents<beast::detail::aged_ordered_container<false, false, std::__1::basic_string<char>, void, std::__1::chrono::steady_clock, std::__1::less<std::__1::basic_string<char>>, std::__1::allocator<std::__1::basic_string<char>>>, std::__1::vector<std::__1::basic_string<char>>>' requested here
    checkContents(c, Values());
    ^
/Users/newuser/git/rippled/src/test/beast/aged_associative_container_test.cpp:780:9: note: in instantiation of function template specialization 'beast::aged_associative_container_test_base::checkContents<beast::detail::aged_ordered_container<false, false, std::__1::basic_string<char>, void, std::__1::chrono::steady_clock, std::__1::less<std::__1::basic_string<char>>, std::__1::allocator<std::__1::basic_string<char>>>>' requested here
        checkContents(c);
        ^
/Users/newuser/git/rippled/src/test/beast/aged_associative_container_test.cpp:1838:5: note: in instantiation of function template specialization 'beast::aged_associative_container_test_base::testConstructEmpty<false, false, false>' requested here
    testConstructEmpty<IsUnordered, IsMulti, IsMap>();
    ^
/Users/newuser/git/rippled/src/test/beast/aged_associative_container_test.cpp:1914:9: note: in instantiation of function template specialization 'beast::aged_associative_container_test_base::testMaybeUnorderedMultiMap<false, false, false>' requested here
        testMaybeUnorderedMultiMap<false, false, false>();

**Comment by stevebanik** [comment]
Following instructions at https://xrpl.org/build-run-rippled-macos.html

**Comment by stevebanik** [comment]
Steps leading to error:

  888  ./bootstrap.sh
  889  echo $0
  890    echo "export BOOST_ROOT=/Users/my_user/boost_1_75_0" >> ~/.zshrc\n
  891  source ~/.zshrc\n
  892  cd ~/git
  893  git clone https://github.com/ripple/rippled.git\ncd rippled
  894  git checkout master
  895  git log -1
  896  mkdir my_build
  897  cd my_build
  898  cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug ..

**Comment by scottschurr** [comment]
Is it possible that you're not using boost 1.75?  The most recent beta build of rippled has the following commit:

https://github.com/XRPLF/rippled/commit/04ef8851081f6ee9176783ad3725960b8a931ebb

It fixes a problem that looks surprisingly like the problem you are describing.  I hope that helps.

**Comment by intelliot** [comment]
The new build instructions can be found here: https://github.com/XRPLF/rippled/blob/develop/BUILD.md
