### ISSUE TITLE
account_objects method does not return NFTokenPages (Version: 1.9.4)

### ISSUE THREAD

**Issue by nixer89** [XRPLF/rippled#4347]
## Issue Description
When trying to get an xrpl accounts owned objects, the method `account_objects` does not return NFTokenPage(s). This is a problem because one could not reliably show the user which objects currently count towards his owner reserve.

The documentation also states:
`The account_objects command returns the raw [ledger format](https://xrpl.org/ledger-object-types.html) for all objects owned by an account.`

## Steps to Reproduce
1. call the `account_objects` method of an account which owns some NFTs
2. response does not include any NFTokenPage

## Expected Result
Also NFTokenPages are returned through the `account_objects` method.

## Actual Result
No NFTokenPage is returned

This is actually quite a problem. On accounts with NFTs, the OwnerCount of the AccountRoot objects shows a bigger number than objects are returned by the `account_objects` method. This confuses developers as well as users.

**Comment by RichardAH** [comment]
Here is a code solution: https://github.com/RichardAH/rippled/tree/nftpage_accobjs

I have tested by hand but it needs unit tests to go in. If someone wants to provide those then we can PR it.

**Comment by scottschurr** [comment]
The top-most commit here adds unit tests and fixes a couple of bugs in corner cases:

https://github.com/scottschurr/rippled/commits/RichardAH-nftpage_accobjs

You're welcome to cherry-pick the commit if you would like.

**Comment by cjcobb23** [comment]
Why can't this just be done client side?

**Comment by RichardAH** [comment]
> The top-most commit here adds unit tests and fixes a couple of bugs in corner cases:
> 
> https://github.com/scottschurr/rippled/commits/RichardAH-nftpage_accobjs
> 
> You're welcome to cherry-pick the commit if you would like.

Thanks! will do today!



> Why can't this just be done client side?

I actually have a client side solution. It is very hacky indeed. Curious to see if you can figure out what it is before I share it
