### ISSUE TITLE
The build

### ISSUE THREAD

**Issue by 0x34d** [XRPLF/rippled#4366]
In  `Nudb.cmake`  what is the meaning of `NuDB not needed in the case of xrpl_core inclusion build`.

How can I Disable NuDB while building?

**Comment by ximinez** [comment]
For reference, the line is https://github.com/XRPLF/rippled/blob/develop/Builds/CMake/deps/Nudb.cmake#L9

It is intended to prevent unnecessary builds of NuDB in configurations where `rippled` is used as a dependency to another project. An example is in https://github.com/ripple/validator-keys-tool/blob/master/CMakeLists.txt#L21-L66

**Comment by legleux** [comment]
The closest to your last question will be provided by using [Conan](https://docs.conan.io/en/latest/) to provide dependencies https://github.com/XRPLF/rippled/pull/4223
