### ISSUE TITLE
Number class shows degradation in math operations performance.

### ISSUE THREAD

**Issue by gregtatcam** [XRPLF/rippled#4368]
## Issue Description
Number class shows degradation in math operations performance as compared to similar operations 
implemented in STAmount.

## Steps to Reproduce
Here is a simple unit test, which demonstrates the issue:

>    
    void
    testSwap1()
    {
        testcase("Swap1");
        using namespace jtx;

        std::uint16_t tfee = 1000;
        auto const gw = Account("gw");
        auto const USD = gw["USD"];
        auto const GBP = gw["GBP"];
        auto const issueIn = USD;
        auto const issueOut = GBP;
        auto const in = STAmount{USD, 1000};
        auto const out = STAmount{GBP, 1000};
        auto const assetIn = STAmount{USD, 1};
        auto const assetOut = STAmount{GBP, 1};

        auto start = std::chrono::high_resolution_clock::now();
        for (int i = 0; i < 100; ++i)
        {
            auto const fm = 1 - Number{tfee} / 100000;
            auto const res = in - (in * out) / (in + assetIn * fm);
        }
        auto elapsed = std::chrono::high_resolution_clock::now() - start;
        std::cout << "Number(swapIn) math: " << std::chrono::duration_cast<std::chrono::microseconds>(
                                            elapsed).count() << std::endl;

        start = std::chrono::high_resolution_clock::now();
        for (int i = 0; i < 100; ++i)
        {
            auto const n1 = STAmount{1};
            auto const feeMult = n1 - divide(STAmount{tfee}, STAmount{100000}, n1.issue());
            auto const en = multiply(in, out, issueOut);
            auto const den = in + multiply(assetIn, feeMult, issueIn);
            auto const res = out - divide(en, den, issueOut);
        }
        elapsed = std::chrono::high_resolution_clock::now() - start;
        std::cout << "STAmount(swapIn) math: " << std::chrono::duration_cast<std::chrono::microseconds>(
            elapsed).count() << std::endl;
        BEAST_EXPECT(true);
    }

## Expected Result
Math operations using Number and STAmount function should produce similar results.

## Actual Result
The issue manifested itself in the payment engine updated for AMM. Swap in formula used
to figure out initial AMM offer size resulted in the throughput degradation.

## Environment
The benchmark test ran on 11 "Ubuntu 20.04.4 LTS" servers (five validators, four clients, two signing) in AWS.
The unit test ran on OSX Ventura.
AMM PR was used to build rippled: https://github.com/XRPLF/rippled/pull/4294

**Comment by HowardHinnant** [comment]
I believe this commit fully addresses this issue: https://github.com/XRPLF/rippled/pull/4192/commits/16f1057d2ab951204d7c0c4564620caf78273491

This commit is part of the NumberMerge PR: https://github.com/XRPLF/rippled/pull/4192

**Comment by intelliot** [comment]
Fixed by https://github.com/XRPLF/rippled/commit/16f1057d2ab951204d7c0c4564620caf78273491
