### ISSUE TITLE
rippled software package (Version: 1.10.0)

### ISSUE THREAD

**Issue by gitmewai** [XRPLF/rippled#4466]
## Issue Description
Is rippled `1.10.0` compiled by Ripple available in Ripple repository yet for node software upgrade?

## Steps to Reproduce
```
apt update
apt list rippled -a
```

## Expected Result
Version `1.10.0` or later should be available for upgrade

## Actual Result
```
root@ripple-1:~$ date ; apt update
Mon Mar 20 06:51:03 UTC 2023
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 http://cdn-aws.deb.debian.org/debian buster InRelease                    
Hit:3 http://cdn-aws.deb.debian.org/debian buster-updates InRelease            
Hit:4 http://cdn-aws.deb.debian.org/debian buster-backports InRelease          
Hit:5 https://repos.ripple.com/repos/rippled-deb buster InRelease              
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
root@ripple-1:~$ date ; apt list rippled -a
Mon Mar 20 06:51:07 UTC 2023
Listing... Done
rippled/buster,now 1.9.4-1 amd64 [installed]
rippled/buster 1.9.3-1 amd64
rippled/buster 1.9.2-1 amd64
rippled/buster 1.9.1-1 amd64
rippled/buster 1.8.5-1 amd64
rippled/buster 1.8.4-1 amd64
rippled/buster 1.8.1-1 amd64
rippled/buster 1.7.3-1 amd64
rippled/buster 1.7.2-1 amd64
rippled/buster 1.7.0-1 amd64
rippled/buster 1.6.0-1 amd64
rippled/buster 1.5.0-1 amd64
rippled/buster 1.4.0-1 amd64
rippled/buster 1.3.1-1 amd64
rippled/buster 1.3.0-1 amd64
```

## Environment
```
root@ripple-1:~$ cat /etc/debian_version 
10.13
root@ripple-1:~$ uname -a
Linux ripple-1 4.19.0-23-cloud-amd64 #1 SMP Debian 4.19.269-1 (2022-12-20) x86_64 GNU/Linux
```

**Comment by gitmewai** [comment]
@legleux BTW, I tried to follow the [Release Notes v1.10.0](https://xrpl.org/blog/2023/rippled-1.10.0.html) to install the debian package manually.

However, the following was reported:
```
Dependency is not satisfiable: libc6 (>= 2.30)
```

Is `Debian 10 Buster` still a supported platform as documented in [Install on Ubuntu or Debian Linux](https://xrpl.org/install-rippled-on-ubuntu.html)? This is because `libc6 (>= 2.30)` should be unavailable on `Debian 10`.

Thanks.

**Comment by legleux** [comment]
This is being addressed right now in https://github.com/XRPLF/rippled/pull/4468 actually.
The package has been tested on Debian 10 Buster.
Debian 9 will not work due to a similar `libc6` dependency.

**Comment by AllenLiuxt** [comment]
I have the same problem unable to upgrade on Ubuntu 20.04. Please let me know how to resolve

**Comment by intelliot** [comment]
1.9.4 should continue to work until the activation of an amendment that it does not understand.

- Find details about [Known Amendments here](https://xrpl.org/known-amendments.html).
- When an amendment reaches majority vote, there is a [two week waiting period](https://xrpl.org/amendments.html) before activation.

At the time of this writing, [no 1.10 amendments have reached majority](https://xrpscan.com/amendments), so 1.9.4 should continue to work for at least 2 more weeks (and most likely much longer, depending on how validators vote).
