### ISSUE TITLE
[Submit transaction exception] (Version: [1.10.0])

### ISSUE THREAD

**Issue by xiongjiabing** [XRPLF/rippled#4492]
hi,a batch of transactions is abnormal, what causes this? pls have a look,thanks
{
	"result": {
		"error_message": "Current ledger is unavailable.",
		"request": {
			"tx_blob": "120000228000000024000000002e717a8935201b04b4e17c614000000003c8030b684000000000000bb8732102750f6e5c9beda0b47748ccb0bb3013d7fb48443c6a6420405ab2bc578a22b8dc74473045022100c736d455c558a54aae071b1c103bf94fb2607dc0657e5593cedacef879189e600220390cd9d9e1ef4b37e9552d6b544dded2aa9d37b0af94cef4d269f0b77187a29c811490c0496bcf56cd8033b099e0a5c1fd80557c515f831497a929da8ff7788f2cbdae5360d7e094ac9c48f6",
			"command": "submit"
		},
		"error_code": 16,
		"error": "noCurrent",
		"status": "error"
	}
}

**Comment by xiongjiabing** [comment]
Another transaction exception

{
	"result": {
		"error_message": "Not synced to the network.",
		"request": {
			"tx_blob": "120000228000000024043db37d2e0011384a201b04b51443614000000001c6b640684000000000000bb8732103b89acf054bfcba99fd26dffba2ee60f851e0946e9989b3d870de687525c366e474473045022100a5f5f3ec7c1348c1306a6802e431471236ad9cd59c9b7039db38e6598f52f7e8022058411e946ec212273022e636fb1471f08b5ae2e2f227c08c80ded3929413e5c081147781c9a4611ad925ef9298b0c9e0e025803fb8bf831435c8e11255e2b43b3a78476919ffc0eacfc0733a",
			"command": "submit"
		},
		"error_code": 17,
		"error": "noNetwork",
		"status": "error"
	}
}

**Comment by xiongjiabing** [comment]
so, do these errors mean that the transaction is unlikely to succeed?

**Comment by xiongjiabing** [comment]
hi any update, hahahhaha

**Comment by ximinez** [comment]
It is normal for a well-behaved server to occasionally fall out of sync. It usually recovers within a few seconds. Any transactions submitted during that time will likely need to be resubmitted. For more information, see https://xrpl.org/reliable-transaction-submission.html

If your node is consistently having trouble syncing, frequently falling out of sync, or having trouble resyncing, see https://xrpl.org/server-doesnt-sync.html
