### ISSUE TITLE
[ripple archive snapshot] (Version: [1.10.1])

### ISSUE THREAD

**Issue by jannes-stubbemann-20230331** [XRPLF/rippled#4497]
## Summary
We want to run an archive node and are looking for a way to speed up the initial sync

## Motivation
according to the doc, it could take months without

## Solution
provide some mirror that we can use to download the latest archive snapshot

## Paths Not Taken
Sync from scratch

**Comment by MarkusTeufelberger** [comment]
If you take a snapshot from someone else you need to make really really sure that you only import actually correct data into your node. I'm not sure if `rippled` does more verification these days when importing node databases (or shards).

While I have a few ideas how this can be done in a bit more distributed and still safe way and will eventually get to that, for now I don't know of any public mirrors of such data. Your best bet as of today would be to get in contact with people like @WietseWind who operate archive nodes and directly peer with them and/or discuss some ways to transfer the data more directly.

**Comment by jannes-stubbemann-20230331** [comment]
@MarkusTeufelberger thank you very much! I'll reach out to @WietseWind :-)

**Comment by WietseWind** [comment]
I'm sorry, I currently don't have the bandwidth (time, not actual packets over the internet :P) to take down a machine and provide a snapshot. Looping in @jscottbranson who might?

**Comment by jscottbranson** [comment]
I'm closing this, as it doesn't pertain to core rippled.
