### ISSUE TITLE
[transaction error] (Version: [1.10.0])

### ISSUE THREAD

**Issue by xiongjiabing** [XRPLF/rippled#4506]
hi , Why did this transaction fail?

{
	"result": {
		"broadcast": false,
		"account_sequence_available": 76286785,
		"applied": false,
		"open_ledger_cost": "10",
		"tx_json": {
			"Account": "r3ZVNKgkkT3A7hbEZ8HxnNnLDCCmZiZECV",
			"Destination": "r3ZVNKgkkT3A7hbEZ8HxnNnLDCCmZiZECV",
			"TransactionType": "Payment",
			"TxnSignature": "304402201D6295BF45BCDA7FAEE3912E90E830EC67F337A6EDC5FE6BB487EBAE784431DC02204CB445FDA7A3E23CE1C5B6732A8CA1B555581D353307CAA76879F3242B782B69",
			"SigningPubKey": "025745B6B80BAE86D6A83979B378D033105C7D2CA7EAACF6984F4011416B913733",
			"Amount": "24000000",
			"Fee": "3000",
			"Flags": 2147483648,
			"Sequence": 76286785,
			"LastLedgerSequence": 79245689,
			"hash": "17DA72F004FECA1B63C5B1E4499C132EBD90061CDD86E04867208629CB071452"
		},
		"queued": false,
		"engine_result_code": -275,
		"accepted": true,
		"kept": true,
		"validated_ledger_index": 79245674,
		"tx_blob": "120000228000000024048C0B41201B04B931796140000000016E3600684000000000000BB87321025745B6B80BAE86D6A83979B378D033105C7D2CA7EAACF6984F4011416B9137337446304402201D6295BF45BCDA7FAEE3912E90E830EC67F337A6EDC5FE6BB487EBAE784431DC02204CB445FDA7A3E23CE1C5B6732A8CA1B555581D353307CAA76879F3242B782B69811452EDC197E96436FBF1A84DDAE4B1A8370767F31F831452EDC197E96436FBF1A84DDAE4B1A8370767F31F",
		"engine_result": "temREDUNDANT",
		"account_sequence_next": 76286785,
		"engine_result_message": "The transaction is redundant.",
		"status": "success"
	}
}

**Comment by Silkjaer** [comment]
The sender and recipient of the payment transaction is the same.

**Comment by xiongjiabing** [comment]
thanks a lot
