### ISSUE TITLE
[transaction error] (Version: [1.10.0])

### ISSUE THREAD

**Issue by xiongjiabing** [XRPLF/rippled#4518]
hi team, Why did the transaction fail? this seems to indicate that the sender account does not have permission. there have been several such cases. Surprisingly

{
    "result": {
        "Account": "rNU4eAowPuixS5ZCWaRL72UUeKgxcKExpK",
        "Amount": "149800000",
        "Destination": "rDUHL5KwoY3WkGMVmDs9ixd8581WGabUpj",
        "Fee": "3000",
        "Flags": 2147483648,
        "LastLedgerSequence": 79592272,
        "Sequence": 71143765,
        "SigningPubKey": "02750F6E5C9BEDA0B47748CCB0BB3013D7FB48443C6A6420405AB2BC578A22B8DC",
        "TransactionType": "Payment",
        "TxnSignature": "3045022100EC00D1DB1E68D52973EC6DDE9D37D1BBA442B564A1BBE89C931C4FB339DDE49E02200E422B795B330DCB3D258CF9729DA52DBA3D76CFC22F92B3D5C0C039E7937997",
        "date": 736697360,
        "hash": "479D342E6744349D0219385F475C4982281A0699DBC05B4B8D2019BF4C01CC0D",
        "inLedger": 79592259,
        "ledger_index": 79592259,
        "meta": {
            "AffectedNodes": [
                {
                    "ModifiedNode": {
                        "FinalFields": {
                            "Account": "rNU4eAowPuixS5ZCWaRL72UUeKgxcKExpK",
                            "Balance": "25043173104904",
                            "Flags": 0,
                            "OwnerCount": 0,
                            "Sequence": 71143766
                        },
                        "LedgerEntryType": "AccountRoot",
                        "LedgerIndex": "E7B758A5AA94C796D2FF06B280EFB516A7FDB645A7690A81C82ED2DD81C2EE64",
                        "PreviousFields": {
                            "Balance": "25043173107904",
                            "Sequence": 71143765
                        },
                        "PreviousTxnID": "BEF264E828199552E092B394F0946E7B79BF372F81ADCE2D123FF61DBB1C7F59",
                        "PreviousTxnLgrSeq": 79592249
                    }
                }
            ],
            "TransactionIndex": 43,
            "TransactionResult": "tecNO_PERMISSION"
        },
        "status": "success",
        "validated": true
    }
}

**Comment by dangell7** [comment]
@xiongjiabing You will receive a much faster response if you use the developer discord. Here is an invite link.

https://discord.com/invite/sfX3ERAMjH

**Comment by xiongjiabing** [comment]
https://discord.com/invite/sfX3ERAMjH
thanks hahah, but my account has been disabled

**Comment by intelliot** [comment]
You can learn about the transaction result here: https://xrpl.org/tec-codes.html

**Comment by xiongjiabing** [comment]
hi ,I think that's the problem
"or a payment tried to deliver funds to an account with the DepositAuth flag enabled."   how can the user deposit successfully?  what does the user need to do with the account?
