### ISSUE TITLE
Messages for closed path_find requests keep being sent (Version: 1.10.1)

### ISSUE THREAD

**Issue by elmurci** [XRPLF/rippled#4525]
## Issue Description

Messages for closed `path_find` requests keep being sent to subscriber.

## Steps to Reproduce

(I am testing on a private network, `"build_version": "1.10.1"`)

Create a `path_find` request:

```
{
  "id": "id_path_finding_HNL",
  "command": "path_find",
  "subcommand": "create",
  "source_account": "rDUc5SVH9fChauaf9ak3MZEb98FKBRjXk4",
  "destination_account": "rzGMYEcDVFXKSKZz2DCKNzbiUjo2DMtCZ",
  "destination_amount": {
    "value": "10",
    "currency": "HNL",
    "issuer": "ra1mvmgxFmrkPy16frXajSvGvC9EakQNEB"
  }
}
```

The request is successful, and I start receiving path updates.

If I close the request:

```
{
    "command": "path_find",
    "subcommand": "close"
}
```

The request works fine, and, if I check the status, I get the expected response:

```
{
    "error": "noPathRequest",
    "error_code": 33,
    "error_message": "No pathfinding request in progress.",
    "request": {
        "command": "path_find",
        "id": {
            "_WsClient": 205
        },
        "subcommand": "status"
    },
    "status": "error",
    "type": false
}
```

Now I create a new request with different parameters:

```
{
  "id": "id_path_finding_USD",
  "command": "path_find",
  "subcommand": "create",
  "source_account": "rDUc5SVH9fChauaf9ak3MZEb98FKBRjXk4",
  "destination_account": "rzGMYEcDVFXKSKZz2DCKNzbiUjo2DMtCZ",
  "destination_amount": {
    "value": "10",
    "currency": "USD",
    "issuer": "rMUzVS5nLtmQ7st9674tSXU4SeLDeuHAwi"
  }
}
```

And start receiving messages on my subscription for this new request.

However, I now get messages for both requests (the closed and the new one).
The closed one returns an empty `alternatives` array:

```
{
    "id": "id_path_finding_HNL",
    "result": {
        "alternatives": [],
        "destination_account": "rzGMYEcDVFXKSKZz2DCKNzbiUjo2DMtCZ",
        "destination_amount": {
            "currency": "HNL",
            "issuer": "ra1mvmgxFmrkPy16frXajSvGvC9EakQNEB",
            "value": "10"
        },
        "full_reply": false,
        "id": {
            "_Request": "id_path_finding_HNL",
            "_WsClient": 9
        },
        "source_account": "rDUc5SVH9fChauaf9ak3MZEb98FKBRjXk4"
    },
    "status": "success",
    "type": true
}
```

 And the new one returns a normal response with the expected paths:
 
 ```
 {
    "id": "id_path_finding_USD",
    "result": {
        "alternatives": [
            {
                "paths_computed": [
                    [
                        {
                            "account": "rKmW3KYdw4XXLdRNtfJKX4PPpP5oWJJMwt",
                            "type": 1
                        },
                        {
                            "currency": "USD",
                            "issuer": "rMUzVS5nLtmQ7st9674tSXU4SeLDeuHAwi",
                            "type": 48
                        }
                    ]
                ],
                "source_amount": {
                    "currency": "EUR",
                    "issuer": "rDUc5SVH9fChauaf9ak3MZEb98FKBRjXk4",
                    "value": "9.21"
                }
            },
            {
                "paths_computed": [
                    [
                        {
                            "account": "rf7x9p53vdNkKVEXaRPHTTFFxnD798Y1gw",
                            "type": 1
                        },
                        {
                            "currency": "USD",
                            "issuer": "rMUzVS5nLtmQ7st9674tSXU4SeLDeuHAwi",
                            "type": 48
                        }
                    ]
                ],
                "source_amount": {
                    "currency": "HUF",
                    "issuer": "rDUc5SVH9fChauaf9ak3MZEb98FKBRjXk4",
                    "value": "3571.428571"
                }
            }
        ],
        "destination_account": "rzGMYEcDVFXKSKZz2DCKNzbiUjo2DMtCZ",
        "destination_amount": {
            "currency": "USD",
            "issuer": "rMUzVS5nLtmQ7st9674tSXU4SeLDeuHAwi",
            "value": "10"
        },
        "full_reply": false,
        "id": {
            "_Request": "id_path_finding_USD",
            "_WsClient": 45
        },
        "source_account": "rDUc5SVH9fChauaf9ak3MZEb98FKBRjXk4"
    },
    "status": "success",
    "type": true
}
```

## Expected Result

I expect not to receive messages for old (closed) `path_find` requests.

## Actual Result

Messages for closed `path_find` requests are sent to subscriber.

**Comment by ximinez** [comment]
I haven't tried reproducing this at all, but try including the request ID on both your `close` and `status` requests.
```
{
  "id": "id_path_finding_HNL",
  "command": "path_find",
  "subcommand": "close"
}
```

**Comment by elmurci** [comment]
@ximinez, adding the `id` doesn't change the behaviour.

Thanks

**Comment by ChronusZ** [comment]
I was unable to reproduce in my own testing environment, also running 1.10.1. I first tried it with arbitrarily different accounts for the two requests; then I thought maybe the fact that your requests have the same source and destination but different destination currency was important so I tried replicating that. Neither approach showed the unexpected behavior.

@elmurci is there a script you use to set up your websocket connection and submit these requests? I can try copying it (with different accounts) and see if it causes the issue to crop up in my environment.

**Comment by elmurci** [comment]
@ChronusZ I have done some more investigations on this one.

It seems like an issue with the [client](https://github.com/XRPL-Labs/xrpl-client) I am using.
It persists an array of subscriptions for its processing in the event of connection loss. The problem was it doesn't remove the old `path_fins` `create` request after closing them.

So... it executes every step after reconnection:

1. `path_find` - `create` (1)
2. `path_find` - `close` (1)
3. `path_find` - `create` (2)

Paths for just (2) are eventually received, but there is always a couple of paths received for (1) (between `path_find` (1) creation and closure).

I am closing this issue.

Thanks for your help!
