### ISSUE TITLE
Transfer non-transferable NFTs to the issuer

### ISSUE THREAD

**Issue by develoQ** [XRPLF/rippled#4529]
## Issue Description
When a holder transfers a non-transferable NFT to the issuer, it works correctly if the issuer creates the offer and the holder accept, but if the holder creates the offer to the issuer, it results in a `tefNFTOKEN_IS_NOT_TRANSFERABLE` error.

## Steps to Reproduce
1. Account1 issues NFT by `NFTokenMint`. The `tfTransferable` flag is not set.
2. Account1 transfers NFTs to Account2 by `NFTokenCreateOffer` and `NFTokenAcceptOffer`.
3. Account2 sends `NFTokenCreateOffer` with Account1 as Destination

## Expected Result
For non-transferable NFTs, `NFTokenCreateOffer` to the issuer should be allowed.

## Actual Result
we get the `tefNFTOKEN_IS_NOT_TRANSFERABLE` error.

## Environment
XRPL Testnet 1.10.1(wss://testnet.xrpl-labs.com)

## Supporting Files
Reproduced code using xrpl.js
https://gist.github.com/develoQ/c8a58fcea7abdcbe636509a8ad89b1e6

**Comment by kennyzlei** [comment]
@develoQ we will take a look at this issue soon, have you been able to also reproduce this on the XRPL Testnet (wss://s.altnet.rippletest.net:51233/) vs. the XRPL Labs Testnet (wss://testnet.xrpl-labs.com)?

https://xrpl.org/xrp-testnet-faucet.html

**Comment by develoQ** [comment]
I'm getting `tefNFTOKEN_IS_NOT_TRANSFERABLE` in both `wss://s.altnet.rippletest.net:51233/` and `wss://testnet.xrpl-labs.com`.

**Comment by intelliot** [comment]
> it works correctly if the issuer creates the offer and the holder accept

Is that an acceptable workaround?

The issuer needs to either create (or accept) an offer anyway, so it shouldn't be a problem to have the issuer create the offer.

**Comment by develoQ** [comment]
>Is that an acceptable workaround?

If my point is that it is a specification, that is fine, but the documentation needs to say that it is a specification.

If there is no mention of it, then future developers will feel that they can trade with the issuer regardless of which side CreateOffer is coming from.

**Comment by kennyzlei** [comment]
@develoQ as next steps, we will work on updating the documentation of the `tfTransferable` flag behavior to specify more explicitly what type of transfer can happen.  after the documentation updates, let's keep an eye out and if this continues to create confusion and is run into often, we can reevaluate the need for a code change on the transfer behavior here

**Comment by kennyzlei** [comment]
@develoQ the documentation has been updated with https://github.com/XRPLF/xrpl-dev-portal/pull/2110  it took a bit longer than expected due to some changes to xrpl-dev-portal that was blocking this pr to go through
