### ISSUE TITLE
Possible transaction breaking change outside of an amendment

### ISSUE THREAD

**Issue by seelabs** [XRPLF/rippled#4532]
## Issue Description
Since the introduction of the new the number class, there's a way that can be transaction breaking in a sneaky way: any constants calculated outside of a transaction will be calculated with the switchover enabled. If any of those constants are calculated to have a different value than before that's transaction breaking outside of an amendment and very bad. We need to audit the code for calculations of constants to make sure they all evaluate to the same values with and without the new number class. For example, this: https://github.com/gregtatcam/rippled/blob/5dc86be4e70b3e852ea18ed27e15a0d29496af36/src/ripple/protocol/impl/STAmount.cpp#L455-L456

## Expected Result

All constants outside of a transaction (like statics) need to evaluate to the same value with and without the new number class amendment activate.

## Action

The code should be audited to find all constants use the new number class that are evaluated outside of a transaction (any globals/static/or function statics). Once these constants are identified, evaluate them with the new amendment both enabled and disabled. If the constant evaluates to different values, identify it and we'll see how to make it evaluate to the old value.

**Comment by ximinez** [comment]
# Findings

## Audit startup initialization of `static` variables

The first audit (suggested by @seelabs elsewhere) was to set a breakpoint on the switchover getter functions (`getStatic...Switchover()`) and on `main`, then keep track of all values that make use of the switchover before `main` starts.

The only hits were in the initialization stack for `uRateOne` (https://github.com/XRPLF/rippled/blob/develop/src/ripple/protocol/impl/STAmount.cpp#L476), which was identified early on as a potential issue.

Then I wrote a simple test computing the value with and without the switchovers.
```
    std::vector<std::uint64_t> results;
    results.reserve(4);
    for (bool num : { false, true })
    {
        for (bool sta : { false, true })
        {
            NumberSO numSO(num);
            STAmountSO staSO(sta);
            std::uint64_t const uRateOne = getRate(STAmount(1), STAmount(1));
            results.push_back(uRateOne);
        }
    }
    for (auto const& result : results)
    {
        assert(result == results[0]);
    }
```
Unsurprisingly, the values were the same.

## Audit `static` variables inside functions

I searched rippled code for `static .*(STAmount|IOUAmount|XRPAmount)`. There were under 30 hits. All of them were function declarations, not variables, except one:
```
static STAmount const empty{};
```
https://github.com/XRPLF/rippled/blob/develop/src/ripple/protocol/impl/STObject.cpp#L605
Needless to say, that constructs identical objects for all four combinations of the switchover variables.

## Change initialization values - see what breaks

In the AMM branch, I changed the initialization of the switchover variables to `false`, and ran unit tests. Three suites had failures: AMM, Number, and Taker.

I looped over the tests with all the possible cominations of the `Number` and `STAmount` switchover flags, similar to https://github.com/gregtatcam/rippled/blob/amm-core-functionality/src/test/app/Taker_test.cpp#L276-L278.

To summarize, no matter which order I initialized the variables in, the iterations where both were true consistently passed. The iterations that had failures always failed the same tests in the same places.

This is the result I would expect if there were no constants dependent on these flags calculated outside of a transaction.

I know this isn't an absolutely exhaustive test, but between not finding any obvious static variables, and not finding any startup variables affected by the flags, I think it's safe to tentatively conclude that there are no constants which are affected by the switches.

If there were to be any next steps, I think it would be to manually go through every occurrence of `static` (and `constexpr`?) and look for any other variable types that could possible be affected. However, I think that is unnecessary at this point. I think it's safe to close this issue. If there are any concerns, feel free to re-open or open a new issue.
