### ISSUE TITLE
[Rippled do not follow limit values as per documentation in many API's] (Version: [1.11.0-rc2])

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/rippled#4540]
## Issue Description
As per documentation for [account_channels](https://xrpl.org/account_channels.html#account_channels), Limit cannot be less than 10 or more than 400 but rippled do not follow this boundary values.

## Steps to Reproduce
Provide limit value less than 10 or greater than 400.

## Expected Result
`invalidParams` error

## Actual Result
No error

**Comment by mounikakun** [comment]
As per documentation for [account_objects](https://xrpl.org/account_objects.html#account_objects)limit must be within the inclusive range 10 to 400 but rippled do not follow this boundary values.

**Comment by mounikakun** [comment]
Issue exists for account_offers also.

**Comment by intelliot** [comment]
The API behavior is fine; this is something that should be clarified in the docs. Closing this issue in favor of https://github.com/XRPLF/xrpl-dev-portal/issues/1985
