### ISSUE TITLE
[account_tx with ledger_index_max value out of ledger range do not return error] (Version: [1.11.0-rc2])

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/rippled#4544]
## Steps to Reproduce

`{
    "method": "account_tx",
    "params": [
        {
            "account": "rH9pnDCtgAbFjozbZQuJWvPM8QHweXgZhj",
            "ledger_index_max": 38923558
        }
    ]
}`
## Expected Result

`lgrIdxMalformed`
## Actual Result

No error

**Comment by mounikakun** [comment]
Issue exists for ledger_index_min also.

**Comment by yinyiqian1** [comment]
this issue was already solved by @PeterChen13579  but you need to set the api_version > 1
