### ISSUE TITLE
[[account_tx] with non existent account do not return an error.] (Version: [1.11.0-rc2])

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/rippled#4546]
## Steps to Reproduce

`Request:
{ "method": "account_tx", "params": [ { "account": "rH9pnDCtgAbFjozbZQuJWvPM8QHweXgZhj" } ] }`
## Expected Result

`actNotFound`
## Actual Result

`{ "result": { "account": "rH9pnDCtgAbFjozbZQuJWvPM8QHweXgZhj", "ledger_index_max": 28952659, "ledger_index_min": 23333389, "limit": 0, "status": "success", "transactions": [], "validated": true } }`

**Comment by mounikakun** [comment]
Issue exists in gateway_balances also.

**Comment by yinyiqian1** [comment]
close. please refer to https://github.com/XRPLF/rippled/pull/4619#issuecomment-1724579487
