### ISSUE TITLE
Add a constant for ripple epoch offset

### ISSUE THREAD

**Issue by gregtatcam** [XRPLF/rippled#4563]
## Issue Description

The [epoch offset](https://xrpl.org/basic-data-types.html#specifying-time) is currently hard-coded in multiple files as seconds(946684800) in (core/Pg.cpp, basics/chrono.h, rpc/handlers/AMMInfo.cpp) and as days(10957) (core/impl/TimeKeeper.cpp, test/jtx/impl/ManualTimeKeeper.cpp).

Epoch offset: 2000-01-01 00:00:00 UTC is 946684800s from 1970-01-01 00:00:00 UTC

## Expected Result

Define a constant

**Comment by HowardHinnant** [comment]
Here's one verbose but readable way to write this constant:
```c++
#include <date/date.h>
// ...
std::chrono::seconds constexpr offset = date::sys_days{year{2000}/1/1} - date::sys_days{year{1970}/1/1};
```

**Comment by Bronek** [comment]
I have this in https://github.com/XRPLF/rippled/pull/4775
