### ISSUE TITLE
Cancelled NFT bids haven't returned the XRP back

### ISSUE THREAD

**Issue by TwoBigPaws133** [XRPLF/rippled#4584]
## Issue Description
placed bids for NFT on onxrp.com. when bid was rejected it requires cancelling to get back 2 XRP. i have over 35 cancelled rejected bids that havent returned the XRP back?

**Comment by TwoBigPaws133** [comment]
placed bids for NFT on onxrp.com. when bid was rejected it requires cancelling to get back 2 XRP. i have over 35 cancelled rejected bids that havent returned the XRP back?

**Comment by TwoBigPaws133** [comment]
![WhatsApp Image 2023-06-24 at 16 48 24](https://github.com/XRPLF/rippled/assets/137709554/3d8a93e4-6316-4dc3-9c18-f854fd40f33e)

**Comment by TwoBigPaws133** [comment]
I have replicated and sometimes it gives back 2 XRP and sometimes it doesnt.

**Comment by MarkusTeufelberger** [comment]
You seem to be confusing this with some third party website support. Please get in tough with the operator of "onxrp.com" (which honestly looks VERY sketchy to me as a side note).

**Comment by shawnxie999** [comment]
@TwoBigPaws133 does your account balance show the correct amount of total XRP?  reserve always stays in your account, it doesn't go anywhere, but reduces your _spendable_ amount

**Comment by intelliot** [comment]
@TwoBigPaws133 - please reply to shawnxie999's questions above.

If you do not reply soon, this issue will be closed due to inactivity.

**Comment by shawnxie999** [comment]
@intelliot I do believe OP asked the same question in another thread and was able to resolve the issue. It was a while ago so I couldn't find it.
