### ISSUE TITLE
`allowClawback` flag is missing from the `account_info.account_flags` response (Version: 1.12.0-beta1)

### ISSUE THREAD

**Issue by ckniffen** [XRPLF/rippled#4588]
## Issue Description
In rippled@1.11.0 a new object called `account_flags` was introduced to the `account_info` response.  An entry needs to be added for `lsfAllowClawback`

This likely was missed because work was being done on both PRs at the same time.

https://github.com/drlongle/rippled/blob/develop/src/ripple/rpc/handlers/AccountInfo.cpp#L80-L100

**Comment by intelliot** [comment]
([Clawback implementation can be found here](https://github.com/XRPLF/rippled/pull/4553))
