### ISSUE TITLE
Try Visual Studio 2022 again

### ISSUE THREAD

**Issue by thejohnfreeman** [XRPLF/rippled#4600]
If and when #4595 is merged, the [caveat](https://github.com/XRPLF/rippled/blob/54afdaa101022445856c0925434e0cfb12dda2bc/BUILD.md#minimum-requirements) about Visual Studio and Boost in our build instructions will be out-of-date. We need to try to build with VS2022 again. If it works, remove the caveat. Otherwise, update the caveat.

**Comment by legleux** [comment]
Looks good. 
I did got this, downgraded and it worked:
```
ERROR: Conflict in googleapis/cci.20220711:
    'googleapis/cci.20220711' requires 'protobuf/3.21.4' while 'grpc-proto/cci.20220627' requires 'protobuf/3.21.9'.
    To fix this conflict you need to override the package 'protobuf' in your root package.
```
[Conan profiles and unittest results](https://gist.github.com/legleux/c96a3bf87c598b482d2e25059dd43e95)
