### ISSUE TITLE
Testnet and Devnet servers should reflect reserves for creating NFTs

### ISSUE THREAD

**Issue by DennisDawson** [XRPLF/rippled#4605]
## Summary
Testnet and Devnet currently don't seem to reflect reserves when minting NFTs. 

## Motivation
It would be a better user experience if the reserves were taken from the balance, so that users will not be surprised by reserve requirements when minting on Mainnet.

## Solution
Ensure that reserves are reflected on Testnet and Devnet as they are on Mainnet.

**Comment by ckniffen** [comment]
I am confused as to how mainet is treating reserves differently.  Can you elaborate on that?

**Comment by DennisDawson** [comment]
Could just be my misunderstanding of how reserves are handled. I'll catch up with you offline.

**Comment by DennisDawson** [comment]
This was based on my misconception. Never mind.
