### ISSUE TITLE
What library is this looking for?

### ISSUE THREAD

**Issue by 7queue** [XRPLF/rippled#4613]
Hello,

https://github.com/XRPLF/rippled/blob/f7dd37e355754e576fee4bda357cec64a35871aa/CMakeLists.txt#L95

`find_package(date REQUIRED)`

Is this a special date function or something found in libc?

Thanks

**Comment by dangell7** [comment]
I'm also getting this error on `Release` build for Mac M1.

**Comment by 7queue** [comment]
It looks like it's looking for `https://github.com/HowardHinnant/date` based on what `https://github.com/conan-io/conan-center-index/blob/master/recipes/date/all/conandata.yml` says. It's trying to connect to `https://center.conan.io` that my firewalls warn me not to trust and block any access to it!

**Comment by thejohnfreeman** [comment]
Yes, it is looking for Howard's library. Conan will try to download all dependencies from Conan Center; `date` is just the second one in the [list](https://github.com/XRPLF/rippled/blob/develop/conanfile.py#L26-L39). Sounds like you'll need to adjust your firewall. That support is out of scope for this project.

**Comment by intelliot** [comment]
If adjusting your firewall doesn't resolve the issue, please open a new issue to explain.
