### ISSUE TITLE
account_nfts rpc result property names

### ISSUE THREAD

**Issue by Curtis-D** [XRPLF/rippled#4625]
## Issue Description
Sequence and Taxon (maybe NFTokenTaxon is needed to differentiate) seem like a better fit as properties for the return from account_nfts than nft_serial and NFTokenTaxon 

## Steps to Reproduce
RPC call with with following body:

```
{
    "method": "account_nfts",
    "params": [
        {
        "account": "rBX7PzVDy6Pwj9tAqC4tN7jxXXKG1Z4JRF",
        "ledger_index": "validated"
        }
    ]
}
```

## Expected Result
```
...

"account_nfts": [
    {
        "Flags": 8,
        "Issuer": "rBX7PzVDy6Pwj9tAqC4tN7jxXXKG1Z4JRF",
        "NFTokenID": "0008138873749B2656849ADDE77BA4656E2E604AE3C778300C1908B000000916",
        "Taxon": 1,
        "TransferFee": 5000,
        "URI": "697066733A2F2F62616679626569667933786C64657562376D6968747778656F33656C616F71327A76657134776A37766C376E706872366C71326B7A6B63703271712F323035382E6A736F6E",
        "Sequence": 2326
    },

...
```

## Actual Result
```
...

"account_nfts": [
    {
        "Flags": 8,
        "Issuer": "rBX7PzVDy6Pwj9tAqC4tN7jxXXKG1Z4JRF",
        "NFTokenID": "0008138873749B2656849ADDE77BA4656E2E604AE3C778300C1908B000000916",
        "NFTokenTaxon": 1,
        "TransferFee": 5000,
        "URI": "697066733A2F2F62616679626569667933786C64657562376D6968747778656F33656C616F71327A76657134776A37766C376E706872366C71326B7A6B63703271712F323035382E6A736F6E",
        "nft_serial": 2326
    },

...
```

## Environment
Running an RPC call to https://s1.ripple.com:51234/

**Comment by Curtis-D** [comment]
Let me just give an example:

https://xrpl.org/nft_info.html

this returns:

```
 {
    "nft_id": "00080000B4F4AFC5FBCBD76873F18006173D2193467D3EE70000099B00000000",
    "ledger_index": 269,
    "owner": "rG9gdNygQ6npA9JvDFWBoeXbiUcTYJnEnk",
    "is_burned": false,
    "flags": 8,
    "transfer_fee": 0,
    "issuer": "rHVokeuSnjPjz718qdb47bGXBBHNMP3KDQ",
    "nft_taxon": 0,
    "nft_sequence": 0,
    "uri": "https://xrpl.org",
    "validated": true,
    "status": "success"
  },
```

However when I'm getting transaction data from the ledger stream, this is what is returned:

```
{
  Account: 'r364ah9PonZUDTP2quKTo5u9rqrCW1gT6u',
  Fee: '15',
  Flags: 8,
  LastLedgerSequence: 81364384,
  Memos: [ { Memo: [Object] } ],
  NFTokenTaxon: 0,
  Sequence: 81177602,
  SigningPubKey: '0338E8641036B9DB9932242B713B29893FE4655DFD8DF53CC0FE25117D4D651775',
  SourceTag: 101102979,
  TransactionType: 'NFTokenMint',
  TransferFee: 10000,
  TxnSignature: '304402206EBDEA5E4D2215CF753808AD21B0C55D81DFF13AE6B8338F153B8BBC57340AC502200FE561DC91F662244A9AFF193B34CA192E94E606194414F074C4580E875F316D',
  URI: '697066733A2F2F6261666B72656963746E7571323671333365377A76706B647935766C69766B376D72746F366B337A35796A6A65706C707A77726965713778736865',
  hash: '9C6122F5EB27E6BCD08B76ACD23C14013A914C9545F7BCB5B30C3875290207A1',
  metaData: {
    AffectedNodes: [ [Object], [Object] ],
    TransactionIndex: 9,
    TransactionResult: 'tesSUCCESS'
  }
}
```

Maybe you can see where the confusion between NFTokenTaxon and nft_sequence/nft_serial etc. comes in?

**Comment by shawnxie999** [comment]
I believe one of the reasons of snake case for `nft_info` API is because it is a synthetically parsed API, meaning that the data is parsed inorganically and not directly retrieved from the ledger objects. But I do agree the discrepancies can cause confusions.

**Comment by intelliot** [comment]
Related context about when snake_case and PascalCase are used in the API:
- [Why fields are capitalized or lowercase in rippled requests and responses](https://github.com/XRPLF/xrpl.js/wiki/Why-fields-are-capitalized-or-lowercase-in-rippled-requests-and-responses)

**Comment by Curtis-D** [comment]
Is there any reason for a difference between nft_sequence and nft_serial? Aren't they essentially the same thing with different names

**Comment by intelliot** [comment]
Yes, `nft_sequence` was the original name; it was changed to `nft_serial`.

https://github.com/ripple/explorer/pull/642

https://github.com/XRPLF/xrpl-dev-portal/issues/1841

It was changed to `nft_serial` in order to have consistency with the field in the response of [account_nfts](https://xrpl.org/account_nfts.html).

**Comment by ledhed2222** [comment]
this wasn't the only place that this change was mentioned, but here's a link to my discord message calling out this and other changes:

https://discord.com/channels/886050993802985492/957049030481965066/1111755223065694218

**Comment by intelliot** [comment]
@Curtis-D : Is there more to do on this issue? If not, please feel free to close it. 

On the other hand, if there is something needed, please clarify what you think the next steps should be. Thanks!

**Comment by ledhed2222** [comment]
I can certainly appreciate that you’re confused! And welcome to XRPL 🤗

It’s quite difficult to make a change to our APIs once they have been released because of the wide-use and because we avoid breaking changes where possible. Some of the conventions in our APIs could be better documented, that’s for sure, but as mentioned earlier in this thread there is real rhyme to the reasoning behind each of the idiosyncrasies you’re noting. 

Are you on our Discord? That’s a great place to hang out and ask questions as well

**Comment by intelliot** [comment]
@Curtis-D : What is the API change you're requesting? For `nft_sequence` to be consistently changed to `nft_serial` everywhere?

**Comment by Curtis-D** [comment]
Yeh I believe that the NFTokenTaxon/Taxon was a Clio version issue. But I understand that it would be a breaking change for only slight convenience

**Comment by Curtis-D** [comment]
I'm going to close the issue. Some of the issues were either from Clio calls being on older versions of Clio or there was a valid explanation regarding synthetic fields. Any slight misnaming left over (which I'm not sure there is) definitely isn't worth a breaking change
