### ISSUE TITLE
Is the AccountDelete TransactionType secure? (Version: [1.10.0])

### ISSUE THREAD

**Issue by xiongjiabing** [XRPLF/rippled#4639]
hi team,
Some transactions recently observed are of type "AccountDelete", For this type, whether the transaction is secure？ As an exchange， we always consider it a success and give the user credit

**Comment by intelliot** [comment]
Yes, you can learn more about the transaction type at https://xrpl.org/accountdelete.html

You can refer to the `delivered_amount` field in the transaction metadata to see how much funds were delivered to the `Destination`. To confirm, you should also check your account's balance to verify that it is what you expect.

**Comment by xiongjiabing** [comment]
To confirm, you should also check your account's balance to verify that it is what you expect.

Is the account balance referred to here for the sender？

**Comment by xiongjiabing** [comment]
Or the payee?

**Comment by xiongjiabing** [comment]
👍

**Comment by xiongjiabing** [comment]
As you said "To confirm, you should also check your account's balance to verify that it is what you expect."
Can I automatically confirm these transactions？Because currently we manually confirm these transactions and then manually give the user credit，this is a very time consuming thing. 

Again, I should be able to identify these error codes in the program
<img width="913" alt="image" src="https://github.com/XRPLF/rippled/assets/15881236/ed9334e8-1b6c-4c80-b245-8902d531df3e">

**Comment by intelliot** [comment]
You can automatically confirm the transactions.
