### ISSUE TITLE
complete_ledgers" : "empty" "network_ledger" : "waiting"

### ISSUE THREAD

**Issue by piku143526** [XRPLF/rippled#4640]
{
   "result" : {
      "info" : {
         "build_version" : "1.11.0",
         "closed_ledger" : {
            "base_fee_xrp" : 1e-05,
            "hash" : "80C6C032E5739ABEAEEB855A173B919048D7ABC4F9BF9572C768B9B81724EF8B",
            "reserve_base_xrp" : 10,
            "reserve_inc_xrp" : 2,
            "seq" : 39996566
         },
         "complete_ledgers" : "empty",
         "hostid" : "ip-172-31-7-88",
         "initial_sync_duration_us" : "13450123731",
         "io_latency_ms" : 1,
         "jq_trans_overflow" : "0",
         "last_close" : {
            "converge_time_s" : 2.005,
            "proposers" : 6
         },
         "load" : {
            "job_types" : [
               {
                  "in_progress" : 1,
                  "job_type" : "clientRPC"
               },
               {
                  "job_type" : "ledgerData",
                  "peak_time" : 25,
                  "per_second" : 4
               },
               {
                  "job_type" : "advanceLedger",
                  "per_second" : 43
               },
               {
                  "job_type" : "fetchTxnData",
                  "per_second" : 2
               },
               {
                  "job_type" : "trustedValidation",
                  "peak_time" : 8,
                  "per_second" : 9
               },
               {
                  "job_type" : "trustedProposal",
                  "per_second" : 1
               },
               {
                  "avg_time" : 3,
                  "job_type" : "heartbeat",
                  "peak_time" : 7
               },
               {
                  "job_type" : "peerCommand",
                  "per_second" : 75
               },
               {
                  "job_type" : "SyncReadNode",
                  "peak_time" : 2,
                  "per_second" : 10
               },
               {
                  "job_type" : "AsyncReadNode",
                  "peak_time" : 2,
                  "per_second" : 941
               },
               {
                  "job_type" : "WriteNode",
                  "per_second" : 16
               }
            ],
            "threads" : 10
         },
         "load_factor" : 1,
         "network_id" : 1,
         "network_ledger" : "waiting",
         "node_size" : "huge",
         "peer_disconnects" : "224",
         "peer_disconnects_resources" : "0",
         "peers" : 3,
         "pubkey_node" : "n9Muhy1R7G29cFoLcN1Y1Lp3FaRrDJzedV6Z9SzQSoHvMAQAt8Bq",
         "pubkey_validator" : "none",
         "published_ledger" : "none",
         "server_state" : "full",
         "server_state_duration_us" : "195554629",
         "state_accounting" : {
            "connected" : {
               "duration_us" : "12918483628",
               "transitions" : "85"
            },
            "disconnected" : {
               "duration_us" : "1909486126",
               "transitions" : "73"
            },
            "full" : {
               "duration_us" : "23303770938",
               "transitions" : "61"
            },
            "syncing" : {
               "duration_us" : "0",
               "transitions" : "0"
            },
            "tracking" : {
               "duration_us" : "0",
               "transitions" : "0"
            }
         },
         "time" : "2023-Aug-02 04:56:18.627780 UTC",
         "uptime" : 38131,
         "validation_quorum" : 33,
         "validator_list" : {
            "count" : 3,
            "expiration" : "2023-Oct-24 00:00:00.000000000 UTC",
            "status" : "active"
         }
      },
      "status" : "success"
   }
}

**Comment by intelliot** [comment]
Your server has not yet synced with the network. Syncing with the network requires good connectivity. 3 peers may not be enough; 10 would be better.

Other factors include: IOPS and network speed.

Depending on whether you have a persisted ledger already, you can also consider trying the `fast_load` setting.
- https://github.com/XRPLF/rippled/blob/1.11.0/cfg/rippled-example.cfg#L1096
- https://xrpl.org/blog/2022/rippled-1.8.4.html#fast-loading

**Comment by intelliot** [comment]
If the issue hasn't been resolved, feel free to re-open this issue or create a new one.
