### ISSUE TITLE
Help make slab allocator work as custom allocator (Version: custom branch https://github.com/mtrippled/rippled/tree/slab-stvar)

### ISSUE THREAD

**Issue by mtrippled** [XRPLF/rippled#4643]
## Issue Description

This is for the memory growth OKR.

I believe that the slab allocator can help fix unbounded memory growth caused by path_find requests. The problem I'm having is unit test failures and crashing on linux gcc in the following branch: https://github.com/mtrippled/rippled/tree/slab-stvar

The problem has to do with using the slab allocator as a custom allocator for std::vector<uint256>. I C&P'd Howard's custom allocator boilerplate and modified it accordingly. However, I suspect that I'm doing something wrong. Either that, or there's something wrong with the slab allocator such that it isn't quite ready as a custom allocator for containers. I've tried a bunch of things, including changing atomic operations and also changing the size of the slab, but haven't fixed it. Basically, the l_ member variable gets scribbled on somehow so that it contains a bogus address, which then cannot be accessed. I put in a bunch of std::cout messages trying to find where this happens, but to no avail.

The branch is a WIP, but I'm mainly interested in help in 2 areas:
1) verify that the custom allocator implementation is correct, and that the slab allocator is appropriate for this activity
2) find the bug(s) causing unit test failures and subsequent crash

## Steps to Reproduce

Simply build the above branch and run unit test. It's broken on linux gcc, and assumedly other platforms.

## Expected Result

Expected behavior is passing unit tests and no crash.

## Actual Result

Unit tests failed, then core dump.

## Environment

Ubuntu 22.04 gcc11.4.0. The branch is linked to above.

**Comment by HowardHinnant** [comment]
With this change: https://github.com/HowardHinnant/rippled/commit/52425ba4059b5a6a2a0b8a1f56a1fe5639c77051 Mark's branch compiles without warnings and passes all unit tests.

**Comment by intelliot** [comment]
@sophiax851 - when you have time, can you try using the slab allocator as a custom allocator, and see if that fixes the unbounded memory growth? You can work with @ximinez and/or @HowardHinnant to do this.

**Comment by sophiax851** [comment]
Sure, we'll try it out. @intelliot

**Comment by HowardHinnant** [comment]
There's a little more work to do before this code is ready for performance testing:

1.  Remove some logging statements.
2. Correct some minor correctness issues in the slab allocator.
3. Finish reviewing code for more correctness issues.

I'll post here with a commit when the steps above are complete.  I'm hoping that will be by the end of this week.

**Comment by sophiax851** [comment]
Thanks @HowardHinnant, we won't get to it this week anyway, so not blocked at all.

**Comment by HowardHinnant** [comment]
Ok, I think this is ready for performance testing: https://github.com/HowardHinnant/rippled/tree/slab-stvar
