### ISSUE TITLE
Add comment about link compression in rippled-example.cfg

### ISSUE THREAD

**Issue by intelliot** [XRPLF/rippled#4656]
P2P link compression is documented here - https://xrpl.org/enable-link-compression.html

But it is not mentioned in rippled-example.cfg - https://github.com/XRPLF/rippled/blob/develop/cfg/rippled-example.cfg

_Originally posted by @intelliot in https://github.com/XRPLF/rippled/issues/4387#issuecomment-1678549074_

**Comment by intelliot** [comment]
Feature was added in 1.6.0 https://github.com/XRPLF/rippled/pull/3287

**Comment by florent-uzio** [comment]
@intelliot here is the PR: https://github.com/XRPLF/rippled/pull/4739
