### ISSUE TITLE
[Is this a normal node?] (Version: [1.11.0])

### ISSUE THREAD

**Issue by junghyun0783** [XRPLF/rippled#4673]
## Issue Description
I have now succeeded in running a ripple node through the docker image provided here!
What I'm curious about is whether it is possible to perform roles such as "wallet deposit processing, withdrawal processing, wallet creation" through my Ripple node.
We will share the current rippled.cfg information and the output result of server_info.
please. I must know this.
Thank you for reading this long article.

## Supporting Files
 <rippled.cfg>
[server]
port_rpc_admin_local
port_ws_public

[port_rpc_admin_local]
port = 5005
ip = 0.0.0.0
admin = 127.0.0.1
protocol = http

[port_ws_public]
port = 80
ip = 0.0.0.0
protocol = ws

[node_db]
type=NuDB
path=/var/lib/rippled/db/nudb
fast_load=1

[ledger_history]
256
[database_path]
/var/lib/rippled/db

[debug_logfile]
/var/log/rippled/debug.log

[sntp_servers]
time.windows.com
time.apple.com
time.nist.gov
pool.ntp.org

[ips]
r.ripple.com 51235

[validators_file]
validators.txt

[rpc_startup]
{ "command": "log_level", "severity": "info" }

[ssl_verify]
1

< server_info >
{
    "result": {
        "info": {
            "build_version": "1.11.0",
            "complete_ledgers": "82009983-82052432",
            "hostid": "DENY",
            "initial_sync_duration_us": "164115188",
            "io_latency_ms": 1,
            "jq_trans_overflow": "0",
            "last_close": {
                "converge_time_s": 3.001,
                "proposers": 35
            },
            "load_factor": 1,
            "peer_disconnects": "12",
            "peer_disconnects_resources": "0",
            "peers": 21,
            "pubkey_node": "n9JvTVraubatQMgeXFTjF1zThDDoiVGL8ay1kB6BGJb1qcCkQobQ",
            "server_state": "full",
            "server_state_duration_us": "148290438438",
            "state_accounting": {
                "connected": {
                    "duration_us": "40947155",
                    "transitions": "2"
                },
                "disconnected": {
                    "duration_us": "117141235",
                    "transitions": "2"
                },
                "full": {
                    "duration_us": "149953562686",
                    "transitions": "53"
                },
                "syncing": {
                    "duration_us": "135668703",
                    "transitions": "55"
                },
                "tracking": {
                    "duration_us": "82059896",
                    "transitions": "55"
                }
            },
            "time": "2023-Aug-24 04:01:27.937383 UTC",
            "uptime": 150329,
            "validated_ledger": {
                "age": 2,
                "base_fee_xrp": 1e-05,
                "hash": "2595D8EDD4071146A64326E77A9C2C33E423B6D08C59EA9AA42CBEF6D71CC28A",
                "reserve_base_xrp": 10,
                "reserve_inc_xrp": 2,
                "seq": 82052432
            },
            "validation_quorum": 28
        },
        "status": "success"
    }
}

thankyou!!!!

**Comment by mDuo13** [comment]
That looks like a normal node that should be able to successfully submit any valid transactions including ones to send & receive money on mainnet. I don't see any online deletion settings, though; you may want to [Configure Online Deletion](https://xrpl.org/configure-online-deletion.html) so that the size of your ledger store does not grow indefinitely. Otherwise, you might end up storing [5 TB of data per year](https://xrpl.org/capacity-planning.html) (rough estimate).

Feel free to reopen if you have further questions.
