### ISSUE TITLE
[Address synchronization] (Version: [1.11.0])

### ISSUE THREAD

**Issue by junghyun0783** [XRPLF/rippled#4692]
hello.
I have a question.
Currently, I am coding as follows:
We created a key pair and address.

//Create a KeyPair
KeyPair randomKeyPair = Seed.ed25519Seed().deriveKeyPair();

// Get the Classic address from testWallet
Address classicAddress = randomKeyPair.publicKey().deriveAddress();

Then, I would like to synchronize the created address to the Ripple network.

Should I use a method like RPC to synchronize?
How do I synchronize my wallet to the Ripple Network?

please. help.
Thank you for reading this long post.

**Comment by ncirelli87** [comment]
Use the Echo Command
