### ISSUE TITLE
CMake Error at .nih_c/unix_makefiles/GNU_11.4.0/Release/rippled_src-src/CMakeLists.txt:76 (find_package):   By not providing "Findlz4.cmake" in CMAKE_MODULE_PATH this project has   asked CMake to find a package configuration file provided by "lz4", but   CMake did not find one.

### ISSUE THREAD

**Issue by shazam8253** [XRPLF/rippled#4734]
We are having an issue with installing the Validator-Keys tool.  When we run these commands here is the output: 
$ cd ${YOUR_VALIDATOR_KEYS_TOOL_DIRECTORY}
$ mkdir -p build/gcc.debug
$ cd build/gcc.debug
$ cmake -DCMAKE_BUILD_TYPE=Release ../.. 

Could not find a package configuration file provided by "lz4" with any of
 the following names:

	lz4Config.cmake
	lz4-config.cmake

  Add the installation prefix of "lz4" to CMAKE_PREFIX_PATH or set "lz4_DIR"
  to a directory containing one of the above files.  If "lz4" provides a
  separate development package or SDK, be sure it has been installed.

**Comment by ximinez** [comment]
The build process changed a few months ago. Take a look at https://github.com/XRPLF/rippled/blob/develop/BUILD.md for the updated dependencies and instructions.

**Comment by shazam8253** [comment]
Oh, thank you! We will try that out.

**Comment by intelliot** [comment]
If you encounter any problems with [the build instructions](https://github.com/XRPLF/rippled/blob/develop/BUILD.md), please open a new issue.
