### ISSUE TITLE
[two types (ed25519, secp256k1)]

### ISSUE THREAD

**Issue by junghyun0783** [XRPLF/rippled#4742]
hello
I am writing this because I have a simple question.
What I'm curious about is that there are two key_types in xrp: ed25519 and secp256k1, right?
However, if two types (ed25519, secp256k1) create addresses with the same master_seed,
Are the two addresses created at this time exactly the same?
I'm very curious about that.
Thank you for reading this long article.

**Comment by sublimator** [comment]
No, different keypairs are derived from the same seed entropy using "key_type" dependant algorithms. 

At the risk of too much info, note that a ripple address is a double hashing of the public key with sha256, then ripemd160.

Roughly speaking the seed is hashed until it's a valid private key value for the given "key_type", From that they do an EC operation multiplying a base point (a special known point on the curve) by the private key. This yields the public key. This is then hashed to create the ripple address.  

So: seed -> private -> public -> address

There was a sEd prefix for encoding ed25519 seeds. It seems like it has become a common practice to encode the entropy the same regardless of intended "key_type"/algorithm used. It may have been clearer without this practice.

**Comment by intelliot** [comment]
Additional details can be found at https://xrpl.org/cryptographic-keys.html.

Closing this issue as it appears to have been answered.
