### ISSUE TITLE
[How to verify the created address] (Version: [1.11.0])

### ISSUE THREAD

**Issue by junghyun0783** [XRPLF/rippled#4758]
hello.
I am a blockchain developer based in Korea.
I use the BouncyCastle library in C# language.
Ed25519 Key pair creation as well as address creation have been completed.
I have a question here.
I would like to verify the address I created.
For example, on Ripple’s official website:
https://xrpl.org/
(Resources>DevTools>Transaction Sender)
If you enter the address you created in the Destination Address field, you can check whether this address is a valid address or an address that cannot be used.

Like this, I would like to implement a source verification in C# language.
I would appreciate your help if you have any reference points or sources.

Thank you very much for reading this long article.

**Comment by dangell7** [comment]
I would use the [XrplCSharp](https://github.com/Transia-RnD/XrplCSharp) repository. Specifically the [IsClassicAddress](https://github.com/Transia-RnD/XrplCSharp/blob/17291652bc5280c82e249883cdf2bc5668d97775/Base/Xrpl.AddressCodec/XrplCodec.cs#L122C28-L122C49) function

**Comment by junghyun0783** [comment]
@dangell7 
First of all, thank you for your kind response.
As you said, I tried to download the XrplCSharp library in C# language, but the .NET Framework version I use does not support it.
The version I use is v4.8.1.
Is there any other way?
I checked and found that the ripplelibsharp library exists. Is it possible to verify addresses with this library?

**Comment by dangell7** [comment]
Well you could try to downgrade the library to 4.8.1 but that is a very old version and might not work.

I'm not sure about ripplelibsharp., the XrplCSharp repo was written from the other community libraries including this one but I believe they are still ahead of 4.8.1 in terms of versioning.

**Comment by junghyun0783** [comment]
@dangell7 
First of all, thank you so much.
  I created the source by referring to the XrplCSharp library.
As a result! We confirmed that the address was successfully verified.
Thanks to you, the problem has been resolved. Thank you!

**Comment by junghyun0783** [comment]
@dangell7
hello.
I found a solution!
1. Generate Ed25519 key pair
2. Create Ripple wallet address
3. Create and sign a transaction
4. Submit and broadcast your transaction to the Ripple network

I have currently completed item 2,
I would like to proceed with (3. Transaction creation and signing).
Is there any data that might be helpful?
We plan to develop in C# language.

**Comment by intelliot** [comment]
Relevant documentation can be found here: 
- https://xrpl.org/transactions.html
- https://xrpl.org/secure-signing.html
- If you run your own `rippled` server, you can use it to sign: https://xrpl.org/sign.html
