### ISSUE TITLE
Amendments Raffles

### ISSUE THREAD

**Issue by lathanbritz** [XRPLF/rippled#4771]
The idea is for the developer of the body of work that is behind the new functionality to get paid.

## Summary
When a new amendment is added and set to be released a NFT is commissioned by the developer(s) who wrote the functionality. There is then an agreed price tag associated with that work and the minimum bid on that NFT is locked to that price.

The amendment is voted in once the NFT minimum bid has been for filled and it has passed voting on the ledger.

## Motivation
Developers get paid for their efforts.

## Solution
This is then both a community tie into the amendment as well as a rigorous challenge to be approved by network operators.

**Comment by mvadari** [comment]
Who pays the funds?

**Comment by lathanbritz** [comment]
It is open to anyone that wants to contribute, grant programs could also use this (if those chose this payment route), participants of the network are also then open to fund work they see value in.

The idea is to open up funding to all network participants. There are two possible routes either as a payment for a delivered piece of work as discussed in opening of this request. 

An alternative is also a gofund-me where by XLS proposals could be funded via a goal amount releasing development of that proposal along with the funds.


Any how it a vague idea, but opens an alternative funding model to core development past the current model.

**Comment by MarkusTeufelberger** [comment]
I don't see how this applies to the code in this repository...
