### ISSUE TITLE
[Ripple network that can sign] (Version: [1.11.0])

### ISSUE THREAD

**Issue by junghyun0783** [XRPLF/rippled#4774]
hello.
I have a question regarding Ripple nodes.
Currently, I am running a Ripple node.

But here's where a problem arose.
I created a wallet address using C# language.
I tried to synchronize that address to the node through the RPC "submit" function.
However, the results were as follows.
{
     "result": {
         "error": "notSupported",
         "error_code": 75,
         "error_message": "Signing is not supported by this server.",
         "request": {
             "command": "sign",
             "fee_mult_max": 1000;
             "offline": false,
             "secret": "<masked>",
             "tx_json": {
                 "Account": "r5LWzT19hrddhReiM1yVBFki4AuaF9dUF",
                 "Amount": {
                     "currency": "XRP",
                     "issuer": "r5LWzT19hrddhReiM1yVBFki4AuaF9dUF",
                     "value": "1000"
                 },
                 "Destination": "rB2TiKtjqdoHhekTwL2JdCKDsxg276J7eJ",
                 "TransactionType": "Payment"
             }
         },
         "status": "error"
     }
}

Can't we create a node that can sign?
I think that in order to create a signing node, you need to create a full node. Is this correct?
I would like to solve this problem.
Experts, please help.

**Comment by intelliot** [comment]
You need an admin connection to the `rippled` node. Which connections are considered "admin" depends on your [rippled.cfg](https://github.com/XRPLF/rippled/blob/41cd337506f24630a55b628f2ac0df541081c818/cfg/rippled-example.cfg#L1629).

Alternatively, you could [enable public signing](https://xrpl.org/enable-public-signing.html).
