### ISSUE TITLE
[Wrong CTID returns from tx if cfg does not set network_id] (Version: [2.0.0-b2])

### ISSUE THREAD

**Issue by cindyyan317** [XRPLF/rippled#4778]
## Issue Description
Wrong CTID returns from tx if rippled starting with cfg does not set network_id

## Steps to Reproduce
1 remove [network_id] from rippled cfg
2 start rippled
3 run tx RPC

## Expected Result
no ctid if network_id not available 
server_info does not have ctid if network_id is not configured.

## Actual Result
wrong ctid
cfg without network id

![Screenshot 2023-10-19 at 09 45 45](https://github.com/XRPLF/rippled/assets/120398799/3fe5eefa-b112-47ac-b60a-0ddffb51912e)

cfg with network id
![Screenshot 2023-10-19 at 09 47 07](https://github.com/XRPLF/rippled/assets/120398799/08f6c686-4c03-43fa-932e-b2a95845acda)

## Environment
devnet

**Comment by dangell7** [comment]
Just to confirm, when you start a new rippled instance you're going back over 200k ledgers? I'm curious to know exactly how you can recreate this. 

Are you using clio in any way?

Can you paste some of the json details so I can look up transactions?

**Comment by dangell7** [comment]
When I start a new devnet rippled and query a recent transaction I get the CTID `C00D1ABD00000000` which is:

```
LedgerIndex: 858813
Tx Index: 0
NetworkID: 0
```

**Comment by cindyyan317** [comment]
>Are you using clio in any way?
I think this bug has nothing to do with Clio.

>Can you paste some of the json details so I can look up transactions?
Here is my rippled cfg
```
[ips]
s.devnet.rippletest.net 51235

[network_id]
devnet

[features]
NonFungibleTokensV1_1

[server]
mounika
port_ws_public

[port_grpc]
port = 50051
ip = 0.0.0.0
secure_gateway = 127.0.0.1

[mounika]
port = 5005
ip = 127.0.0.1
admin = 127.0.0.1
protocol = http

[port_ws_public]
port = 6006
ip = 127.0.0.1
admin = 127.0.0.1
protocol = ws

[node_db]
type=NuDB
path=/Users/cyan/data/nudb
online_delete=512
advisory_delete=0

[database_path]
/Users/cyan/data/

[debug_logfile]
/Users/cyan/data/rippled/debug.log

[sntp_servers]
time.windows.com
time.apple.com
time.nist.gov
pool.ntp.org

[validators_file]
nft-validators.txt

[rpc_startup]
{ "command": "log_level", "severity": "warning" }

[ssl_verify]
0

[beta_rpc_api]
1
```
when 
```
[network_id]
devnet
```
is there , I can get the correct ctid from tx. 
If I remove network_id session, restart rippled,
I can not get the correct ctid from tx. See the attached screenshots.

>When I start a new devnet rippled and query a recent transaction I get the CTID C00D1ABD00000000 which is:

>LedgerIndex: 858813
>Tx Index: 0
>NetworkID: 0

NetworkID should be 2 for devnet.

**Comment by cindyyan317** [comment]
devnet's network_id should be 2 ,right? 
https://github.com/XRPLF/rippled/blob/078bd606c73e73fc242c59b67866143deb19df04/src/ripple/core/impl/Config.cpp#L492

If we specify the network_id in cfg, the ctid is correct.

**Comment by dangell7** [comment]
devnet network id is 2 because you said it was 2. Call the `server_info` command and you can see what network id your running. There is no internal network id, its an agreed upon value.

So the CTID is behaving exactly as it should.

**Comment by cindyyan317** [comment]
Thanks for clarifying.
