### ISSUE TITLE
[Are the main and testnet wallet creation methods the same?] (Version: [1.11.0])

### ISSUE THREAD

**Issue by junghyun0783** [XRPLF/rippled#4792]
hello.
Suddenly something curious occurred to me.

When creating a Ripple wallet address,
Is there a difference in the way mainnet and testnet are created?
You make it the same way, right?

**Comment by lathanbritz** [comment]
'Wallet' key/pair created on any network is valid on all.

**Comment by junghyun0783** [comment]
@lathanbritz 
thank you
I have one more question.
When signing a transaction, the required values are known as unsigned transactions and seeds.
Here, Seed is the seed that generates the privateKey, right?
Then why did you pass the Seed as a parameter instead of giving a privateKey?

**Comment by lathanbritz** [comment]
Seed is the value used with your private key to sign transactions, it's the value you keep safe and never share with anyone.

Using wallets in the ecosystem make signing transactions simpler for the end users.

If your building applications using the API's these definitions become important I suggest you head over to [xrpl.org](xrpl.org) to understand the basics your asking here.

**Comment by junghyun0783** [comment]
@lathanbritz 
First of all, thank you for your kind response.
okay!
Is it correct to create a private key with a seed?

**Comment by lathanbritz** [comment]
Please refer to the documentation this should cover your questions https://learn.xrpl.org/course/intro-to-the-xrpl/lesson/accounts-on-the-xrp-ledger/

**Comment by intelliot** [comment]
Yes, you can derive the private key from a seed. It's explained here as well: https://xrpl.org/cryptographic-keys.html#private-key
