### ISSUE TITLE
[Parameters used when signing a transaction (unsigned TX, Seed)] (Version: [1.11.0])

### ISSUE THREAD

**Issue by junghyun0783** [XRPLF/rippled#4797]
From what I checked,
I understand that when signing a transaction, an unsigned transaction and a seed are required.
First, the Seed here is the seed that generates the privateKey, right?
Second, then why did you pass the Seed as a parameter instead of giving a privateKey? I know that other coins hand over the privateKey.

I'm in development, but I'm very confused. help.
Thank you for reading this long article.

**Comment by mvadari** [comment]
I recommend checking out the libraries and tutorials at https://xrpl.org/tutorials.html - it'll be a little easier to understand. It's generally discouraged to sign transactions via rippled itself.

**Comment by junghyun0783** [comment]
@mvadari 
Thank you for your kind reply.
Thanks to you, it was resolved.
