### ISSUE TITLE
[Seed creation process and starting string] (Version: [1.11.0])

### ISSUE THREAD

**Issue by junghyun0783** [XRPLF/rippled#4806]
hello. I am a Ripple wallet address developer.
Suddenly something curious occurred to me.
Should the first letter of seed always be 's'?
I understand that when generating a seed, it is generated as a random number.
However, the Seed listed on the official website always starts with 's'.

In other words, what I want to know is, does Seed have to start with 's'?

**Comment by sublimator** [comment]
The "s" is a prefix, denoting "s"eed or "s"ecret
A version byte is chosen such that base58 encoded data of a certain length
will always start with s

**Comment by junghyun0783** [comment]
@sublimator 
Thank you for your kind reply.
When referring to the official website (https://xrpl.org/cryptographic-keys.html#ed25519-key-derivation),
It has 16 bytes.

(https://xrpl.org/xrp-testnet-faucet.html) Why is the Seed value 31 bytes when created here?
  I always hear "sEd" in front... Is the prefix "sEd"?

When I checked the C++ document, there was no prefix in front of it.
Now I made it in 16 byte format.
An error occurred while signing.

**Comment by sublimator** [comment]
It uses base58 (an alphabet with 58 characters) encoding of the 
1. seed: 16 bytes
2. version byte[s]: To create `sEd` prefix requires 3 "version" bytes 
3. check sum: 4 bytes - helps with typos

So when all that together is encoded it's more than 16 characters. 

`sEd` is the common prefix for ed25519 keys, `s` is for secp256k1 keys

btw, this isn't really the place for ripple questions, it's more for development of the ripple p2p app

**Comment by junghyun0783** [comment]
@sublimator 
Ah, I see!!
Thank you again for your kind response.
Thanks, problem solved!

Also, can I ask one more question?
For other coins, PrivateKey is used when signing.
But why does Ripple use Seed?
Is there a reason to sign with a seed instead of signing with a PK created with a seed?
