### ISSUE TITLE
Initial path response result seems invalid (Version: 1.12.0)

### ISSUE THREAD

**Issue by lathanbritz** [XRPLF/rippled#4844]
## Issue Description
The path_find request returns and initial result which seems to be very different for the XRP -> IOU.

## Steps to Reproduce
execute a https://xrpl.org/path_find.html for any IOU on the XRPL.

## Expected Result
Expect the results to be quite similar.

## Actual Result
The path_find request returns and initial result which seems to be very different for the XRP -> IOU the single step path most simple one. This result is returned in the initial response of path_find.

The subsequent responses to that polling request then has quite a substantial change to that basic path result.

## Environment
Production

## Supporting Files
I used the 1 EUR:rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B as my destination, initial result was 4769048 drops and subsequent responses were around 1747671 drops.

this was stopped and then run again and "similar" results happen every time.

Why such a drastic change???

cmd request.
<img width="516" alt="Screenshot 2023-12-04 at 20 41 30" src="https://github.com/XRPLF/rippled/assets/508629/fd2ed93c-6349-4fac-a744-2177114a1094">

responses..

initial response in the UI
<img width="627" alt="Screenshot 2023-12-04 at 20 40 22" src="https://github.com/XRPLF/rippled/assets/508629/d27f4860-03be-4fce-bac5-dc9c9206254a">

initial response in browser console
<img width="974" alt="Screenshot 2023-12-04 at 20 41 02" src="https://github.com/XRPLF/rippled/assets/508629/b179c8ec-e35e-458e-a601-4846a1d8fa41">

follow up response in the UI
<img width="623" alt="Screenshot 2023-12-04 at 20 40 42" src="https://github.com/XRPLF/rippled/assets/508629/4fbd2b89-ec8a-4d4e-81e7-0e7975b33980">

follow up response in browser console
<img width="1051" alt="Screenshot 2023-12-04 at 20 41 07" src="https://github.com/XRPLF/rippled/assets/508629/7a321231-82a6-4fce-b68e-9712211e4882">

**Comment by lathanbritz** [comment]
I figured some of the reason why, they so different...

because the follow up response has multiple steps and the first dose not.

<img width="2560" alt="Screenshot 2023-12-04 at 21 10 33" src="https://github.com/XRPLF/rippled/assets/508629/2733878a-e375-4bc8-abeb-26d454e48b76">

the question is still though is this valid initial response though?

**Comment by tequdev** [comment]
If a good path has not been found, the amount needed to send 1EUR is 4,769,048drops, and after a good path is found, 1,747,671 drops turns out to be sufficient, does it not?

**Comment by lathanbritz** [comment]
Yip it seems the issue is simply that the initial response does not use a "path" but the subsequent do... however in this case they are so different it calls into question should that initial response even be sent?

That I think boils down to the is this a bug or not... I would ague it seems to be.

**Comment by ximinez** [comment]
The initial response is intended to be faster, so it doesn't go as deep on the search. Thus, it may find paths that aren't as good as later responses (or not find any at all). If you control the server, you can tweak the `path_search*` settings to change that behavior.

**Comment by lathanbritz** [comment]
```[path_search]
5
[path_search_fast]
2
[path_search_max]
10
```

is what ive been running with on my instances as its been the most "stable" and reliable for me.

but as your saying here this is configurable then that initial result could be changed, so I would assume upping that `[path_search_fast]` to a higher number for me here would then change that initial response from the cmd?

super I will give that a bash if so that's a perfectly valid solution here :)

**Comment by lathanbritz** [comment]
successfully tested and validated this.

I upped the path_search_fast to 5 and the initial response then mirrored the follow up responses.

this works as designed.
