### ISSUE TITLE
I want to enable “destination Tag”.

### ISSUE THREAD

**Issue by junghyun0783** [XRPLF/rippled#4854]
hello!
I want to enable “destination Tag”.
I want to make "requireDestinationTag": true.
I followed it by referring to (https://xrpl.org/require-destination-tags.html).
 **[TX]**
{
   "TransactionType": "AccountSet",
   "Account": "rL1n58LULPbeKAJwRq1g799X2qVQe6CQ18",
   "SetFlag": 1;
   "Memos": [
     {
       "Memo": {
         "MemoData": "7B2270617468223A222F726571756972652D64657374696E6174696F6E2D746167732E68746D6C222C22627574746F6E223A2273656E642D61636 36F756E74736574222C2273746570223A332C22746F74616C7374657073223A367D",
         "MemoFormat": "6170706C69636174696F6E2F6A736F6E",
         "MemoType": "68747470733A2F2F6769746875622E636F6D2F5852504C462F7872706C2D6465762D706F7274616C2F626C6F622F6D61737465722F746F6F6C2F4 94E5445524143544956455F5455544F5249414C535F524541444D452E6D64"
       }
     }
   ],
   "Flags": 0,
   "Sequence": 43891665,
   "Fee": "12",
   "LastLedgerSequence": 43893644
}

I created and sent a tx like this...
"requireDestinationTag": does not change to true.

**[result]**
{{ "accepted": true, "account_sequence_available": 43891710, "account_sequence_next": 43891710, "applied": true, "broadcast": true, "engine_result": "tesSUCCESS", "engine_result_code": 0, "result_message": "The transaction was applied. Only final in a validated ledger.", "kept": true, "open_ledger_cost": "10", "queued": false, "status": "success", "tx_blob": "", "tx_json": { "Account": "rGG9k2shfmrYsuoonsDLjUgNUugfL72Ps6", "Fee": "12", "Flags": 2147483648, "LastLedgerSequence": 43893466, "Memos": [ { "Memo": { "MemoData": "7B2270617468 223A222F726571756972652D64657374696E6174696F6E2D746167732E68746D6C222C22627574746F6E223A2273656E642D6163636F756E74736574222C2 273746570223A332C22746F74616C7374657073223A367D ", "MemoFormat": "6170706C69636174696F6E2F6A736F6E", "MemoType": "68747470733A2F2F6769746875622E636F6D2F5852504C462F7872706C2D6465762D706F7 274616C2F626C6F622F6D61737465722F746F6F6C2F494E5445524143544956455F5455544F5249414C535F524541444D452E6D64" } } ], "Sequence": 43891709 , "SetFlag": 1, "SigningPubKey": "ED0003A38942BDBE5F18F6EFD762DFDD6E69D86B25C69677F5E54D1B5876E47CAD", "TransactionType": "AccountSet", " TxnSignature": "B6DF28E3089A19CB8C6E16AA82C00797E0C3A5B991ABCCA52B92F3B1A4155E312842E2E1C6D39CB5FE671447899DC29B767710F0AFC5C4C36159D22D5A0BC9 00", "hash": "97925FDDABAA10632A1D5CEA2507F14C7927198BBEF9402609E07B80F95B3F65" }, "validated_ledger_index": 43893465}}

It comes out like this...
One thing I guess is that when I looked up the hash, it was “validated”: false.
What can I do to solve this problem? I need help.

**Comment by sublimator** [comment]
You should find a ripple developer forum/discord etc

**Comment by intelliot** [comment]
If you're using that account on Testnet, I think requireDestinationTag was set to true. https://testnet.xrpl.org/accounts/rL1n58LULPbeKAJwRq1g799X2qVQe6CQ18

What makes you think `lsfRequireDestTag` was not enabled?

If you'd like to chat with other developers, you can join the community Discord here: https://xrpldevs.org/

**Comment by junghyun0783** [comment]
@intelliot 
Oh, not that account.
"rJKUwXejQY8Kd1qKba6bGjJ9kmoZ1Hc6yd"
It's actually this account!!
