### ISSUE TITLE
will there be payee and payer that are the same with a transaction?

### ISSUE THREAD

**Issue by xiongjiabing** [XRPLF/rippled#4858]
hi team, will there be payee and payer that are the same with a transaction？ 
Now I've found similar transactions on other networks，e.g. CELO,TIA

Each block contains a large number of such transactions，I worry that XRP will have similar problems

**Comment by xiongjiabing** [comment]
And these transactions are very small

**Comment by mvadari** [comment]
You cannot send a Payment transaction to yourself.

**Comment by Bronek** [comment]
Indeed; as I was looking to answer this issue I found that this is enforced in preflight, so the check is very cheap to do. However I also noticed that there's no unit test for this check, will add it.

**Comment by Bronek** [comment]
Test added in https://github.com/XRPLF/rippled/pull/4860

**Comment by nixer89** [comment]
> You cannot send a Payment transaction to yourself.

I think you can send a payment transaction to yourself as long as it crosses offers (currency conversion) and the sent currency does not equal the receiving currency.

**Comment by Bronek** [comment]
> > You cannot send a Payment transaction to yourself.
> 
> I think you can send a payment transaction to yourself as long as it crosses offers (currency conversion) and the sent currency does not equal the receiving currency.

That's true, but it requires a path, hence involvement of other accounts.

**Comment by Bronek** [comment]
No changes in regard to this issue are planned in the future.
