### ISSUE TITLE
[transaction] (Version: [1.12.0])

### ISSUE THREAD

**Issue by xiongjiabing** [XRPLF/rippled#4868]
hi team,
https://github.com/XRPLF/rippled/releases/tag/2.0.0-rc7
I saw a new version recently，do we need to use XRP2.0 ?
 Do you have any good suggestions

**Comment by intelliot** [comment]
Yes, you should update to version 2.0.0. For release announcements, you can subscribe to [the mailing list](https://groups.google.com/g/ripple-server).

**Comment by mvadari** [comment]
I recommend asking these sorts of questions in the XRPL discord: xrpldevs.org
