### ISSUE TITLE
Simplified node recovery out of disk.

### ISSUE THREAD

**Issue by lathanbritz** [XRPLF/rippled#4880]
## Summary
When a node runs out of disk, is not straight forward how to recover the node.

## Motivation
Simplify the process of recovering the node.

## Solution
A rippled command line request could be issued to rippled to truncate a portion of the DB. Allowing the node operator to stand the node back up, instead of getting stuck with the same response of having no disk. Note: for deletions to take place the node has to fist function...

## Paths Not Taken
Maybe a well documented procedure on xrpl.org of how to recover a node once in this situation is sufficient.

**Comment by intelliot** [comment]
In most cases, it is fine to just manually delete `rippled`'s databases, because `rippled` primarily stores public blockchain data which is already replicated across hundreds of nodes across the network. After deleting dbs, when `rippled` is restarted, it will automatically regenerate the db and start to (gradually) backfill.

For example, if you are using:
```
[node_db]
type=NuDB
path=/var/lib/rippled/db/nudb
```

You should be able to run:
```
rm -r /var/lib/rippled/db/*
```

**Comment by lathanbritz** [comment]
> In most cases, it is fine to just manually delete `rippled`'s databases, because `rippled` primarily stores public blockchain data which is already replicated across hundreds of nodes across the network. After deleting dbs, when `rippled` is restarted, it will automatically regenerate the db and start to (gradually) backfill.


Some cases one does not want to loose a large amount of data doing this... if I could simply truncate a little off the end to get the node running again and adjust config to keep it with in the bounds of the disk.

**Comment by intelliot** [comment]
Understood, but the way NuDB works, I don't think it is possible to "truncate a little off the end". Perhaps @ximinez or @mtrippled could explain how it works and help determine whether something like this might be possible.

**Comment by mtrippled** [comment]
NuDB does not allow removing data. It is append-only. RocksDB allows this. However, there's no way to easily know what data can be removed other than online deletion, which requires rippled to be running. This describes how online deletion works: https://xrpl.org/online-deletion.html

**Comment by lathanbritz** [comment]
@mtrippled what would then be a reasonable way to stand a node back up that has run out of disk? 

As it stands at the moment one can either delete all the history as @intelliot showed above and start from scratch, go out and buy another disk and add it to the machine.


because once I restart rippled once it has run out of disk to my knowledge no matter what value you now throw in online_delete the server never gets to the point to do anything and rippled kicks out saying it has no disk left.

**Comment by intelliot** [comment]
Deleting all the history is a reasonable way because it's a blockchain - the data is already replicated across hundreds of nodes.
