### ISSUE TITLE
NFT issuer is inadvertently creating a trustline due to third-party transactions(Version: 2.1.0)

### ISSUE THREAD

**Issue by tequdev** [XRPLF/rippled#4925]
## Issue Description
Since the NFTokenAcceptOffer does not check the trust line that the issuer receives as a transfer fee in the NFTokenAcceptOffer, if the issuer deletes the trust line after NFTokenCreateOffer, the trust line is created for the issuer by the NFTokenAcceptOffer.

## Steps to Reproduce

1. Issuer has Trustline (ie: USD)
2. Mint NFToken with transfer fee
3. Transfer NFToken to Alice.
4. Alice create NFTokenOffer to bob with 10 USD
5. Issuer delete USD Trustline
6. Accept NFTokenOffer

## Expected Result

NFTokenAcceptOffer transaction fails with `terNO_LINE`

## Actual Result

NFTokenAcceptOffer transaction succeeds and a trustline is created for the issuer.

## Environment
rippled 2.1.0

## Supporting Files

https://gist.github.com/tequdev/f5cfd3f3cfbfcf4a22205052962e6cfe

**Comment by ximinez** [comment]
Do you have any example transaction(s)?

**Comment by tequdev** [comment]
> Do you have any example transaction(s)?

You can find gist code in the supporting files.

**Comment by tequdev** [comment]
This NFTokenAcceptOffer transaction creates a trustline for NFT's Issuer account.

https://testnet.xrpl.org/transactions/DB9EC35BEC75D314CAB5D4ADBF676C0ACE4EF03EAA83268921C377CD0ACF4934/detailed

NFToken issuer account
https://testnet.xrpl.org/accounts/rL4qyVGJLjch4863okbM9brrR5EhFrHZ61

**Comment by ximinez** [comment]
Yep. Confirmed that this looks like a legitimate issue.
