### ISSUE TITLE
After signing the TX, can I obtain the TX hash value using the signature value?

### ISSUE THREAD

**Issue by junghyun0783** [XRPLF/rippled#4929]
For Ripple
After signing the TX, can I obtain the TX hash value using the signature value?
I always obtained the TX hash value through submit RPC... What I want is I wonder if it is possible to obtain the tx hash value before submitting RPC.
Please, experts.
Please let me know~:)

**Comment by sublimator** [comment]
Yep, if you sign the transaction blob yourself you should be able to get
the hash
You were simply submitting the json to the submit rpc endpoint?
I think these days there's a Client#sign method in xrpl
