### ISSUE TITLE
Node upgrade] (Version: [2.1.1]

### ISSUE THREAD

**Issue by xiongjiabing** [XRPLF/rippled#4969]
https://github.com/XRPLF/rippled/releases/tag/2.1.1
hi team, Is this a mandatory upgrade？are there any breaking change modifications?

**Comment by sappenin** [comment]
@xiongjiabing Please read more [AMM Status Update](https://xrpl.org/blog/2024/amm-status-update) and [Introducing XRP Ledger version 2.1.1](https://xrpl.org/blog/2024/amm-status-update) for some more information.

**Comment by sappenin** [comment]
Closing for now, but feel free to re-open if you have issues related to rippled source code.
