### ISSUE TITLE
./rippled --unittest failed output

### ISSUE THREAD

**Issue by Xtinc-T** [XRPLF/rippled#5024]
## Issue Description
I am building the rippled release repo on my VM (Ubuntu 22.04) and when I ran ran test, initially they were going as expected. But at the end the output was something else and I am not sure what should I make of it, did the testing went well? did it gave out errors and stopped the testing?

## Expected Result
Absolutely no idea what to expect as this is my first time working with Rippled.

## Actual Result
I am attaching some of the final output lines, I literally have no clue what happened and I am learning.
![Screenshot 2024-05-21 174625](https://github.com/XRPLF/rippled/assets/71006747/2e0a3fd8-b6cb-4a70-ae10-dd472cd1c98f)
## Environment
Ubuntu 22.04 Jammy everything else is above the requirements.

**Comment by dangell7** [comment]
"Address already in use". Are you running other services on that computer?

**Comment by Xtinc-T** [comment]
Yes I checked these is nothing running, I even killed the running service which was rippled itself but everytime i killed it, it just gets assigned with different PID and goes to (LISTEN).  I killed the process, then I kill again so at time I get no process running as expect but when I lsof, I see its created automatically as if it is binded. 
![Screenshot 2024-05-22 124449](https://github.com/XRPLF/rippled/assets/71006747/53d351aa-a8e9-452e-aca5-1296cf04f6ae)

**Comment by legleux** [comment]
> Yes I checked these is nothing running, 

How'd you do that? You must have missed it because `51235` is `rippled`'s example config's peer port.

How are you "killing the service"? It wont restart if you ask it nicely.

**Comment by Xtinc-T** [comment]
I see, I got it resolved though. Turns out just needed to end the rippled service instead of service running on that port. Thanks for the help
